### ISSUE TITLE
Add ARM lwjgl libraries

### ISSUE THREAD

**Issue by mobilegmYT** [MultiMC/MultiMC5#3836] opened 2021-06-04 17:50 UTC
### Role

I play multimc without mods

### Suggestion

I'd like multimc to support downloading/linking to ARM lwjgl libraries if a arm system is detected

### Benefit

Because while mojang doesn't support arm devices officially, it would be amazing to be able to run MultiMC on the Raspberry Pi or M1 mac without having to manually specify lwjgl library locations and such

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by mobilegmYT** [comment] 2021-06-04 17:52
Just to elaborate, here's some links to arm lwjgl libraries: https://github.com/mikehooper/Minecraft. lwjgl themselves provide the latest builds, but I have not tested them: https://www.lwjgl.org/customize.

I've tested the former libraries with MC on a raspberry pi 4, and they work perfectly. I'm not sure how well they work on a m1 mac or other ARM chips though.

**Comment by mobilegmYT** [comment] 2021-06-04 17:52
(and yes I know multimc doesn't support building to ARM, but there are unofficial builds which could benifit.)

**Comment by phit** [comment] 2021-06-04 17:53
Duplicate of https://github.com/MultiMC/MultiMC5/issues/2133
Also see https://github.com/MultiMC/MultiMC5/issues/3480#issuecomment-747926533

**Closed by phit** 2021-06-04 17:53 UTC
