### ISSUE TITLE
Microsoft Account refresh failed error

### ISSUE THREAD

**Issue by SleepyBoi2852** [MultiMC/MultiMC5#4099] opened 2021-09-14 09:27 UTC
### Operating System

Windows

### Description of bug

When launching a MultiMC instance, it shows this error
![image](https://user-images.githubusercontent.com/35126957/133231695-8803453f-2101-4ab9-8325-fc5f42b85bab.png)

And multiMC says "N/A" on "Can Migrate?"
![image](https://user-images.githubusercontent.com/35126957/133232056-707b15dd-3646-4170-a0dc-ac2f72e75dbf.png)

### Steps to reproduce

* Log into Microsoft Account
* Launch Instance

### Suspected cause

It might be because of the "Can Migrate?" Thing

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by BlahBlah81** [comment] 2021-09-15 00:01
Have you tried to "Manually log in again"?

**Comment by SleepyBoi2852** [comment] 2021-09-15 02:52
> Have you tried to "Manually log in again"?

I tried to log in several times and it didn't work

**Comment by bread-tab** [comment] 2021-09-15 03:01
I have also had this issue on Windows, version 0.6.13-develop-2495. I resolved it by logging in again in the vanilla launcher (where it said there had been suspicious activity on the Microsoft account, although I didn't see any when I looked) with a verification code, then deleting the login info for the account in MultiMC and logging in again. Had to repeat the MultiMC delete-and-login process before it actually worked. The second time it asked to grant permissions to MultiMC for access to the microsoft and xbox account details, the first time it didn't.

**Comment by matthyno** [comment] 2021-09-15 19:12
> 
> 
> I have also had this issue on Windows, version 0.6.13-develop-2495. I resolved it by logging in again in the vanilla launcher (where it said there had been suspicious activity on the Microsoft account, although I didn't see any when I looked) with a verification code, then deleting the login info for the account in MultiMC and logging in again. Had to repeat the MultiMC delete-and-login process before it actually worked. The second time it asked to grant permissions to MultiMC for access to the microsoft and xbox account details, the first time it didn't.

This worked for me. All I had to do was log in on the official MC launcher and then re-verify my account on MultiMC.

**Comment by baraks300** [comment] 2021-09-15 19:13
Might your issue be related to this one?

https://github.com/MultiMC/MultiMC5/issues/4071

**Comment by phit** [comment] 2021-09-15 19:14
Duplicate of #4071

**Closed by phit** 2021-09-15 19:14 UTC
Labels: bug
