### ISSUE TITLE
I can't start any of my instances.

### ISSUE THREAD

**Issue by MLDKYT** [MultiMC/MultiMC5#3917] opened 2021-07-01 07:21 UTC
### Operating System

Windows

### Description of bug

I am trying to run an instance, but it always crashes with a log similar to this

https://paste.ee/p/Z4Tfq

### Steps to reproduce

Run Minecraft

### Suspected cause

I don't know.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by jamierocks** [comment] 2021-07-01 17:09
I'm unable to reproduce with the given reproduction steps.

**Comment by AverageComet250** [comment] 2021-07-06 16:36
Disable your antivirus and make sure you have internet.

Your log says it failed to download assets, and that means that it either failed to connect, your antivirus blocked its internet access or your computer doesn't have enough space

**Comment by jamierocks** [comment] 2021-07-13 16:25
I'm going to close this issue as unable to reproduce and no further comments have been made.

**Closed by jamierocks** 2021-07-13 16:25 UTC
Labels: maybe-bug, needs-repro
