### ISSUE TITLE
[MSA] MultiMC freezes while logging in if there are network problems

### ISSUE THREAD

**Issue by oplexz** [MultiMC/MultiMC5#4147] opened 2021-10-05 16:27 UTC
### Operating System

Windows 11 22471.1000

### Description of bug

I woke up my PC from sleep mode (MultiMC was running before I put it to sleep), tried starting an instance, and the launcher got stuck on "Logging in with XBox and Mojang services). I can't close the "Please wait" window, nor can I press "Play Offline", so I'm forced to crash it with Task Manager.

### Steps to reproduce

0. Have a MSA profile
1. Launch MultiMC
2. Put your computer to sleep
3. Wake your computer up
4. Start any instance (using MSA profile)

### Suspected cause

MultiMC does not have enough time to reconnect to MS after waking up from sleep mode?
The logging in process also requires a timeout, so the app is not completely frozen.
Logfile stops after "Error 4" (mentioned in #4131).

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by oplexz** [comment] 2021-10-05 16:28
Attachments:
![image](https://user-images.githubusercontent.com/12859907/136064073-42ad648e-ba6d-4d3c-8ca7-995107664407.png)
[MultiMC-0-msa-freeze-4147.log](https://github.com/MultiMC/MultiMC5/files/7287528/MultiMC-0-msa-freeze-4147.log)

**Comment by phit** [comment] 2021-10-05 16:33
Gonna close this as a dupe of the issue you mentioned yourself, they both boil down to lack of error handling in the login process.
Duplicate of #4131

**Closed by phit** 2021-10-05 16:33 UTC
Labels: bug
