### ISSUE TITLE
Add a progress bar for exporting instances

### ISSUE THREAD

**Issue by GBLodb** [MultiMC/MultiMC5#4142] opened 2021-10-03 09:01 UTC
### Role

All kinds of players, especilally modded ones.

### Suggestion

Add a progress bar for exporting instances, instead of freezing the window.

### Benefit

If a progress bar is unavailavle, at least a window to say that it's doing things, not a freezed window.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by phit** [comment] 2021-10-03 13:28
Duplicate of https://github.com/MultiMC/MultiMC5/issues/2610

**Closed by phit** 2021-10-03 13:28 UTC
