### ISSUE TITLE
Build Testing/Code Revision to add native Arm Support.

### ISSUE THREAD

**Issue by EndlessEden** [MultiMC/MultiMC5#4036] opened 2021-08-24 15:10 UTC
### Role

I provide packaging for multimc for ARM6h/ARM7h/ARM8h devices on linux(archlinux derivative) and test/use them myself. 

### Suggestion

build/test and revise on arm platforms

### Benefit

Add documented support for ARM based platforms.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

After reviewing and confirming there is no other documented topics on it outside of earlier closed topics. I currently use/build on ARM8h(arm64), and can confirm that minecraft does work natively with native openjdk-java and native LWJGL. 

lwjgl has been working on arm support for the last year, and it is working. However i dont expect mojang to bundle libraries (they dont seem to be targeting mac/linux anymore due to the existence of bedrock and microsoft has abandoned windows on arm all together. So any source of lwjgl will have to be native. - Offering to download a lwjgl binary to match the native os/platform is one option, and quite benifitial for cases like mac/windows[arm], but linux should opt to detect like is done with java currently. native path support is already built in.) - see https://github.com/LWJGL/lwjgl3/issues/601

With that said, i realize targeting arm*h/arm64 is not a primary goal, some transparency and making a public goal for it and adding documentation so we know what needs to be done, so the community can help contribute would go a long ways to doing it.

With that said, Thank You so much, ive used multimc for years on all my platforms. Its been a pleasure playing Minecraft(java) with Multimc taking care of all the headaches associated with it. I was only able to even start playing modded minecraft to start with because of multimc. Thank You for 1000's of hours of fun!

**Comment by phit** [comment] 2021-08-24 15:15
please use the search this has been declined countless times, MultiMC supports what Mojang supports

> due to the existence of bedrock and microsoft has abandoned windows on arm all together.

also no

**Comment by phit** [comment] 2021-08-24 15:16
Duplicate of https://github.com/MultiMC/MultiMC5/issues/2133
and many others

**Closed by phit** 2021-08-24 15:15 UTC

**Comment by EndlessEden** [comment] 2021-08-24 15:54
> 
> please use the search this has been declined countless times, MultiMC supports what Mojang supports
> 

i did, Thus why my conclusion on it being related to lwjgl and ive been using patches up to now in order to maintain multimc on arm to resolve most of these issues...

> > due to the existence of bedrock and microsoft has abandoned windows on arm all together.
> 
> also [n](https://blogs.windows.com/windowsdeveloper/2021/06/28/announcing-arm64ec-building-native-and-interoperable-apps-for-windows-11-on-arm/)[o](https://www.theverge.com/2021/6/24/22549303/windows-11-intel-bridge-android-apps-amd-arm-processors)

I have differing opinions on this given Microsofts moves to support JIT over native on ARM for x86. | their entire motivation is due to the introduction of x86_64+ARM64 hybrid CPU's coming soon. Bedrock has compatibility already due to microsft having control over it, However with java being oot with Oracle (and they uninterested afaik in making java compatible with mixed-architecture platforms)

So i disagree with this assestment, and assert my initial opinion. - But i accept this conversation and request is over with.

**Comment by peterix** [comment] 2021-08-24 16:44
The game is not available for ARM. Not yet anyway. When it is, it will make sense to look at this.
