### ISSUE TITLE
cant log in to microsoft

### ISSUE THREAD

**Issue by sophienix** [MultiMC/MultiMC5#4128] opened 2021-09-28 13:19 UTC
### Description of bug

i went to login to microsoft but it said Microsoft user authentication failed. i also linked it but i did migrate some time this month  also I cant change it I click on it and it just keeps on going to the same one i linked 

### Steps to reproduce

loging in to a microoft acount that have been migrated 

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by sophienix** [comment] 2021-09-28 13:24
fixed it just had to keep on redoing it till it worked

**Comment by sophienix** [comment] 2021-09-28 13:27
nvm its doing it again have to relogin again

**Comment by sophienix** [comment] 2021-09-28 13:28
its doing this now
![image](https://user-images.githubusercontent.com/74495871/135096036-422c190c-acae-45b6-b526-eab97cfda1a1.png)

**Comment by sophienix** [comment] 2021-09-28 13:30
yep went back to square one again  
![image](https://user-images.githubusercontent.com/74495871/135096483-b90f3e80-505d-4e9c-8b7c-47b00ae753f4.png)

**Comment by Puremin0rez** [comment] 2021-09-28 13:32
I'm having the same issue, and came here to see if anyone has reported it. All of my Microsoft accounts are failing to authenticate, and removing them and re adding them results in an authentication failed error within MultiMC after putting the code into the Microsoft site. I'm guessing there's some active issue right now.

Also - I recommend not continuously posting comments on your own issue as that's bad GitHub etiquette. Put any additional information in the original issue.

**Comment by phit** [comment] 2021-09-28 13:39
Duplicate of https://github.com/MultiMC/MultiMC5/issues/4071

**Comment by phit** [comment] 2021-09-28 13:41
eh not a dupe, but https://support.xbox.com/en-US/xbox-live-status
not an issue on MultiMC's end

**Comment by sophienix** [comment] 2021-09-28 13:48
yeah it almost a dupe but it was a migrated account and just won't give up

**Comment by sophienix** [comment] 2021-09-28 13:49
i even tried everything that was in #4071 but it didnt work

**Comment by sophienix** [comment] 2021-09-28 13:51
cant connect to https://support.xbox.com/en-US/xbox-live-status so it might just be xbox

**Comment by sophienix** [comment] 2021-09-28 13:53
can still connect to their website https://www.xbox.com/en-GB/

**Comment by sophienix** [comment] 2021-09-28 13:57
umm i just used a non migrated account and it worked it looks like you cant use migrated accounts

**Comment by sophienix** [comment] 2021-09-28 13:57
but i want to be able to use my main one not a stupid back up

**Closed** 2021-09-28 14:04 UTC
Labels: external, Auth

**Comment by sophienix** [comment] 2021-09-28 14:15
this must be fixed or people will have to buy another account if they have migrated

**Comment by sophienix** [comment] 2021-09-28 14:17
i never use this back up any way sso im getting rid of it on multi mc

**Comment by sophienix** [comment] 2021-09-28 14:18
and waiting for it to be fixed

**Comment by kb-1000** [comment] 2021-09-28 14:20
Please stop spamming this issue.
Other than that... well, Microsoft authentication isn't exactly reliable. If you want to complain, complain to Microsoft...

**Comment by peterix** [comment] 2021-09-28 14:21
The one thing that can be done here is to handle more of the errors MS auth can return in a better way. Like, we don't have to invalidate tokens because some server is overloaded or returning unrelated errors.

**Comment by peterix** [comment] 2021-09-28 14:29
I do not see this with my account. From what other people posted here, it seems like it was a temporary issue on XBox end, with their servers being overloaded.

So, try again?

**Comment by sophienix** [comment] 2021-09-28 14:35
yeah it was my bad sorry for all the complaints

**Comment by sophienix** [comment] 2021-09-28 14:36
but thats weird though was only doing it to my migrated on

**Comment by peterix** [comment] 2021-09-28 14:38
Mojang accounts go only through Mojang systems.
Microsoft accounts go through Microsoft, XBox and Mojang. 

That's 1 vs 3 things that can be broken/down for maintenance/unavailable.

**Comment by sophienix** [comment] 2021-09-28 14:43
wait im dumb i forgot i cant login to my other one caue i had to install something for it so i had to jut put a name on it thats why i was having any problems cause i was offline

**Comment by sophienix** [comment] 2021-09-28 14:45
still dont have a skin but i can deal with it since i am in beta
