### ISSUE TITLE
Process exited with code -1.

### ISSUE THREAD

**Issue by CRJButter** [MultiMC/MultiMC5#2002] opened 2017-09-26 02:32 UTC
I got a new computer and I was able to get multimc on my old one, but It will not start up. And at the same time non of my instants won't work, even new ones. I know all the mods work together. I don't know how to read code that well so. If you can help please.
Don't ask about the names. 
I'm on 1.7.10 btw
Code

MultiMC version: 0.5.0-945

Minecraft folder is:
instances/The War/minecraft

Java path is:
C:/ProgramData/Oracle/Java/javapath/javaw.exe

Java is version 1.8.0_144, using 64-bit architecture.

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  C:/Users/Conner/Desktop/Oringal/instances/The War/natives

Libraries:
  C:/Users/Conner/Desktop/Oringal/libraries/com/mojang/netty/1.6/netty-1.6.jar
  C:/Users/Conner/Desktop/Oringal/libraries/com/mojang/realms/1.3.5/realms-1.3.5.jar
  C:/Users/Conner/Desktop/Oringal/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/Conner/Desktop/Oringal/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/Conner/Desktop/Oringal/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/Conner/Desktop/Oringal/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/Conner/Desktop/Oringal/libraries/java3d/vecmath/1.3.1/vecmath-1.3.1.jar
  C:/Users/Conner/Desktop/Oringal/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  C:/Users/Conner/Desktop/Oringal/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Users/Conner/Desktop/Oringal/libraries/net/sf/jopt-simple/jopt-simple/4.5/jopt-simple-4.5.jar
  C:/Users/Conner/Desktop/Oringal/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  C:/Users/Conner/Desktop/Oringal/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  C:/Users/Conner/Desktop/Oringal/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  C:/Users/Conner/Desktop/Oringal/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  C:/Users/Conner/Desktop/Oringal/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  C:/Users/Conner/Desktop/Oringal/libraries/io/netty/netty-all/4.0.10.Final/netty-all-4.0.10.Final.jar
  C:/Users/Conner/Desktop/Oringal/libraries/com/google/guava/guava/17.0/guava-17.0.jar
  C:/Users/Conner/Desktop/Oringal/libraries/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar
  C:/Users/Conner/Desktop/Oringal/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar
  C:/Users/Conner/Desktop/Oringal/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar
  C:/Users/Conner/Desktop/Oringal/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
  C:/Users/Conner/Desktop/Oringal/libraries/com/mojang/authlib/1.5.21/authlib-1.5.21.jar
  C:/Users/Conner/Desktop/Oringal/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9/log4j-api-2.0-beta9.jar
  C:/Users/Conner/Desktop/Oringal/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9/log4j-core-2.0-beta9.jar
  C:/Users/Conner/Desktop/Oringal/libraries/tv/twitch/twitch/5.16/twitch-5.16.jar
  C:/Users/Conner/Desktop/Oringal/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/Users/Conner/Desktop/Oringal/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/Users/Conner/Desktop/Oringal/libraries/org/lwjgl/lwjgl/lwjgl/2.9.1/lwjgl-2.9.1.jar
  C:/Users/Conner/Desktop/Oringal/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.1/lwjgl_util-2.9.1.jar
  C:/Users/Conner/Desktop/Oringal/libraries/net/minecraftforge/forge/1.7.10-10.13.4.1558-1.7.10/forge-1.7.10-10.13.4.1558-1.7.10-universal.jar
  C:/Users/Conner/Desktop/Oringal/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  C:/Users/Conner/Desktop/Oringal/libraries/org/ow2/asm/asm-all/5.0.3/asm-all-5.0.3.jar
  C:/Users/Conner/Desktop/Oringal/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  C:/Users/Conner/Desktop/Oringal/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  C:/Users/Conner/Desktop/Oringal/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  C:/Users/Conner/Desktop/Oringal/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  C:/Users/Conner/Desktop/Oringal/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar
  C:/Users/Conner/Desktop/Oringal/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar
  C:/Users/Conner/Desktop/Oringal/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  C:/Users/Conner/Desktop/Oringal/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  C:/Users/Conner/Desktop/Oringal/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  C:/Users/Conner/Desktop/Oringal/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  C:/Users/Conner/Desktop/Oringal/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  C:/Users/Conner/Desktop/Oringal/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  C:/Users/Conner/Desktop/Oringal/versions/1.7.10/1.7.10.jar
  C:/Users/Conner/Desktop/Oringal/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  C:/Users/Conner/Desktop/Oringal/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.1/lwjgl-platform-2.9.1-natives-windows.jar
  C:/Users/Conner/Desktop/Oringal/libraries/tv/twitch/twitch-platform/5.16/twitch-platform-5.16-natives-windows-64.jar
  C:/Users/Conner/Desktop/Oringal/libraries/tv/twitch/twitch-external-platform/4.5/twitch-external-platform-4.5-natives-windows-64.jar

Mods:
  [1.7.10]extrautilities 1.2.12 - Installer
  backpack-2.0.1-1.7.x
  BiblioCraft[v1.11.6][MC1.7.10]
  Carpenter's Blocks v3.3.8.1 - MC 1.7.10
  Chisel-1.7.10-1.5.7
  CustomNPCs_1.7.10d(21feb16)
  Damage-Indicators-Mod-1.7.10
  Decocraft-2.4.2_1.7.10
  Dutch KCT-4.7.0-1.7.10-1.1
  FC Pack V8.02 1.7.10-1.8 FM5.1
  Flans Mod-1.7.10-4.10.0
  Greylight 2_1 by DerpiWolf-Content Pack-1.7.10-4.10.0
  Grim3212-Core-1.7.10
  Magic-Wands-Mod-1.7.10
  MrCrayfishFurnitureModv3.4.7(1.7.10)
  nobats
  OptiFine_1.7.10_HD_U_C1
  Pam's HarvestCraft 1.7.10Lb
  SecurityCraft-Mod-1.7.10
  Stefinus Guns-0.5.2

Params:
  --username  --version MultiMC5 --gameDir C:/Users/Conner/Desktop/Oringal/instances/The War/minecraft --assetsDir C:/Users/Conner/Desktop/Oringal/assets --assetIndex 1.7.10 --uuid  --accessToken  --userProperties  --userType  --tweakClass cpw.mods.fml.common.launcher.FMLTweaker

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms2939m, -Xmx5120m, -Duser.language=en]

Minecraft process ID: 4056

Using onesix launcher.

[21:30:42] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[21:30:42] [main/INFO] [LaunchWrapper]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[21:30:42] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
[21:30:42] [main/INFO] [FML]: Forge Mod Loader version 7.99.36.1558 for Minecraft 1.7.10 loading
[21:30:42] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_144, running on Windows 10:amd64:10.0, installed at C:\Program Files\Java\jre1.8.0_144
[21:30:49] [main/INFO] [FML]: Loading tweaker optifine.OptiFineForgeTweaker from OptiFine_1.7.10_HD_U_C1.jar
[21:30:50] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[21:30:50] [main/INFO] [LaunchWrapper]: Loading tweak class name optifine.OptiFineForgeTweaker
[21:30:50] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker
[21:30:50] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[21:30:50] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[21:30:50] [main/INFO] [LaunchWrapper]: Calling tweak class optifine.OptiFineForgeTweaker
[21:30:50] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:49]: OptiFineForgeTweaker: acceptOptions
[21:30:50] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:49]: OptiFineForgeTweaker: injectIntoClassLoader
[21:30:50] [main/INFO] [STDOUT]: [optifine.OptiFineClassTransformer:dbg:179]: OptiFine ClassTransformer
[21:30:50] [main/INFO] [STDOUT]: [optifine.OptiFineClassTransformer:dbg:179]: OptiFine URL: file:/C:/Users/Conner/Desktop/Oringal/instances/The%20War/minecraft/mods/OptiFine_1.7.10_HD_U_C1.jar
[21:30:50] [main/INFO] [STDOUT]: [optifine.OptiFineClassTransformer:dbg:179]: OptiFine ZIP file: java.util.zip.ZipFile@7dc222ae
[21:30:50] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[21:30:54] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[21:30:54] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[21:30:54] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[21:30:54] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLDeobfTweaker
[21:30:55] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.TerminalTweaker
[21:30:55] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.TerminalTweaker
[21:30:55] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:49]: OptiFineForgeTweaker: getLaunchArguments
[21:30:55] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[21:30:56] [main/INFO]: Setting user: <PROFILE NAME>
[OptiFine] (Reflector) Class not present: ModLoader
[OptiFine] (Reflector) Class not present: net.minecraft.src.FMLRenderAccessLibrary
[OptiFine] (Reflector) Class not present: LightCache
[OptiFine] (Reflector) Class not present: BlockCoord
[OptiFine] (Reflector) Class not present: net.minecraftforge.fml.client.SplashProgress
[21:31:02] [Client thread/INFO]: LWJGL Version: 2.9.1
[21:31:02] [Client thread/ERROR]: Couldn't set pixel format
org.lwjgl.LWJGLException: Pixel format not accelerated
	at org.lwjgl.opengl.WindowsPeerInfo.nChoosePixelFormat(Native Method) ~[lwjgl-2.9.1.jar:?]
	at org.lwjgl.opengl.WindowsPeerInfo.choosePixelFormat(WindowsPeerInfo.java:52) ~[lwjgl-2.9.1.jar:?]
	at org.lwjgl.opengl.WindowsDisplay.createWindow(WindowsDisplay.java:252) ~[lwjgl-2.9.1.jar:?]
	at org.lwjgl.opengl.Display.createWindow(Display.java:306) ~[lwjgl-2.9.1.jar:?]
	at org.lwjgl.opengl.Display.create(Display.java:848) ~[lwjgl-2.9.1.jar:?]
	at org.lwjgl.opengl.Display.create(Display.java:757) ~[lwjgl-2.9.1.jar:?]
	at net.minecraftforge.client.ForgeHooksClient.createDisplay(ForgeHooksClient.java:327) ~[ForgeHooksClient.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:432) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_144]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_144]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_144]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_144]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_144]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_144]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_144]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_144]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:236) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:297) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:162) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:53) [NewLaunch.jar:?]
[21:31:06] [Client thread/INFO] [STDOUT]: [net.minecraft.client.Minecraft:func_71377_b:349]: ---- Minecraft Crash Report ----
// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 9/25/17 9:31 PM
Description: Initializing game

org.lwjgl.LWJGLException: Pixel format not accelerated
	at org.lwjgl.opengl.WindowsPeerInfo.nChoosePixelFormat(Native Method)
	at org.lwjgl.opengl.WindowsPeerInfo.choosePixelFormat(WindowsPeerInfo.java:52)
	at org.lwjgl.opengl.WindowsDisplay.createWindow(WindowsDisplay.java:252)
	at org.lwjgl.opengl.Display.createWindow(Display.java:306)
	at org.lwjgl.opengl.Display.create(Display.java:848)
	at org.lwjgl.opengl.Display.create(Display.java:757)
	at org.lwjgl.opengl.Display.create(Display.java:739)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:452)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:236)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:297)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at org.lwjgl.opengl.WindowsPeerInfo.nChoosePixelFormat(Native Method)
	at org.lwjgl.opengl.WindowsPeerInfo.choosePixelFormat(WindowsPeerInfo.java:52)
	at org.lwjgl.opengl.WindowsDisplay.createWindow(WindowsDisplay.java:252)
	at org.lwjgl.opengl.Display.createWindow(Display.java:306)
	at org.lwjgl.opengl.Display.create(Display.java:848)
	at org.lwjgl.opengl.Display.create(Display.java:757)
	at org.lwjgl.opengl.Display.create(Display.java:739)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:452)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:236)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:297)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_144, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2648097552 bytes (2525 MB) / 2954362880 bytes (2817 MB) up to 4772593664 bytes (4551 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms2939m -Xmx5120m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	Launched Version: MultiMC5
	LWJGL: 2.9.1
	OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	GL Caps: 
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: ~~ERROR~~ NullPointerException: null
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)
[21:31:06] [Client thread/INFO] [STDOUT]: [net.minecraft.client.Minecraft:func_71377_b:359]: #@!@# Game crashed! Crash report saved to: #@!@# C:\Users\Conner\Desktop\Oringal\instances\The War\minecraft\crash-reports\crash-2017-09-25_21.31.05-client.txt
Process exited with code -1.

**Comment by CRJButter** [comment] 2017-09-26 22:23
RIP my computer doesn't have the requirements to download, but I will save for when I get a new beefier pc(I had to get this computer on a drop of a hat). So yeah thanks for helping though.

**Comment by QuImUfu** [comment] 2017-09-26 23:01
What? Even a PC from 1998 can download a driver. What was/is the problem?
Did you find out you graphics vendor?

**Comment by CRJButter** [comment] 2017-09-28 23:11
Yes an intel, but it won't download and then I tried a different one and it said I didn't have to requirements.

**Comment by QuImUfu** [comment] 2017-09-29 02:38
If you are indeed using integrated intel graphics, this is maybe another duplicate of #1276. Intels drivers for old iGPU's do not work with newer Java versions. Worked around by using an java version older than 8u60 for MultiMC (this is what the vanilla launcher does) or by applying some hacky Driver patch from LWJGL/lwjgl#119. Or by using windows <10 or Linux.
If you have a new enough (Haswell+, edit: maybe Ivy Bridge as well) gpu an Intel driver update should help as well. 
The automated (and very bad) Intel driver installer should be able to update the drivers needed for your device: https://www.intel.com/content/www/us/en/support/detect.html?iid=dc_iduu

Likely the best course of action if a driver update doesn't help or is not available is to use this version of  java: https://files.multimc.org/downloads/jre-8u51-windows-x64.zip

Extract it somewhere in MultiMC's folder and set the javaw.exe as the Java to use in MultiMC.

**Comment by peterix** [comment] 2018-02-14 15:55
Closing due to inactivity.

**Closed by peterix** 2018-02-14 15:55 UTC
Labels: support

**Comment by Waveium** [comment] 2020-10-08 16:40
happened to me i have a gt 1030,

**Comment by CODERC755** [comment] 2022-01-02 19:51
i got a rtx 3090 same issue installed drivers when i got the pc so idk the problem
