### ISSUE TITLE
Ability to copy worlds across instances

### ISSUE THREAD

**Issue by SoniEx2** [MultiMC/MultiMC5#3093] opened 2020-04-14 01:17 UTC
System Information
-----------------------------
MultiMC version: 296ff6d

Operating System: Arch Linux x86_64

Summary of the issue or suggestion:
----------------------------------------------
Neither the "copy" nor the "add" buttons support the ability to share worlds (or at least the full level.dat) across instances. This is a bit silly. It'd be cool if you could do that, because re-creating my modified level.dat (buffet cave world with vanilla_layered biomes) is a pain. (in-game world re-creation works fine with it.)

What should happen:
------------------------------
N/A

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. N/A

2. N/A

3. N/A

Suspected cause:
---------------------------
N/A

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
N/A

Additional Info:
---------------------------
N/A

**Comment by SoniEx2** [comment] 2020-04-14 01:33
(yes, I know you can drag and drop. *grumbles about accessibility*)

**Comment by phit** [comment] 2021-03-09 21:13
Duplicate of https://github.com/MultiMC/MultiMC5/issues/2440

**Closed by phit** 2021-03-09 21:13 UTC
