### ISSUE TITLE
MultiMC cant connect to internet?

### ISSUE THREAD

**Issue by MookyLadybug** [MultiMC/MultiMC5#3494] opened 2020-12-19 23:25 UTC
System Information
-----------------------------
MultiMC version: 0.6.11

Operating System: MacBook Pro

Summary of the issue or suggestion: MultiMc is acting like it cant connect to the internet when i play minecraft. It wont let me join public servers and when i play alone it shows with no skin, as if i were playing with no internet connection.
----------------------------------------------

What should happen: 
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Open Minecraft through MultiMC

2. Exit out of multimc while still playing on java.

3. Press deny when it asks some questions.

Suspected cause: I pressed deny on some popups thats probably it.
---------------------------

Logs/Screenshots: 
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info: Basically how can I accept what i have denied access?
---------------------------

**Comment by jotoho** [comment] 2020-12-20 09:10
I am unfamiliar with macOS and it's firewall so I cannot help you with any OS-specific problems and you answering popups you didn't read doesn't make it easier.

The first thing that comes to mind is that you may be using MultiMC's offline mode. Perhaps the login token was invalidated and multimc was asking you for your minecraft login credentials again? Don't know if you would be allowed to play offline if you didn't reenter the PW.
Have you tried just closing the game and restarting minecraft through multimc? Perhaps the popup will reappear.

Otherwise you might want to look at the firewall settings of your mac and make sure both multimc and minecraft are allowed to access the internet.

If you want more help on this problem you should upload your log [using the method described here](https://github.com/MultiMC/MultiMC5/wiki/Minecraft-Logs#uploading-logs) and give us the URL so someone can take a look at it.

**Comment by MrMineO5** [comment] 2020-12-20 10:00
Try pinging a server in the server list, if java's connection to the internet is blocked, the server MOTD will not show up, if the issue is with authentication (for example invalid session, etc.) the MOTD will show up but you will not be able to connect. In the latter case, simply restart your game as @jotoho has already said, if not, check the Firewall settings in System Preferences.

**Closed** 2021-03-06 22:26 UTC
