### ISSUE TITLE
Microsoft Account error.

### ISSUE THREAD

**Issue by pobertraterson** [MultiMC/MultiMC5#4020] opened 2021-08-17 16:41 UTC
### Operating System

Linux

### Description of bug

When I built MultiMC from source (because the one in the AUR wouldn't let me sign in to a Microsoft account) it gave my this error
![image](https://user-images.githubusercontent.com/85105200/129766116-253f607f-6355-4f00-a1ed-2e05ee1fa27d.png)

### Steps to reproduce

Press 'add microsoft' in account settings

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment] 2021-08-17 16:45
Duplicate of https://github.com/MultiMC/MultiMC5/issues/4012

**Closed by phit** 2021-08-17 16:45 UTC
Labels: bug
