### ISSUE TITLE
Missing Minecraft Microsoft Account support

### ISSUE THREAD

**Issue by SirPytan** [MultiMC/MultiMC5#4066] opened 2021-09-03 10:51 UTC
### Operating System

Windows

### Description of bug

There is no option to choose if your account is a Microsoft Account or Mojang account, and because everyone needs to migrate anyway at some point, you should fix this.

I just have read your message a little too late, about not migrating until you made an update.

### Steps to reproduce

Add your Microsoft account details and it fails.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by peterix** [comment] 2021-09-03 11:04
Already fixed in dev.

Duplicate of https://github.com/MultiMC/MultiMC5/issues/3392

**Comment by peterix** [comment] 2021-09-03 11:05
If you want to check it out, switrch to the dev builds (in settings) and update.

**Closed by peterix** 2021-09-03 11:04 UTC
Labels: bug

**Comment by peterix** [comment] 2021-09-03 11:08
In the settings, switch update channel to Development and update.

![In the settings, switch update channel to Development and update](https://cdn.discordapp.com/attachments/134843027553255425/855880510031003728/unknown.png "Switching to dev")

**Comment by SirPytan** [comment] 2021-09-03 11:51
Oh, thanks very helpful. I already downloaded the latest dev build manual from your website. But good to know that there is an easier way to do it. Maybe add that on the Readme file.
