### ISSUE TITLE
Custom commands only sometimes work

### ISSUE THREAD

**Issue by theTisch21** [MultiMC/MultiMC5#3602] opened 2021-02-11 19:40 UTC
System Information
-----------------------------
MultiMC version: 0.6.11

Operating System: Windows 10 home

Summary of the issue or suggestion:
----------------------------------------------
Some commands don't work, other commands only work if there is a .minecraft directory. I have a script in node.js that only runs when there is a .minecraft directory, but works without one if the instance version is minecraft 1.15 or greater. `dir` doesn't work at all, even though it exits with code 0, the instance just stops there, saying `pre-launch command failed with code 0`.

What should happen:
------------------------------
My custom command should run, work, exit with code 0, then the instance should start

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
Testing it with `dir` command:
1. Create a new 1.14.4 instance

2. Set the custom command to `dir`

3. Attempt to launch the instance (It will fail with code 0)

4. Click the "Open .minecraft folder" button on the right side of the instance config window, which will generate a .minecraft directory

5. Launch the instance again, it will fail.

Testing it with my script:
Go to my repository and follow the setup instructions: [theTisch21/Auto-MC-Config](https://github.com/theTisch21/Auto-MC-Config)

1. Create a new 1.14.4 instance

2. Try to start it, my script won't even run, just fail with code 0

3. Click the "open .minecraft folder" to generate it

4. Launch instance again, script will work and run.

Suspected cause:
---------------------------
Likely something to do with how MultiMC executes commands.

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
Failed script launch: https://paste.ee/p/guJIl
Succeeded script launch (It only succeded after creating the .minecraft directory): https://paste.ee/p/D5Wlp
Failed `dir` launch: https://paste.ee/p/J37xL

Additional Info:
---------------------------

**Comment by Forkk** [comment] 2021-03-06 21:02
I can't reproduce this on my machine, but I'm on Linux. Could someone else on Windows test this?

The commands are run inside the `.minecraft` directory, it's possible they are failing to start because that directory doesn't exist yet.

**Comment by theTisch21** [comment] 2021-03-07 00:42
> The commands are run inside the `.minecraft` directory, it's possible they are failing to start because that directory doesn't exist yet.

I found that the script runs even without the .minecraft directory (I have my script create the directory if there isn't one), but only on versions 1.15+ . Any version before that, my script only runs once I have created a .minecraft folder manually for it.

**Comment by Forkk** [comment] 2021-03-07 14:58
Apparently `dir` is a shell builtin on Windows, which is why it doesn't work as a pre-launch command at all. If you just need a dummy command to test with, `ping` works.

We have been able to reproduce this on different OSes, but the only way is by deleting the `.minecraft` folder before launching, as normally MultiMC creates this folder as soon as you do anything (like open the edit instance window to change the pre-launch command). I'm wondering how you managed to end up in this state without deleting the folder manually.

**Comment by theTisch21** [comment] 2021-03-07 17:40
@Forkk I've figured out how to reproduce this without manually deleting the folder:


Step 1: Launch multimc  
Step 2: Open GLOBAL settings, and set the pre-launch command to `ping 127.0.0.1`  
Step 3: Create a new instance (Any version), DO NOT click the "edit instance" button or any other button
Step 4: Attempt to launch the instance WITHOUT clicking any other button  
Step 5: It will fail: https://paste.ee/p/2WTqc   
Step 6: Click the "edit instance" button, then close that window  
Step 7: Attempt to launch the instance again  
Step 8: It will succeed: https://paste.ee/p/ybcxz  

I think the solution to this bug is if MultiMC generates a `.minecraft` folder just before launch, like it generates one when clicking "edit instance" or "Minecraft folder" on the sidebar.

**Comment by theTisch21** [comment] 2021-03-09 02:08
I've figured out how to make sure a .minecraft folder exists, and have created a pull request, #3649

**Comment by peterix** [comment] 2021-03-10 02:59
Should be fixed in develop builds.

**Closed by peterix** 2021-03-10 02:59 UTC
Labels: bug

**Comment by theTisch21** [comment] 2021-03-10 03:58
@peterix I just tested it, it works in develop! Thank you!
