### ISSUE TITLE
Creating or loading into a world causes a white screen and stops responding, minecraft 1.2.3, no mods 

### ISSUE THREAD

**Issue by Lufvave** [MultiMC/MultiMC5#3557] opened 2021-01-27 13:12 UTC
System Information
-----------------------------
MultiMC version: 
0.6.11-1430

Operating System: 
Windows 10 Pro N 64bits

Summary of the issue or suggestion:
----------------------------------------------
Whenever I create or load into a world in minecraft 1.2.3 with forge installed, it displays the message 'saving chunks' and shows a white screen, it doesn't start responding and has to be killed.

What should happen:
------------------------------
load into a world without errors

Steps to reproduce the issue:
-------------------------------------------------------------
1. Create a new instance of minecraft release 1.2.3

2. Install forge 1.4.1.64

3. Launch the instance

4. Create a world or load into an existing one

Suspected cause:
---------------------------
Unknown

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
[Link to pastebin](https://pastebin.com/E5GLC8m4)

Additional Info:
---------------------------
This doesn't happen because of mods how I originally expected, it seems to occur only after forge is installed.

**Comment by AverageComet250** [comment] 2021-01-27 14:06
Two things:

1. Why are you playing 1.2.3 and

2. It says that you stopped the instance, not an error.

**Comment by Lufvave** [comment] 2021-01-27 16:31
> Two things:
> 
> 1. Why are you playing 1.2.3 and
> 2. It says that you stopped the instance, not an error.

1) I want to play 1.2.3 because that is the version of minecraft the old YogBox was built on, I've gotten nostalgic lately so I wanted to get it running on MultiMC

2) It doesn't crash, it just throws a white screen and stops responding, only thing I can do is to kill it as it doesn't even have the windows "this program is not responding" popup that closes the software

![white screen](https://user-images.githubusercontent.com/78086980/106021777-70123f80-60c5-11eb-952a-f88998e4d6d4.png)

**Comment by phit** [comment] 2021-01-27 16:41
the error points at you missing modloader, i was able to reproduce this behavior locally, looks like the forge installation is messed up

**Comment by phit** [comment] 2021-01-27 16:43
yep, fixed by adding this to the minecraft.jar via multimc

https://mcarchive.net/mods/modloader?gvsn=1.2.3

**Comment by Lufvave** [comment] 2021-01-27 17:20
> yep, fixed by adding this to the minecraft.jar via multimc
> 
> https://mcarchive.net/mods/modloader?gvsn=1.2.3
> 
> select minecraft in the version tab and then click "add to minecraft.jar", then select that zip file you can get from the link
> 
> ![](https://camo.githubusercontent.com/0c29d85123fc0a1ef316ff93b0e03afeb186e18369cc971101074f7d91d1fde5/68747470733a2f2f692e696d6775722e636f6d2f764169644458362e706e67)

Thank you very much!

**Closed** 2021-01-27 17:21 UTC
