### ISSUE TITLE
MultiMC Flatpak

### ISSUE THREAD

**Issue by Schmensch** [MultiMC/MultiMC5#3950] opened 2021-07-21 11:24 UTC
### Role

I want to switch to Fedora Silverblue and MultiMC would be the only app not available through Flatpak.

### Suggestion

Package MultiMC as a Flatpak and publish it to Flathub.

### Benefit

Flatpak is really practical and the future. I know @peterix has been against this multiple time, but I want him to reconsider. Packaging as a Flat is not really that hard. Right now I just see him very non-community friendly, actively trying to destroy MultiMC as a Flatpak.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by jamierocks** [comment] 2021-07-21 11:35
> I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

Duplicate of GH-3183 and GH-3149.

**Closed by jamierocks** 2021-07-21 11:35 UTC
