### ISSUE TITLE
report error

### ISSUE THREAD

**Issue by JoaozinhoCunha** [MultiMC/MultiMC5#3645] opened 2021-03-08 13:04 UTC
<! -
Before submitting this issue, make sure you have:

 1. Completed this form completely, the only optional field is "additional information".
    - Use as much detail as possible and state the problem clearly.
 2. Review your entire problem report.
    - Grammar and spelling errors make problem reports more difficult to understand.
 3. Make sure that your problem is not caused by a problem in your own modpack.
    - We provide support for MultiMC, not your modpack. Problems with your modpack will be ignored.
 4. Given the problem a descriptive title.
    - A good title includes a brief summary of the problem and avoids things like "Help" and "What ?!".
      The use of UPPERCASE is discouraged, as it looks like someone is shouting.
 5. Put all the information below the lines ----.
    - Makes the problem look beautiful
 
If you believe your problem is a bug, be sure to check the wiki page: https://github.com/MultiMC/MultiMC5/wiki/Report-a-Bug
->

System information
-----------------------------
MultiMC version: 5

Operating system: windows 10

Summary of problem or suggestion: minecraft account
----------------------------------------------

What should happen: no error in microsoft login (minecraft account)
------------------------------

Steps to reproduce the problem (add more if necessary):
-------------------------------------------------- -----------
1: profiles

2: account management

3: add

4: login

Suspected cause:
---------------------------

Logs / screenshots:
----------------------------
[//]: # (see https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your records.)

Additional information:
---------------------------

**Comment by phit** [comment] 2021-03-08 13:07
Please read the pinned issues before opening a new one.
Duplicate of https://github.com/MultiMC/MultiMC5/issues/3392

**Comment by JoaozinhoCunha** [comment] 2021-03-08 13:22
Please read the pinned issues before opening a new one.
Duplicate of #3392 
reponse: it has a billion errors and you want me to spend a year reading everything !!!!!???

**Comment by sambhavsaggi** [comment] 2021-03-08 14:10
Microsoft accounts are currently NOT supported. This means that any accounts that have migrated or were made recently will not work with MultiMC. Adding support is a work-in-progress. This issue should be closed because it is a duplicate of issue #3392. I recommend using the official launcher until something official is released.

**Comment by Scotsguy** [comment] 2021-03-08 14:13
Duplicate of #3392

**Closed by Scotsguy** 2021-03-08 14:13 UTC
