### ISSUE TITLE
Mac: Please move the instances folder out of the Application folder and into ~/Library/Application Support

### ISSUE THREAD

**Issue by darchitectlp** [MultiMC/MultiMC5#3322] opened 2020-08-29 23:58 UTC
Just updated to 0.6.11-1370.

MultiMC is trying to keep everything in the Applications folder, hidden inside the MultiMC.app itself. This is obviously not good. Can you switch it to having a MultiMC folder in Application Support? 

Thanks for making an amazing launcher!

**Comment by cfanoulis** [comment] 2020-08-30 10:25
It's MultiMC's philosophy to be self-contained. So I don't expect it to be even considered at this point

**Comment by Janrupf** [comment] 2020-08-30 10:56
You can select the instances folder manually if you desire so. Head to the MultiMC settings, select the MultiMC tab and then Features. There you can set a custom instances folder.
![image](https://user-images.githubusercontent.com/25827180/91657298-2f83ab00-eac0-11ea-9879-24c9bbe4d17d.png)

**Comment by darchitectlp** [comment] 2020-08-30 15:11
I've already moved my folder locations, but thank you for posting, as it may help others. But the app itself should not do this. I'm just flagging that this should be fixed at some point. The Application folder should not be used to read/write entire save files to. In addition, hiding the user's saves/mods/configs etc inside an app is very bad for the users' experience. I hope the dev will seriously consider moving to the standard implementation like Minecraft itself does. Thanks!

**Comment by kb-1000** [comment] 2020-08-30 15:13
Minecraft itself is an example of what they _don't_ want to do as far as I know. Can you put the .minecraft folder on an USB drive and start the launcher without any additional setup? This is possible with the concept of a portable app like MultiMC. Of course, if you don't like that, just move the folder somewhere else.

**Comment by phit** [comment] 2020-08-30 15:17
Duplicate of https://github.com/MultiMC/MultiMC5/issues/1457

**Comment by darchitectlp** [comment] 2020-09-07 06:21
> You can select the instances folder manually if you desire so. Head to the MultiMC settings, select the MultiMC tab and then Features. There you can set a custom instances folder.

Just out of curiosity, what is supposed to happen when the user updates MultiMC? They drag the freshly downloaded application from the Downloads folder into the Applications folder, and BOOM: every save game and modpack they've ever played is immediately wiped out, with no indication as to why or what happened. I understand that you're trying to keep MultiMC self-contained, but if you're going against the design patterns set by both Apple and Microsoft, perhaps you should reconsider. 

I'm writing all of this because MultiMC is a much better implementation of a launcher, and I'd like to keep it as my go-to. That being said, I would have a hard time recommending this app if it's going to ruin less tech-savvy players games.

**Comment by peterix** [comment] 2020-09-07 08:17
Nothing. Let it update.

**Comment by peterix** [comment] 2020-09-07 08:19
And yeah, duplicate.

**Closed by peterix** 2020-09-07 08:19 UTC
