### ISSUE TITLE
Failed to download files

### ISSUE THREAD

**Issue by Icey455** [MultiMC/MultiMC5#1474] opened 2016-02-15 02:13 UTC
Hello, i'm trying to download 16w05b and I keep getting this

MultiMC version: 0.4.10-733

Minecraft folder is:
instances/1.9 Snaps/minecraft

Java path is:
C:/ProgramData/Oracle/Java/javapath/java.exe

Instance update failed because: Failed to download the following files:
http://s3.amazonaws.com/Minecraft.Download/versions//.jar

Reason:Job 'Libraries for instance 1.9 Snaps' failed to process:
http://s3.amazonaws.com/Minecraft.Download/versions//.jar
Please try again..

Can anyone tell me how to fix this?

**Comment by Heufneutje** [comment] 2016-02-15 10:56
Duplicate of #1453

**Closed** 2016-02-15 10:57 UTC
