### ISSUE TITLE
MultiMC Crashes when attempting to open Folder from an Instance

### ISSUE THREAD

**Issue by madalienist** [MultiMC/MultiMC5#2579] opened 2019-03-26 04:16 UTC
System Information
-----------------------------
MultiMC version:0.6.5-1243

Operating System: MacOs 10.14.3

Summary of the issue or suggestion:
----------------------------------------------
I created an instance of a ModPack (FTB Unlimited Reloaded), tried to open the instance folder (or any linked folder) and MultiMC crashes (spinning ball of death).  I wanted to find the packs scripts folder so I could modify a script for the pack.  Tried dozens of times.  Restarted the machine, restarted MultiMC.  Loaded the modpack to make certain all folders were created.  Nothing worked.  

I finally copied my world over (from twitch), copied over a couple of Mods I had added.  Then launched the ModPack.  In the middle it said I was missing a mod and it gave me the option of opening the mod folder.  Wala, i could see the folders.  Added the changed script and the missing mod.  Forgot to add the journeyman folder.  

I want to be able to access the instance folder and add the journey map folder from my Twitch play through.  

What should happen:
------------------------------
Folders should open

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.Open MUltiMC. 

2.Pick a Folder associated with an Instance

3.Watch it crash.

Suspected cause:
---------------------------
No idea

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

No logs.  This happens before running an instance and after.

Additional Info:
---------------------------

**Comment by Daeruin** [comment] 2019-05-22 01:40
This is happening to me, as well. Choose Minecraft Folder, Config Folder, or Instance Folder from the side menu or the context menu, and MultiMC freezes. It gets as far as giving Finder focus, but MultiMC freezes in the background and has to be Force Quit. If I navigate to the instance folder manually, it appears to have no folders at all. And yet I can still run and play the instance.

**Comment by peterix** [comment] 2019-06-16 10:08
Yay more macOS bugs.

**Comment by Wtoll** [comment] 2020-02-17 01:28
This is still happening to me, it's really kind of annoying

**Comment by 45gfg9** [comment] 2020-03-29 11:02
Still today.
macOS 10.15.4
MultiMC 0.6.11
Java 1.8.0_241

**Comment by Ghalid** [comment] 2020-04-03 04:47
Is this related to #2529? It seems similar to my report, except I also see the freezes from in-game.

To anyone having this issue, if you don't need MultiMC to be portable, I'd suggest moving the instances folder outside the app by going to MultiMC's settings. Then, move the instances to the location you set.

Note: if you need to find the old instances location, go to where the MultiMC.app is, right click it, click "Show Package Contents", open the "Contents" folder, open the "MacOS" folder, then find the "instances" folder.

If this doesn't decrease the time MultiMC is frozen or get rid of the freezing, this issue is probably not the same as #2529, even though it sounds similar.

**Comment by Wtoll** [comment] 2020-04-03 05:44
The issues I am experiencing are that of #2529 but others may be having a different experience. From what I would guess this issue is a dupe

**Comment by 45gfg9** [comment] 2020-04-06 08:38
A little follow up:
Sometimes I could get it working as usual and in that whole session (as long I don't close the launcher) I could open any amount of external window (Finder etc) with absolutely no problem, but at next session it just freezes as how most times it would be.
This confuses me - currently I didn't find certain steps to repro this, but from what I can tell is that all these working situations happened after I started an instance. I will keep trying.

**Comment by NeRdTheNed** [comment] 2020-04-14 05:52
Just confirming that it freezes on Mojave as well, so it's not Catalina specific.

**Comment by Dylan-Kazak** [comment] 2020-12-01 16:53
Im having the exact same problem

**Comment by Dylan-Kazak** [comment] 2020-12-01 17:06
Tried moving the instance folder out of the app, Did not fix

**Comment by Dylan-Kazak** [comment] 2020-12-01 17:11
OH
I was waiting and it eventually opened.

**Comment by RocketNinja15** [comment] 2020-12-10 19:21
+bump same issue

**Comment by phit** [comment] 2021-03-09 20:39
Duplicate of https://github.com/MultiMC/MultiMC5/issues/2529

**Closed by phit** 2021-03-09 20:39 UTC
Labels: bug, needs-repro, system: macOS
