### ISSUE TITLE
Multi Mc Versions not working at all for me

### ISSUE THREAD

**Issue by Unpleasurable** [MultiMC/MultiMC5#2122] opened 2018-01-25 03:01 UTC
System Information
-----------------------------
MultiMC version:0.60

Operating System:Mac osx

Summary of the issue or suggestion: Minecraft versions wont work
----------------------------------------------

What should happen:Should work
------------------------------

Steps to reproduce the issue (Add more if needed): 
-------------------------------------------------------------
1. Not sure why it happens

2. Cant create new instances

3. Idk just isnt working in general

Suspected cause: aint sure
---------------------------

Logs/Screenshots:Instance update failed because: Component metadata update task failed while downloading from remote server:
Job 'Download of meta file index.json' failed to process:
https://v1.meta.multimc.org/index.json
Job 'Download of meta file net.minecraft/1.12.json' failed to process:
https://v1.meta.multimc.org/net.minecraft/1.12.json.
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:

**Comment by peterix** [comment] 2018-02-14 18:57
What version of macOS is this? and can you provide a more complete log?

**Comment by timmbrooks** [comment] 2018-03-19 17:14
Just tried on my daughters Mac, Discovered similar issue as reported above.
v0.6.1
OSX 10.9.5
Able to reach json through browser.  Newsfeed at bottom also stuck on 'loading news'.

What logs do you need?

**Comment by peterix** [comment] 2018-03-19 17:39
I think it's some weird issue between Qt and OSX... And still have no idea how to resolve it. I don't have such an old version of OSX available to me, so it's really hard to test this.

So let's start with the obvious:
The log is in a folder inside the `MultiMC.app` - you can get there by using one of the folder opening buttons:
Folders -> View Instance Folder -> go one level up in Finder.
Upload the `MultiMC.0.log` here.

**Comment by timmbrooks** [comment] 2018-03-19 21:31
[MultiMC-0.log](https://github.com/MultiMC/MultiMC5/files/1827027/MultiMC-0.log)
[MultiMC-1.log](https://github.com/MultiMC/MultiMC5/files/1827028/MultiMC-1.log)
[MultiMC-2.log](https://github.com/MultiMC/MultiMC5/files/1827029/MultiMC-2.log)
[MultiMC-3.log](https://github.com/MultiMC/MultiMC5/files/1827030/MultiMC-3.log)
[MultiMC-4.log](https://github.com/MultiMC/MultiMC5/files/1827032/MultiMC-4.log)

I think MultiMC-4.log might be most useful, found "The root CA certificate is not trusted for this purpose" for both rss feed and v1.meta.multimc.org.  Checked clock and tried both successfully from a browser.

**Comment by peterix** [comment] 2020-01-07 03:20
```
    7.768 D Downloading  "https://multimc.org/rss.xml"
   11.659 C Download "https://multimc.org/rss.xml" SSL Error # 1  :  "The root CA certificate is not trusted for this purpose"
   11.659 W Unimplemented code.
   11.659 C Certificate in question:
 ""
   11.659 C Failed  "https://multimc.org/rss.xml"  with reason  QNetworkReply::NetworkError(SslHandshakeFailedError)
```

**Comment by Forkk** [comment] 2021-03-09 18:01
Duplicate of #2085

**Closed by Forkk** 2021-03-09 18:01 UTC
Labels: bug, system: macOS
