### ISSUE TITLE
deleting needs to change.

### ISSUE THREAD

**Issue by P1-Kashwak** [MultiMC/MultiMC5#1444] opened 2016-02-02 04:56 UTC
The way MultiMC fully removes a pack should be changed to where when a pack gets deleted from the list it gets placed in the recycle bin instead of just deleting the whole thing with no way to get it back.

**Comment by jikuja** [comment] 2016-02-02 05:02
dupe of #1423 and #814

**Closed** 2016-02-02 06:41 UTC
