### ISSUE TITLE
The X11 connection broke: Maximum allowed requested length exceeded (code 4)

### ISSUE THREAD

**Issue by nate2014jatc** [MultiMC/MultiMC5#2375] opened 2018-08-16 12:51 UTC
System Information
-----------------------------
MultiMC version:
- Version 0.6.2-1137
- Git 6284f070c19053ae2bcf26dd9bccac2e0d35477f

Operating System: Ubuntu 18.04.1 LTS running kernel 4.15.0-32-generic

Summary of the issue or suggestion:
----------------------------------------------
MultiMC Opens, and can be navigated, however when I try to open an instance, it crashes completely

What should happen:
------------------------------
Ideally, I should have the pack open.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Launch MultiMC through any supported method.

2. Launch instance.

3. (don't) profit

Suspected cause:
---------------------------
Unknown, logs suggest it's an X11 error

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
[https://gist.github.com/nate2014jatc/7911e05eefb07fe7de8bd7a47f7be010](https://gist.github.com/nate2014jatc/7911e05eefb07fe7de8bd7a47f7be010)

Additional Info:
---------------------------
Vanilla Based instances appear to run fine, the modded pack I'm working on causes the failure above.

**Comment by peterix** [comment] 2018-11-01 00:57
I found one potential lead:
https://forum.manjaro.org/t/solved-after-update-launching-kde-applications-fails-with-the-x11-connection-broke-maximum-allowed-requested-length-exceeded-code-4/53070

**Comment by peterix** [comment] 2018-11-01 00:58
Sounds like a Qt bug?

**Comment by peterix** [comment] 2018-11-01 00:59
Also, provide game logs if possible.

**Comment by nate2014jatc** [comment] 2018-11-01 20:05
The log provided above is the only log I was able to find. The game seemingly failed to launch entirely. I'll try again later today and get back to you.

**Comment by nate2014jatc** [comment] 2018-11-05 05:35
[MultiMC-0.log](https://github.com/MultiMC/MultiMC5/files/2547035/MultiMC-0.log)
This is the only log it creates, The instance's log folder is completely empty.

It appears that the crash is related to the icon size for the pack.
![full_r_big](https://user-images.githubusercontent.com/11836893/47979751-ddb79880-e081-11e8-8930-44490f13cf70.png)

**Comment by codeka** [comment] 2020-07-11 02:16
FWIW, I see this even in the latest version, 0.6.11 -- it was also solved by choosing a different (smaller) icon for the instance.

I can choose the icon and it displayed normally in the list of instances. Just trying to edit the instances causes the whole app to crash with the message in the subject of this issue.

**Comment by phit** [comment] 2021-03-11 14:08
Duplicate of #2811 
Closing this in favor of the newer issue since it has a more clear title

**Closed by phit** 2021-03-11 14:08 UTC
Labels: display scaling, external
