### ISSUE TITLE
[Suggestion] Auto-generate server

### ISSUE THREAD

**Issue by Starwort** [MultiMC/MultiMC5#1973] opened 2017-09-01 14:20 UTC
System Information
-----------------------------
MultiMC version:
0.6.0-develop-979 lin64
Operating System:
Fedora 25
Summary of the issue or suggestion:
----------------------------------------------
Add button which auto-installs the appropriate server (i.e. for version + forge) and copies the mods into the server's mods folder.

**Comment by peterix** [comment] 2018-02-14 18:08
Server support would be sweet, and this is likely a duplicate, because this sort of idea is not new.

**Comment by phit** [comment] 2018-02-14 20:48
Duplicate of https://github.com/MultiMC/MultiMC5/issues/60

**Closed** 2018-02-17 08:45 UTC
Labels: duplicate
