### ISSUE TITLE
Allow launcher to minimize to system tray

### ISSUE THREAD

**Issue by darthvader45** [MultiMC/MultiMC5#1786] opened 2017-01-16 16:16 UTC
System Information
-----------------------------
MultiMC version: 0.5.0-929

Operating System: Win 10 64-bit

Summary of the issue or suggestion:
----------------------------------------------
When launching an instance, the console/launcher window should be able to minimize to the system tray, to not be so intrusive on the taskbar.

**Comment by peterix** [comment] 2017-01-16 16:22
Duplicate of #1785

**Closed by peterix** 2017-01-16 16:22 UTC
Labels: gubbins
