### ISSUE TITLE
MAC - Freeze

### ISSUE THREAD

**Issue by Pseudohuman93** [MultiMC/MultiMC5#2784] opened 2019-08-04 05:10 UTC
Hello!

I got an issue with the latest version of MultiMC for Mac - (Mac version - MacOS Mojave - Latest version).

For some reason, every time I try to open the app it freezes for 40 seconds. The same happens when I launch a version of Minecraft. 40 seconds too. After that, everything else works perfectly.

**Comment by peterix** [comment] 2019-08-04 16:21
AFAIK, this is macOS doing pointless work for security theater reasons. I can't really do anything about it aside from removing features (MultiMC being a portable application), or dropping macOS support altogether.

It is a problem, not sure what I'll do about it yet.

**Comment by Boundarybreaker** [comment] 2019-08-31 02:36
I'm not entirely sure this is security theater stuff. It freezes the whole screen for a good few seconds every time a new window is opened, even the game window or the new instance window.

**Comment by Sakata-MC** [comment] 2019-09-01 02:32
does the same crap in windows 10

**Comment by Heufneutje** [comment] 2019-09-02 06:46
No, this problem is specific to macOS. Create a new issue.

**Comment by adamyellen** [comment] 2019-09-07 17:39
A workaround for this issue: launch the binary from the terminal.

**Comment by Boundarybreaker** [comment] 2019-10-16 05:18
…huh. For some reason, this issue just *stopped happening* when I updated to Catalina. I have *no* idea why.

**Comment by peterix** [comment] 2019-10-16 08:18
It is a macOS bug.

**Comment by KNOBDev** [comment] 2019-11-01 03:07
Apparently, this only happens when you give MultiMC Accessibility features in Security & Privacy settings.

**Comment by refactorized** [comment] 2020-03-30 17:51
This is a definite issue, and not one i have seen on any other mac application, portable or not, native or not.  I love MultiMC but it freezes the entire visual surface of the OS everytime I launch it, or go to open files.  It's terrible.

Because i don't see this anywhere else, I have to assume it is at least very fixable (if not trivial) either as an mmc bug or an osx bug with a viable workaround.

**Comment by refactorized** [comment] 2020-03-30 18:22
I can confirm that disabling Accessibility features fixes this! I don't know why MMC needs those features, and therefore what disabling them might break, but things look good so far.

**Comment by Ianshogren** [comment] 2020-04-02 17:57
> Apparently, this only happens when you give MultiMC Accessibility features in Security & Privacy settings.

This fixed it, thank you! Do you know why?

**Comment by Zetabite** [comment] 2020-04-02 18:03
Yes. MacOS security feature is as cancer and bad as Winodws. It is supposed to stop viruses and stuff, but mostly just blocks programs whose developers wont pay those stupid licsenses to get on the good boy list

**Comment by Boundarybreaker** [comment] 2020-04-02 18:10
That ain't a satisfactory answer, since I've *used* other non-notarized apps and NONE pull this shit.

**Comment by refactorized** [comment] 2020-04-06 17:32
> Yes. MacOS security feature is as cancer and bad as Winodws. It is supposed to stop viruses and stuff, but mostly just blocks programs whose developers wont pay those stupid licsenses to get on the good boy list

That might be beside the point. Why does it need accessibility access in the first place?

**Comment by scribbler957** [comment] 2020-06-18 19:48
The only way to take advantage of some features or disable some "features" is through Accessibility settings.

**Comment by nohl** [comment] 2020-11-12 22:16
I can confirm that disabling Accessibility features fixes this too. The whole system seems to run noticeably faster.

**Comment by phit** [comment] 2021-03-09 22:11
Duplicate of https://github.com/MultiMC/MultiMC5/issues/2598

**Closed by phit** 2021-03-09 22:11 UTC
Labels: packaging, system: macOS
