### ISSUE TITLE
Unreadable tiny fonts on Win10 20H2 displays with 150% scale

### ISSUE THREAD

**Issue by Alex0322** [MultiMC/MultiMC5#3732] opened 2021-04-15 06:51 UTC
### Operating System

Windows

### Description of bug

Some of the app components dont scale font size for 150% monitor font size value (Win10 20H2). So some fonts became hard readable on 14" laptops (fullhd resolution) and common view of main window is very ugly :-(

### Steps to reproduce

1) Set display scale 150%
2) Just run MultiMC

### This issue is unique

I have searched the issue tracker and did not find an issue describing my bug.

**Comment by spannerman79** [comment] 2021-04-15 06:56
Duplicate of #3666 - starts at https://github.com/MultiMC/MultiMC5/issues/3666#issuecomment-808939302

**Closed** 2021-04-15 06:58 UTC
Labels: bug
