### ISSUE TITLE
[Suggestion] Choose what modpack versions should be installed for Twitch/Curse packs

### ISSUE THREAD

**Issue by OakBricks** [MultiMC/MultiMC5#3667] opened 2021-03-22 03:14 UTC
### Role

I want to use other versions of twitch modpacks (especially if the modpack creator uses different minecraft versions for different modpack releases)

### Suggestion

add a way to choose what modpack version you want for twitch/curseforge

### Benefit

So that if (PLAYER) want to use (X) version of modpack (Y) but the latest zip is for minecraft version (X) and the modpack supports versions (A) - (Z), tldr, MMC downloads the latest and sometimes greatest from curse which can be an issue if the modpack creator uploaded a zip for an older version of minecraft

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

![image](https://user-images.githubusercontent.com/65257189/111935721-11988a80-8a92-11eb-83f5-7654da9b6857.png)
This is what the launcher give me (i want the 1.16.5 version) 
![image](https://user-images.githubusercontent.com/65257189/111935749-26751e00-8a92-11eb-901f-77d52cb62061.png)
latest one (for 1.16.5)
![image](https://user-images.githubusercontent.com/65257189/111935800-46a4dd00-8a92-11eb-8d01-8b90ea2e0e38.png)
this is the one I want (manually downloaded from curse)

**Comment by spannerman79** [comment] 2021-03-22 05:24
It is known that generally modpacks are **extreemely** slow to update, hence the mods that are in the pack (usually) have been updated, the person playing the pack (with the mod that has been updated/fixed with whatever known bug) encounters a bug, then complains to the mod author.

No, modpacks should be the most current versions because of this.

If its curse/twitch (ie from curseforge) then manually downloading the zip and importing it is still an option and isn't needed for the Twitch section that is now part of v0.6.12

**Comment by phit** [comment] 2021-03-22 08:18
Duplicate of https://github.com/MultiMC/MultiMC5/issues/3611

**Comment by peterix** [comment] 2021-03-22 08:37
I disagree.

**Comment by thericegamer01** [comment] 2021-03-22 13:27
I came here just to ask for this. It'd make server stuff a lot easier for me because some servers use older versions of packs

**Closed** 2021-04-08 20:07 UTC
Labels: suggestion
