### ISSUE TITLE
I think I am having java trouble

### ISSUE THREAD

**Issue by Wolfy10** [MultiMC/MultiMC5#1998] opened 2017-09-24 03:38 UTC
System Information
-----------------------------
MultiMC version:

Operating System:

Summary of the issue or suggestion:
----------------------------------------------

What should happen:
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.

2.

3.

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by Wolfy10** [comment] 2017-09-24 03:38
I downloaded the new verson and it is are ready messing up I think Its my java if it is what java should I use

https://pastebin.com/QYXCEt9f

**Comment by QuImUfu** [comment] 2017-09-24 09:02
If you are using integrated intel graphics, this is likely another duplicate of #1276. Intels drivers for old iGPU's do not work with newer Java versions. Worked around by using an java version older than 8u60 for MultiMC (this is what the vanilla launcher does) or by applying some hacky Driver patch from LWJGL/lwjgl#119. Or by using windows <10 or Linux. 
If you have a new enough (Haswell+) gpu an Intel driver update should help as well. 

Likely the best course of action if a driver update doesn't help or is not available is to use this java: https://files.multimc.org/downloads/jre-8u51-windows-x64.zip

Extract it somewhere in MultiMC's folder and set the javaw.exe as the Java to use in MultiMC.

**Comment by Wolfy10** [comment] 2017-09-24 15:17
Um I am using Windows 10 so I don't know I was looking through the other issues to see if someone encountered the same problem with no luck

**Comment by QuImUfu** [comment] 2017-09-24 20:02
jeah, the problem only exist with win 10.

**Comment by Wolfy10** [comment] 2017-09-24 21:53
Do I need to use a different os or a different Java version I am using Java 7 I also tried Java 8 but got same results

**Comment by QuImUfu** [comment] 2017-09-24 22:04
Try the java version i linked to in my previous post. Just extract it somewhere and tell MultiMC to use it in the settings.
Apart from that, try updating your graphics Driver. 
Are you using an intel gpu?

**Comment by Wolfy10** [comment] 2017-09-24 22:17
No it is Windows I have never used Intel gpu my whole life

**Comment by QuImUfu** [comment] 2017-09-24 22:21
what gpu are you using than? AMD or Nvidia?

**Comment by Wolfy10** [comment] 2017-09-24 22:29
I will check and get back to you

**Comment by peterix** [comment] 2017-09-26 14:57
Well, have you tried that java version linked here?

Also:
* Make sure to use javaw.exe instead of java.exe
* Try renaming MultiMC.exe to Minecraft.exe and try to launch after that

**Comment by peterix** [comment] 2018-02-14 15:55
Closing due to inactivity.

**Closed by peterix** 2018-02-14 15:55 UTC
Labels: support
