### ISSUE TITLE
MultiMC 0.6.2 Launch Times slow

### ISSUE THREAD

**Issue by kvgeorge1** [MultiMC/MultiMC5#2473] opened 2018-11-22 22:19 UTC
System Information
-----------------------------
MultiMC version: 0.6.2

Operating System: Mojave (MacOS)

Summary of the issue or suggestion:
----------------------------------------------
When launching from the command line - MultiMC launches normally.   Launching from the Desktop is about a 45 second or so wait for launch to happen and locks up the entire machine during this time

What should happen:
------------------------------
It should launch normally

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Install Mojave

2. Java 1.8.0.191

3.

Suspected cause:
---------------------------
Java and/or MultiMC compiled wrong???

Logs/Screenshots:
----------------------------

Additional Info:
---------------------------

**Comment by kvgeorge1** [comment] 2018-11-22 22:29
Not totally wrong either.  However, as I mentioned - starting this directly in a terminal using /Applications/MultiMC/Content/MacOS/MultiMC does not experience the same problem, only when starting this by double-clicking the icon to start it.

**Comment by kvgeorge1** [comment] 2018-11-22 22:39
UPDATE:  I am thinking this is specific to MultiMC alone.

When launching an instance - the same thing occurs, but only if I launched using the icon to start up MultiMC (this doesn't happen if I use the CLI to start MultiMC as previously mentioned).  However, this behavior is NOT experienced if using the MC Launcher from Mojang.

**Comment by Goretantath** [comment] 2018-11-25 08:45
MultiMc is being super slow for me as-well, though i'm on win10 64bit and my system doesn't lock but everything gets slowed down A-LOT when i open it, also any action i do in MultiMc causes the same amount of lag until finally opening up the new window etc. I'm going to try to learn how to use cmd to open it since i didn't know that was possible and see if its fine like it was for you, If i don't edit this it most likely means cmd didnt help, otherwise i'l post my findings.

**Comment by peterix** [comment] 2018-12-10 20:30
@Goretantath that is entirely unrelated.

**Comment by Zeldinator** [comment] 2018-12-12 12:58
@kvgeorge1 Well, can relate.

However, this issue happens for me since (if I recall correctly) High Sierra. Also it seems related application size, if you delete instances the delay decreases quite a bit. I just moved my instances-folder somewhere else and symlinked it, no issue anymore.

**Comment by phit** [comment] 2021-03-09 20:43
Duplicate of https://github.com/MultiMC/MultiMC5/issues/2529

**Closed by phit** 2021-03-09 20:43 UTC
Labels: needs-repro
