### ISSUE TITLE
GUI Suggestion - Keep Group State

### ISSUE THREAD

**Issue by digitalnoise** [MultiMC/MultiMC5#2432] opened 2018-10-14 16:23 UTC
System Information
-----------------------------
MultiMC version: 0.6.2-develop-1246

Operating System: Windows 10 x64

Summary of the issue or suggestion:
----------------------------------------------

Preserve the state of groups from one launch to another.

What should happen:
------------------------------

When using groups to organize instances, preserve the state of the GUI from one launch to another.  I.e. if group A is collapsed upon close, at the next launch group A should still be collapsed.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.  Create a group.

2.  Add instance to said group.

3.  Collapse group.

4.  Close MultiMC.

5.  Re-launch MultiMC.

6.  Observe that group created in Step 1 and Collapsed in Step 3 is not collapsed upon re-launching MultiMC.

Suspected cause:
---------------------------

Code doesn't preserve group state.

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by Janrupf** [comment] 2018-10-14 17:28
duplicate of #2043

**Comment by peterix** [comment] 2018-10-31 22:48
And #851

**Closed by peterix** 2018-10-31 22:48 UTC
