### ISSUE TITLE
Install forge button grayed out

### ISSUE THREAD

**Issue by ShadeZinc46** [MultiMC/MultiMC5#4139] opened 2021-10-02 17:22 UTC
### Operating System

Windows

### Description of bug

I wanted to install forge for 1.17.1, but the install forge button, as well as the install liteloader button, are grayed out.

### Steps to reproduce

- Create a new 1.17.1 instance
- Go to Edit Instance > version
- You should see that "Install Forge" and "Install Liteloader" are grayed out
![image](https://user-images.githubusercontent.com/72886318/135726419-280b9166-d7e4-4641-8a7d-0a4c21ba3b71.png)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment] 2021-10-02 17:43
Duplicate of https://github.com/MultiMC/MultiMC5/issues/3936

**Closed by phit** 2021-10-02 17:43 UTC
Labels: bug

**Comment by kamranilv** [comment] 2022-02-10 21:50
Hello. Im just made my MultiMC minectaft 1.18.1 manually work with forge.

you have to make a txt file and paste this to it.

</>

{
  "minecraft": {
    "version": "1.18.1",
    "modLoaders": [
      {
        "id": "forge-39.0.75",
        "primary": true
      }
    ]
  },
  "manifestType": "minecraftModpack",
  "manifestVersion": 1,
  "name": "my forge minecraft",
}

</>

Ahen change it to .json file and compress to zip.

After creating a new instance with it everything should work.

**Comment by kamranilv** [comment] 2022-02-11 09:04
@phit my multimc launcher makes forge install button grey and unpressable.

**Comment by KurtB03** [comment] 2022-02-20 10:51
As for MultiMC5 V0.6.13 the "install forge" button is not supported for Minecraft 1.17 and 1.18
