### ISSUE TITLE
Twitch URL

### ISSUE THREAD

**Issue by M6444** [MultiMC/MultiMC5#2911] opened 2019-11-11 02:27 UTC
System Information
-----------------------------
MultiMC version: 0.6.7-develop-1399

Operating System: Windows 10

Summary of the issue or suggestion:
----------------------------------------------

What should happen: When I click and drag the purple install button over from curse to MultiMC it should detect the ModPack
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Any purple click and drag to the area it tells me to put on does not work

2.

3.

Suspected cause: Have no idea
---------------------------

Logs/Screenshots: 

![URLnotwork](https://user-images.githubusercontent.com/42199213/68556596-bf4c5180-03e7-11ea-9a6e-486d845158f7.PNG)

----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by peterix** [comment] 2019-11-11 08:05
The answer to that is 'no'. It shouldn't be there. Then it won't confuse you, and won't make you believe that it is possible.

**Comment by cfanoulis** [comment] 2019-11-14 13:30
duplicate of #2829 if anyone is keeping track

**Comment by UpcraftLP** [comment] 2019-11-18 17:20
twitch import page removed in https://github.com/MultiMC/MultiMC5/commit/b5adff14ab97a6f1cde677127663258a776b42ef.

**Closed** 2019-11-19 08:42 UTC
