### ISSUE TITLE
Feature Request - Recognise Manifest file when Importing MMC instance

### ISSUE THREAD

**Issue by bolte-io** [MultiMC/MultiMC5#3736] opened 2021-04-17 12:04 UTC
### Role

I share MMC instances as custom Java Arguments/RAM settings can be included, CF packs do not do this but MMC does. The only issue it recognising and using a CF manifest file if it finds one, when importing a prepared MMC instance.

### Suggestion

I would like MultiMC to recognise a Curseforge manifest file when importing an MMC instance so all the configurations of the instance can remain, but the mods can be downloaded via Curseforge.

### Benefit

This would allow custom instance settings with CF mod downloads/mod configs. It will enable instance configs to be brought to CF Packs like Java Arguments and memory settings etc, and bring the filesize down (as you could just delete the mods folder from the exported instance).

### This suggestion is unique

- [x] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by bolte-io** [comment] 2021-04-17 12:23
Basically, on your MMC instance import logic...

1. Check for manifest file when identifying its an MMC instance.
2. If found, ignore mods folder in instance & fetch the mods with existing code.
3. If not found, use the mods folder from the instance.

**Comment by spannerman79** [comment] 2021-04-17 12:51
This would require that Curseforge has a _sane_ API - for which it doesn't.

Duplicate of #3422 (and others that has asked for usage of a Curse API)

**Comment by phit** [comment] 2021-04-17 13:05
@spannerman79 this doesn't require anything that doesn't already exist, they are asking for imports to be adjusted to allow a mix of MultiMC and Curseforge, no extra API calls needed

**Comment by peterix** [comment] 2021-04-17 13:10
No mixing will be allowed.

**Closed by peterix** 2021-04-17 13:10 UTC
Labels: suggestion

**Comment by peterix** [comment] 2021-04-17 13:12
MultiMC instances should never depend on anything like Curse. Ever. Under any circumstances.

**Comment by peterix** [comment] 2021-04-17 13:26
The only OK way to handle this is to have a platform that doesn't depend on whims of whatever commercial entity currently owns Curse (or anything similar to curse).
