### ISSUE TITLE
[Feature Request] Update Modpack

### ISSUE THREAD

**Issue by blacksythe** [MultiMC/MultiMC5#3521] opened 2021-01-11 19:51 UTC
System Information
-----------------------------
MultiMC version: dev 1496

Operating System: win 10

Summary of the issue or suggestion:
----------------------------------------------
Ability to directly update mod packs, preserving options and settings, instead of downloading a new instance and overwriting the old one manually.
In addition to this add an extra mods section so we can preserve mods that we have added like quality of life mods.

**Comment by spannerman79** [comment] 2021-01-12 02:04
Duplicate of https://github.com/MultiMC/MultiMC5/issues/3356 (plus many others)

**Closed** 2021-03-06 20:17 UTC
