### ISSUE TITLE
Failed to download 16w05b (Snapshot)

### ISSUE THREAD

**Issue by ARTIKLARTIKL** [MultiMC/MultiMC5#1453] opened 2016-02-05 22:02 UTC
Hello. I have an issue with downloading Minecraft 16w05b.
When I create a new instance or try to change version of the game to 16w05b, I get this message:
![capture](https://cloud.githubusercontent.com/assets/7947367/12860378/fccbb6ee-cc10-11e5-8898-0f2fc46031bb.PNG)

I don't know how to fix this. Please help. Thanks :)

**Comment by BatHeart** [comment] 2016-02-06 13:11
Yes. I see this too. Have Mojang changed something in this latest snapshot about how the files are retrieved? I notice the actual file names are missing from the urls in the error message.

**Comment by RX14** [comment] 2016-02-06 13:15
```
   10.290 C Exception: "The base version file of this instance was meant for a newer (18) version of the vanilla launcher than this version of MultiMC supports (14)."
   10.290 W Couldn't apply profile patches because:  "The base version file of this instance was meant for a newer (18) version of the vanilla launcher than this version of MultiMC supports (14)."
```

Seems to be the root cause

**Comment by nebularazer** [comment] 2016-02-06 13:49
Seems like the [versions.json](https://s3.amazonaws.com/Minecraft.Download/versions/versions.json) moved:
>     "__comment": "This URL is being phased out! Please update your scripts to check   
       https://launchermeta.mojang.com/mc/game/version_manifest.json instead. 
       Thanks <3 --Dinnerbone",

The new [version:manifest.json](https://launchermeta.mojang.com/mc/game/version_manifest.json) contains different urls to the json for the specific version:

>    "latest": {
    "snapshot": "16w05b",
    "release": "1.8.9"
  },
  "versions": [
    {
      "id": "16w05b",
      "type": "snapshot",
      "time": "2016-02-04T15:38:39+00:00",
      "releaseTime": "2016-02-04T15:28:02+00:00",
      "url": "https://launchermeta.mojang.com/mc/game/6768033e216468247bd031a0a2d9876d79818f8f/16w05b.json"
    },
...

And finally the 16w05b.json contains the urls for client, server, and assets:

>   {
    "assetIndex": {
        "id": "1.9",
        "sha1": "81f4951679bb400bd031349e278b20b2803dba58",
        "size": 134402,
        "url": "https://launchermeta.mojang.com/mc-staging/assets/1.9/81f4951679bb400bd031349e278b20b2803dba58/1.9.json",
        "totalSize": 117237481
    },
    "assets": "1.9",
    "downloads": {
        "client": {
            "sha1": "3a07cea3cf6f1198a7db39a8bd3775883fb391be",
            "size": 8692004,
            "url": "https://launcher.mojang.com/mc/game/16w05b/client/3a07cea3cf6f1198a7db39a8bd3775883fb391be/client.jar"
        },
        "server": {
            "sha1": "9fdf8a90055b3cf689265cc30bdd9d1faf2c743c",
            "size": 8843033,
            "url": "https://launcher.mojang.com/mc/game/16w05b/server/9fdf8a90055b3cf689265cc30bdd9d1faf2c743c/server.jar"
        }
    },
    "id": "16w05b",
...

**Comment by RX14** [comment] 2016-02-06 16:04
Just to be clear, the old URLs and methods still work, which is great. 

It seems the new URLs are much faster, because of the hash in the URL, so I guess that's one positive. The URLs in the JSON are a good idea too, imho.

This error isn't because of the json URL move, bur rather a version increment in the snapshot json files.

**Comment by robbix1206** [comment] 2016-02-09 21:00
New launch tag"--versionType ${version_type}"  which is snapshot/release/old_beta/old_alpha
But that's all
All that we need is to rewrite the version parser and add this argument to pass to the game.

**Comment by Eisys** [comment] 2016-02-10 18:10
So... Is there a fix for this yet? I'd really like to play snapshots.

**Comment by peterix** [comment] 2016-02-10 18:12
There is a workaround. Edit instance, select Minecraft, Customize, Edit. Remove the the part that specifies minimum launcher version. Save, reload in MultiMC, play.

**Comment by Siris-Galatas** [comment] 2016-02-16 21:26
I'm also having this problem with the snapshots failing to download because Mojang moved the URL. I tried your "workaround" and the "Edit" button does nothing. I select the instance/Edit Instance/Minecraft/Customize/Edit  and it doesn't bring up a text file like it used to a while ago. It just stopped working for me a while ago. I didn't think to make a bug report because I never needed it till now. Also, I'm on a mac. OSX: 10.9.5

**Comment by jackpipe** [comment] 2016-02-20 00:53
The workaround doesn't work for me for version 1.7.10.
Clicking minecraft -> customize doesn't bring up the edit button.
In fact 1.7.9 downloads fine, as does 1.8.8, 1.8.9 etc.
Just a problem with 1.7.10.
This on xubuntu 15.04

**Comment by peterix** [comment] 2016-02-28 19:10
Fixed in develop, release will be available when the builds finish.

**Closed by peterix** 2016-02-28 19:10 UTC
Labels: bug, in progress

**Comment by unixfox** [comment] 2016-02-29 15:20
Same bug for 1.9

**Comment by peterix** [comment] 2016-02-29 15:21
No. Update.

**Comment by DyeffersonAz** [comment] 2018-11-03 19:00
Having the same problem with Forge.

```
MultiMC version: 0.6.2-1222


Minecraft folder is:
C:/Program Files (x86)/MultiMC/instances/1.12.2/.minecraft


Java path is:
C:/Program Files/Java/jdk1.8.0_181/bin/javaw.exe


Java is version 1.8.0_181, using 64-bit architecture.


Instance update failed because: Game update failed: it was impossible to fetch the required libraries.
Reason:
Job 'Libraries for instance 1.12.2' failed to process:
http://files.minecraftforge.net/maven/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar.pack.xz
http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.2-14.23.5.2768/forge-1.12.2-14.23.5.2768-universal.jar
http://files.minecraftforge.net/maven/org/jline/jline/3.5.1/jline-3.5.1.jar
http://files.minecraftforge.net/maven/org/ow2/asm/asm-all/5.2/asm-all-5.2.jar
http://files.minecraftforge.net/maven/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar.pack.xz
http://files.minecraftforge.net/maven/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar.pack.xz
http://files.minecraftforge.net/maven/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar.pack.xz
http://files.minecraftforge.net/maven/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar.pack.xz
http://files.minecraftforge.net/maven/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar.pack.xz.


```
