### ISSUE TITLE
Can't built MultiMC on ARM Mac

### ISSUE THREAD

**Issue by mlindner** [MultiMC/MultiMC5#3801] opened 2021-05-20 21:04 UTC
### Operating System

macOS

### Description of bug

When trying to build on ARM Mac I hit errors during the end of `make install`.

```
-- fixup_bundle: preparing...
-- fixup_bundle: copying...
-- 1/62: *NOT* copying '/Users/lindner/sources/MultiMC5/build/../dist/MultiMC.app/Contents/MacOS/iconengines/libqsvgicon.dylib'
-- 2/62: copying '/opt/homebrew/Cellar/qt@5/5.15.2/lib/QtCore.framework/Versions/5/QtCore'
-- 3/62: copying '/opt/homebrew/Cellar/qt@5/5.15.2/lib/QtGui.framework/Versions/5/QtGui'
-- 4/62: copying '/opt/homebrew/Cellar/qt@5/5.15.2/lib/QtSvg.framework/Versions/5/QtSvg'
-- 5/62: copying '/opt/homebrew/Cellar/qt@5/5.15.2/lib/QtWidgets.framework/Versions/5/QtWidgets'
-- 6/62: *NOT* copying '/Users/lindner/sources/MultiMC5/build/../dist/MultiMC.app/Contents/MacOS/imageformats/libqgif.dylib'
-- 7/62: *NOT* copying '/Users/lindner/sources/MultiMC5/build/../dist/MultiMC.app/Contents/MacOS/imageformats/libqicns.dylib'
-- 8/62: *NOT* copying '/Users/lindner/sources/MultiMC5/build/../dist/MultiMC.app/Contents/MacOS/imageformats/libqico.dylib'
-- 9/62: *NOT* copying '/Users/lindner/sources/MultiMC5/build/../dist/MultiMC.app/Contents/MacOS/imageformats/libqjpeg.dylib'
-- 10/62: *NOT* copying '/Users/lindner/sources/MultiMC5/build/../dist/MultiMC.app/Contents/MacOS/imageformats/libqmacheif.dylib'
-- 11/62: *NOT* copying '/Users/lindner/sources/MultiMC5/build/../dist/MultiMC.app/Contents/MacOS/imageformats/libqmacjp2.dylib'
-- 12/62: *NOT* copying '/Users/lindner/sources/MultiMC5/build/../dist/MultiMC.app/Contents/MacOS/imageformats/libqsvg.dylib'
-- 13/62: *NOT* copying '/Users/lindner/sources/MultiMC5/build/../dist/MultiMC.app/Contents/MacOS/imageformats/libqwbmp.dylib'
-- 14/62: *NOT* copying '/Users/lindner/sources/MultiMC5/build/../dist/MultiMC.app/Contents/MacOS/libMultiMC_gui.dylib'
-- 15/62: copying '/opt/homebrew/opt/qt@5/lib/QtConcurrent.framework/Versions/5/QtConcurrent'
-- 16/62: copying '/opt/homebrew/opt/qt@5/lib/QtNetwork.framework/Versions/5/QtNetwork'
-- 17/62: copying '/opt/homebrew/opt/qt@5/lib/QtXml.framework/Versions/5/QtXml'
-- 18/62: copying '/Users/lindner/sources/MultiMC5/dist/MultiMC.app/Contents/MacOS/libMultiMC_iconfix.dylib'
-- warning: resolved_item == resolved_embedded_item - not copying...
-- 19/62: copying '/Users/lindner/sources/MultiMC5/dist/MultiMC.app/Contents/MacOS/libMultiMC_logic.dylib'
-- warning: resolved_item == resolved_embedded_item - not copying...
-- 20/62: copying '/Users/lindner/sources/MultiMC5/dist/MultiMC.app/Contents/MacOS/libMultiMC_nbt++.dylib'
-- warning: resolved_item == resolved_embedded_item - not copying...
-- 21/62: copying '/Users/lindner/sources/MultiMC5/dist/MultiMC.app/Contents/MacOS/libMultiMC_quazip.dylib'
-- warning: resolved_item == resolved_embedded_item - not copying...
-- 22/62: *NOT* copying '/Users/lindner/sources/MultiMC5/build/../dist/MultiMC.app/Contents/MacOS/libMultiMC_rainbow.dylib'
-- 23/62: *NOT* copying '/Users/lindner/sources/MultiMC5/build/../dist/MultiMC.app/Contents/MacOS/platforms/libqcocoa.dylib'
-- 24/62: copying '/opt/homebrew/Cellar/qt@5/5.15.2/lib/QtDBus.framework/Versions/5/QtDBus'
-- 25/62: copying '/opt/homebrew/Cellar/qt@5/5.15.2/lib/QtPrintSupport.framework/Versions/5/QtPrintSupport'
-- 26/62: *NOT* copying '/Users/lindner/sources/MultiMC5/build/../dist/MultiMC.app/Contents/MacOS/platforms/libqwebgl.dylib'
-- 27/62: copying '/opt/homebrew/Cellar/qt@5/5.15.2/lib/QtQml.framework/Versions/5/QtQml'
-- 28/62: copying '/opt/homebrew/Cellar/qt@5/5.15.2/lib/QtQmlModels.framework/Versions/5/QtQmlModels'
-- 29/62: copying '/opt/homebrew/Cellar/qt@5/5.15.2/lib/QtQuick.framework/Versions/5/QtQuick'
-- 30/62: copying '/opt/homebrew/Cellar/qt@5/5.15.2/lib/QtWebSockets.framework/Versions/5/QtWebSockets'
-- 31/62: *NOT* copying '/Users/lindner/sources/MultiMC5/build/../dist/MultiMC.app/Contents/MacOS/MultiMC'
-- fixup_bundle: fixing...
-- 32/62: fixing up '/Users/lindner/sources/MultiMC5/build/../dist/MultiMC.app/Contents/MacOS/iconengines/libqsvgicon.dylib'
  exe_dotapp_dir/='../dist/MultiMC.app/'
  item_substring='/Users/lindner/sourc'
  resolved_embedded_item='/Users/lindner/sources/MultiMC5/build/../dist/MultiMC.app/Contents/MacOS/iconengines/libqsvgicon.dylib'

Install or copy the item into the bundle before calling fixup_bundle.
Or maybe there's a typo or incorrect path in one of the args to fixup_bundle?

CMake Error at /Users/lindner/sources/MultiMC5/cmake/BundleUtilities.cmake:568 (message):
  cannot fixup an item that is not in the bundle...
Call Stack (most recent call first):
  /Users/lindner/sources/MultiMC5/cmake/BundleUtilities.cmake:656 (fixup_bundle_item)
  application/install_prereqs.cmake:26 (fixup_bundle)
  application/cmake_install.cmake:67 (include)
  cmake_install.cmake:63 (include)
```

### Steps to reproduce

Build MultiMC on ARM Mac.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by jamierocks** [comment] 2021-05-20 21:45
I tried building myself to confirm this, and it does look as if this prevents the building of a macOS bundle for AArch64 systems at present.

Having said that, AArch64 isn't a build target of MultiMC at present - so I'm going to close this issue. Support will need to be introduced at such a time Mojang and subsequently MultiMC supports such systems natively.

**Closed by jamierocks** 2021-05-20 21:45 UTC
Labels: bug

**Comment by mlindner** [comment] 2021-05-20 21:46
This has nothing to do with Mojang. Please don't close this issue. It's a bug in MultiMC. It shouldn't depend on CPU architecture in the first place.

**Comment by Janrupf** [comment] 2021-05-20 21:49
Please don't unnecessarily open new issues. This is NOT a bug in MultiMC itself, but rather a flaw in the build system. Like your previous issue, this is not considered a bug. Please also restrain from calling out for hardcoded paths when you haven't put enough research into it.

If you think this requires further evaluation, you can come talk to use on our [Discord](https://discord.gg/multimc)

**Comment by mlindner** [comment] 2021-05-20 21:54
1. I didn't "call out for hardcoded paths". I said they shouldn't be hardcoded.
2. I didn't "unnecessarily open new issues". I looked for existing issues but didn't find any.
3. Discord isn't a method for communicating technical issues. That's best done on github or via email or something similar.
4. I fail to see how "a flaw in the build system" is not "a bug in MultiMC". If there's a build error then it's a flaw in MultiMC or its dependencies. If it's not a flaw in MultiMC, then please mention what it is a flaw in so I can go file a bug on their bug tracker.

**Comment by Janrupf** [comment] 2021-05-20 21:57
I can only repeat what James and I said already - if you want to further discuss this, come talk to us on discord, thats where we talk about how to tackle such things. 

And repeating what James said: MultiMC does not officially support ARM, so you are on your own, that also goes for the build system. We will happily help out and discuss this on Discord.
