### ISSUE TITLE
Abort button don't work when downloading 

### ISSUE THREAD

**Issue by mrcorpz** [MultiMC/MultiMC5#3704] opened 2021-03-30 09:21 UTC
### Operating System

Windows

### Description of bug

Abort button don't work when downloading 

### Steps to reproduce

Download a modpack and then press abort

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by kb-1000** [comment] 2021-03-30 09:24
Duplicate of #1949.

**Closed by kb-1000** 2021-03-30 09:24 UTC
Labels: bug

**Comment by mrcorpz** [comment] 2021-04-03 05:28
THIS HAVE BEEN ON A LOOOOONG TIME AND YOUGYS HAVEN'T FREAKING FIXED COME ON
