### ISSUE TITLE
Feature Request: Archived Minecraft Versions

### ISSUE THREAD

**Issue by Omega-Richi** [MultiMC/MultiMC5#3746] opened 2021-04-28 23:05 UTC
Not all versions of Minecraft, that have been publicly released at one point, are available through the Mojang servers. 
Some however have been externally archived and are available through the official Minecraft wiki (https://minecraft.fandom.com/wiki/Java_Edition_version_history), where you can download the client .jar and the .json file for the official launcher.

Since MultiMC has been adding support for directly downloading from various modpack launchers, I would like to request the ability to select from these archived versions during instance creation, as it would simplify installing them.

**Comment by jotoho** [comment] 2021-04-29 03:33
Duplicate of #3472

**Comment by kb-1000** [comment] 2021-04-29 06:00
Duplicate of #3472

**Closed by kb-1000** 2021-04-29 06:00 UTC
