### ISSUE TITLE
BMCLAPI

### ISSUE THREAD

**Issue by haotian2004** [MultiMC/MultiMC5#3258] opened 2020-07-26 02:16 UTC
System Information
-----------------------------
MultiMC version:
0.6.12-develop-1459

Operating System:
Windows10 

Summary of the issue or suggestion:
Downloading in mainland China is a problem. 
There is a source called BMCLAPI in China.
https://bmclapidoc.bangbang93.com/
This is a Chinese page，
You can go to find out,
This speeds up the download.
----------------------------------------------

What should happen:
Can you add a (custom) download source option,

------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.

2.

3.

Suspected cause:
Download package is too slow
---------------------------

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by phit** [comment] 2021-03-09 20:50
Duplicate of https://github.com/MultiMC/MultiMC5/issues/3164

**Closed by phit** 2021-03-09 20:50 UTC
