### ISSUE TITLE
Instance twice launched after Update

### ISSUE THREAD

**Issue by Zocker1999NET** [MultiMC/MultiMC5#1874] opened 2017-04-30 17:02 UTC
System Information
-----------------------------
MultiMC version: 0.5.0-develop-973

Operating System: Windows 10 Pro - Build 16184.1001

Summary of the issue:
----------------------------------------------
When starting MultiMC with the launch command `-l [instance]`, it searches also for updates and asks to install these when MultiMC found a newer version. After pressing Okay, MultiMC updates and starts itself again with the same launch command. After a few seconds, two MultiMC instances seem to run. Also two windows of the same game instance appear at the same time.

What should happen:
------------------------------
The old version of MultiMC should be closed and the game should only be started if the user has canceled the update or the update has finished.

Steps to reproduce the issue:
-------------------------------------------------------------
(Does only work if an update is available)

1. Open a command line or create a link to MultiMC with the following line:
`MultiMC.exe -l myInstance`
2. Start MultiMC
3. MultiMC asks for an update to install, accept the installation.
MultiMC installs the update and starts itself with the same parameters.
After a few seconds, you see in the taskbar that two windows of MultiMC are opened. And even a few moments later, two instances of Minecraft appear.

Suspected cause:
---------------------------
The game is started before the update window appears.

**Comment by flcmc** [comment] 2017-05-01 02:59
I cannot reproduce this, a second MultiMC process is opened with the new version and the old MultiMC process is still open, but it doesn't open the instance again on the new one. 

Still a problem however.

**Comment by peterix** [comment] 2017-05-01 11:36
1. It shouldn't be launching the instance the second time.
2. The update shouldn't be able to trigger with instances running.

**Comment by peterix** [comment] 2017-05-01 11:42
The changes in #1873 make it impossible to trigger updates while using `-l $ID` alone, because no main window is created anymore.

You can still have one open additionally afterwards. You can also have an existing one.

I'm adding a filter to the updater that will make it not launch the new process with `-l $ID`.
You can still trigger an update while an instance is running... so I will block that.
I will also block starting instances while an update is running.

That should fix all of {#1873, #1874, #1875}

**Comment by M1CR0H4CK3R** [comment] 2017-05-01 16:53
The newest commit makes MultiMC crash upon loading my instance. The instance in question is 1.12.2 with Forge 13.20.0.2228 and 3 mods: Inventory Tweaks 1.62 beta, JourneyMap 5.4.6, and One Click Crafting 1.2.2.

**Comment by peterix** [comment] 2017-05-02 21:38
MultiMC will now exit after an instance is closed, as long as there are no windows left behind.
It will not create a main window, unless you actually launch it normally.
Direct launch of instance does not - by default - not create an instance window. This has to be enabled in the settings, or the instance has to crash.

I consider this a good enough solution until MultiMC can track running instances even through its own restart.

Closing {#1873, #1874, #1875}

**Closed by peterix** 2017-05-02 21:38 UTC
Labels: bug
