### ISSUE TITLE
this is more of a suggestion for the "-L" in the command line

### ISSUE THREAD

**Issue by crusher42** [MultiMC/MultiMC5#3240] opened 2020-07-10 05:18 UTC
i been useing the command line to load the game fast
but sometimes i have left it set to the other account 
maybe if there is a way to have (MultiMC.exe -l "instance name" -a "account name")

**Comment by naqaden** [comment] 2020-08-08 16:53
+1, and this is a duplicate of #3116

**Comment by Scotsguy** [comment] 2021-03-08 14:21
Duplicate of #3411

**Closed by Scotsguy** 2021-03-08 14:21 UTC
