### ISSUE TITLE
mod downloading progress stuck at near finish

### ISSUE THREAD

**Issue by HalcyonSuoh** [MultiMC/MultiMC5#2992] opened 2020-02-05 19:33 UTC
System Information
-----------------------------
MultiMC version: 0.6.7-1375 on win32

Operating System: Windows 10

Summary of the issue or suggestion:
----------------------------------------------
Download progress stuck at near finish during importing Roguelike "Adventures and Dungeons" modpack.Abort and X button won't work either

What should happen:
------------------------------
download progress should complete

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.Download "update-RAD-1.35.zip" at curseforge

2.import it in MutiMC

3.wait

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------
https://paste.ee/p/uu5pb

Additional Info:
---------------------------

**Comment by peterix** [comment] 2020-08-09 20:09
Sounds like something that could be improved by detecting stuck downloads.

**Comment by Colonizor48** [comment] 2020-10-10 20:38
im having this issue too. Pls fix it

**Comment by phit** [comment] 2021-03-11 14:25
Duplicate of https://github.com/MultiMC/MultiMC5/issues/2868

**Closed by phit** 2021-03-11 14:25 UTC
Labels: bug
