### ISSUE TITLE
Bug with the groups

### ISSUE THREAD

**Issue by Flo59Flocon** [MultiMC/MultiMC5#1208] opened 2015-08-24 19:23 UTC
![ok](https://cloud.githubusercontent.com/assets/13950504/9449970/40def3b0-4aa6-11e5-8e33-eb9e224a60bb.jpg)
![pas ok](https://cloud.githubusercontent.com/assets/13950504/9449972/43c65ff0-4aa6-11e5-9267-3a8f0dc45fbc.jpg)

Hello.

I encounter a bug that resets the half of my group every time I raise the software.
(The 1st image is the good groups and the 2nd is the not good groups)

Thank you in advance for fix this bug.

Excuse me if my english is Approximate , I used Google Translate

**Comment by Flo59Flocon** [comment] 2015-08-24 19:24
The 2nd image was pict after a restart of the application

**Comment by peterix** [comment] 2015-08-25 07:43
Ok... 
If you test this with the develop builds, is it still happening?

Make sure you have backups of the whole thing before you switch to develop/update.

**Comment by peterix** [comment] 2015-10-19 23:58
This should be fixed and was caused by unicode characters in group names.

**Closed by peterix** 2015-10-19 23:58 UTC
Labels: bug
