### ISSUE TITLE
Win-7, Newest Dev Update (0.6.0-dev-1134) missing "MSVCR120.dll"

### ISSUE THREAD

**Issue by TriforceMayhem** [MultiMC/MultiMC5#2062] opened 2017-12-08 02:26 UTC
System Information
-----------------------------
MultiMC version: 0.6.0-develop-1134

Operating System: Windows 7 64-bit

Summary of the issue or suggestion: 
----------------------------------------------
After updating, I get an error that says the program cannot boot because MSVCR120.dll is missing from my computer. MMC still launches, but the launcher is completely offline, I cannot retrieve versions (ex. when making a new instance), and it prompts me to set a name for offline mode, though I can still play Minecraft Multiplayer.

What should happen: 
------------------------------
The program launches without any error and the launcher can retrieve online data.

Steps to reproduce the issue:
-------------------------------------------------------------
1. Download the latest MMC & set it up

2. Set Update Channel to Development

3. Update MMC

4. Launch MMC and get the error

Suspected cause:
---------------------------
Either some data was lost in the update, or I don't have the correct Microsoft Visual C++ Redistributable

**Comment by peterix** [comment] 2017-12-08 08:25
Duplicate of https://github.com/MultiMC/MultiMC5/issues/2060 -- look there for more info.

**Closed by peterix** 2017-12-08 08:25 UTC
Labels: duplicate
