### ISSUE TITLE
Cannot remove LiteLoader from instance

### ISSUE THREAD

**Issue by khionu** [MultiMC/MultiMC5#1809] opened 2017-02-01 22:08 UTC
System Information
-----------------------------
MultiMC version: 0a6af3cff3adf6df641b1ed99aaeac0f4ea4e252

Operating System: Mint 18.1 MATE

Summary of the issue or suggestion: Cannot remove LiteLoader from Instance
----------------------------------------------

What should happen:
------------------------------

Button to remove LiteLoader from instance should be functional

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Install LiteLoader to instance

2. Try to remove

**Comment by peterix** [comment] 2017-02-01 22:20
I cannot reproduce this issue. Please add more detail about you specific situation.

**Comment by khionu** [comment] 2017-02-01 23:22
...... actually, I'm just blind.

I would like to change this into a recommendation to move the Remove button to be with the Customize and Revert button. I assumed the Revert button was the Remove.

**Comment by peterix** [comment] 2017-02-01 23:58
Maybe the distinction between the Edit and Selection sections is not clear.

But in general, Selection is more destructive than Edit.  If you change the version of Minecraft (currently only Minecraft), it can mean that all custom patches are removed. If you move patches around, their meaning changes significantly. If you Remove something, it is gone.

Customizing means the version that is managed by a version list is copied into the instance without it being affected in any way. It is now static. Edit affects the custom version - but only if you actually change the file, it can also be interpreted as View. Revert throws away the custom changes and reverts to using the upstream version.

I'm honestly not sure what the right approach to this is, because the things it works with are fairly complex. Seriously, imagine picking a random person from the street and explaining this to them. Could you? If you can't, you don't understand it fully.

I removed a lot of hidden complexity from the version file format over the last few stable versions. I bet absolutely nobody understood it. Maybe @02JanDal did because he wrote it. And me, because I had to understand enough of it to remove unused features from it.

So, I don't know if moving a mysterious button to an equally mysterious position helps.

**Comment by peterix** [comment] 2018-02-14 15:50
Hmm... still don't know how to make this better, but now the versions do not start out as custom, so this is possibly different?

Anyway, closing.

**Closed by peterix** 2018-02-14 15:50 UTC
Labels: support
