### ISSUE TITLE
My MultiMC is broken

### ISSUE THREAD

**Issue by KostasX98** [MultiMC/MultiMC5#1841] opened 2017-03-18 00:33 UTC
I Downloaded MultiMC and it crashes when i try to play.
I reinstalled it 2 times but its still crashes i dont know if thats because im from Windows 10.

**Comment by peterix** [comment] 2017-03-18 00:41
You cannot install it, because it has no installer. Are you sure you got the right thing?

What do you mean by `crashes`?

**Comment by KostasX98** [comment] 2017-03-18 02:17
Im trying to Launch minecraft 1.11.2 from MultiMC and shows me the Minecraft Log

**Comment by KostasX98** [comment] 2017-03-18 02:39
Im trying to Launch minecraft 1.11.2 from MultiMC and shows me the Minecraft Log

**Comment by peterix** [comment] 2017-03-18 07:33
I'm sorry, but that's like saying that your car doesn't start.

Click that Upload button and give me the link to the uploaded log.

**Comment by KostasX98** [comment] 2017-03-18 13:56
https://paste.ee/p/LYct2

**Comment by QuImUfu** [comment] 2017-03-18 14:22
Likely another duplicate of #1276. Intels drivers for old iGPU's do not Work with newer Java versions. Worked around by using an java version older than 8u60 for MultiMC.

**Comment by peterix** [comment] 2017-03-18 14:34
Indeed, the best course of action is to use this java: https://files.multimc.org/downloads/jre-8u51-windows-x64.zip

Extract it somewhere in MultiMC's folder and set the `javaw.exe` as the Java to use in MultiMC.

**Comment by KostasX98** [comment] 2017-03-19 04:04
Thanks for the help, its finnaly working!
But how i can install 5zig and Optifine with MultiMC ?

**Comment by tehbasshunter** [comment] 2017-03-19 04:13
If you have forge installed you can copy the jar into your mods folder for the instance.

**Comment by GmanAtheist** [comment] 2017-03-22 22:20
WOW!. Great support . Thanks . This will help a lot of people. :-)

**Closed** 2018-02-14 15:40 UTC
Labels: support
