### ISSUE TITLE
Dragging and dropping a modpack zip into MultiMC from explorer resulted in explorer hanging for some time

### ISSUE THREAD

**Issue by anpilley** [MultiMC/MultiMC5#2252] opened 2018-04-22 03:29 UTC
System Information
-----------------------------
MultiMC version: 0.6.2-develop-1221

Operating System: Win10 16299.371

Summary of the issue or suggestion:
----------------------------------------------
MultiMC supports dragging and dropping zipped up modpacks into its window to start the Add Instance process. Doing this from an explorer window hangs the explorer window until the import is complete, at which point, the explorer window becomes responsive again.

What should happen:
------------------------------
Explorer should remain responsive to user input.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Download a larger modpack from curseforge.com (I was using Sevtech).

2. Locate the modpack zip file in explorer.

3. Drag the modpack into the MultiMC window.

4. Attempt to interact with the originating explorer window.

Suspected cause:
---------------------------
Likely, the code stemming from 
https://github.com/MultiMC/MultiMC5/blob/604295e6d504f6e41ec2f91500479edbf2838a2d/api/logic/minecraft/ModList.cpp#L128
needs to be modified to queue up an import action, and then return to the drag/drop caller as quickly as possible, to release the drag&drop operation on Explorer's side.

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by peterix** [comment] 2018-04-22 16:12
Makes sense.

**Comment by peterix** [comment] 2018-04-23 07:04
Fixed in develop (AFAIK)

**Closed by peterix** 2018-04-23 07:04 UTC
Labels: multimc: bug

**Comment by anpilley** [comment] 2018-04-23 15:49
Yep, picked up the new build this morning, no more problems with explorer being unresponsive. Nice.

**Comment by peterix** [comment] 2018-04-23 15:51
Glad to hear it. This was way worse with drag&drop of URLs from the browser :)

**Comment by brodycas3** [comment] 2018-04-23 15:56
Does this also fix the issue with chrome?

**Comment by peterix** [comment] 2018-04-23 15:57
I believe so. I tested it on Windows 7 and the problem was gone.

**Comment by brodycas3** [comment] 2018-04-23 15:59
I can confirm fixed, I believe there may still be open issues related to this.

**Comment by swoolcock** [comment] 2018-04-25 00:57
Note that Finder in macOS has the same freezing issue, but this change does not fix it.

**Comment by swoolcock** [comment] 2018-04-27 01:06
Yes, using the latest develop build.

**Comment by anpilley** [comment] 2018-04-27 01:25
Yep. Can confirm it’s fixed on windows but not on my MacBook.
