### ISSUE TITLE
Could not load Forge 1.17.1

### ISSUE THREAD

**Issue by Ben-5K** [MultiMC/MultiMC5#3960] opened 2021-07-23 13:56 UTC
### Operating System

Windows

### Description of bug

Forge 1.17.1 is released, but in MultiMC it dispays, there is no version for 1.17.1 now.

### Steps to reproduce

open multimc - create instance for 1.17.1 and try to install or download forge

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by heftymouse** [comment] 2021-07-23 13:58
This is intentional.
> New Forge versions are currently broken/unusable and will not show up in MultiMC until further notice (36.1.66 and above for 1.16.5, 37 and above for 1.17.1).

**Comment by phit** [comment] 2021-07-23 14:01
Duplicate of https://github.com/MultiMC/MultiMC5/issues/3953

**Closed by phit** 2021-07-23 14:01 UTC
Labels: bug

**Comment by peterix** [comment] 2021-07-25 17:34
There is no working version of Forge for 1.17.1 - the information is correct.
