### ISSUE TITLE
Can it choose java8 or java16 automatically

### ISSUE THREAD

**Issue by UncleMax** [MultiMC/MultiMC5#3889] opened 2021-06-21 15:50 UTC
### Role

Switch the Java version manually every time

### Suggestion

Automatically select the corresponding java version according to the game version

### Benefit

Because this is a very practical function, I hope MultiMC is better

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by RDKRACZ** [comment] 2021-06-21 16:05
What are you talking about? You can set the Java version separately for every instance.

**Comment by Zetabite** [comment] 2021-06-21 16:09
Thats not what they are talkin about. They want mmc to automaticly choose the java version needed. With better java detection implemented and soon use of Mojangs shipped java, that might be a thing to do.

**Comment by RDKRACZ** [comment] 2021-06-21 16:23
>Thats not what they are talkin about

That's what I thought but "Switch the Java version manually every time". Why every time if it's just a one-time thing? Regardless, auto-switch the Java version to 16 for MC 1.17+ versions still sounds nice.

**Comment by phit** [comment] 2021-06-21 17:20
Duplicate of https://github.com/MultiMC/MultiMC5/issues/3832

**Closed by phit** 2021-06-21 17:20 UTC

**Comment by phit** [comment] 2021-06-21 17:21
It will happen soon (tm), don't need multiple versions about basically the same thing. MultiMC will automatically download the needed Java like the Vanilla launcher.
