### ISSUE TITLE
Liteloader Incompatibilities.

### ISSUE THREAD

**Issue by TruBlaze** [MultiMC/MultiMC5#1569] opened 2016-05-14 17:51 UTC
System Information
-----------------------------
MultiMC version: 0.4.11-703

Operating System: Ubuntu Xenial (64-bit)

Summary of the issue or suggestion: The launcher does not pick up Liteloader snapshot versions (1.8-1.9)
----------------------------------------------

What should happen: (1.7.10) Display Liteloader versions
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Open MultiMC

2. Create a 1.8, 1.8.8, or 1.9 instance

3. In Instance Settings/Version, click Install Liteloader

Suspected cause: Incompatibility with Snapshot releases
---------------------------

Logs/Screenshots: http://i.imgur.com/wUDPAWC.png
----------------------------

Additional Info: none
---------------------------

**Comment by 02JanDal** [comment] 2016-05-14 17:54
Duplicate of #676

**Closed by 02JanDal** 2016-05-14 17:54 UTC
