### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by untamemadman** [MultiMC/MultiMC5#1176] opened 2015-08-10 00:18 UTC
I notest that you can upload screenshots to imgur.com via the MultiCM launcher so I waw wondering if maybe their could be a way to login to imgur to keep all your screenshots linked to your account.

If this is already a feature then please let me know how I do this.

Kind Regards
untamemadman

**Comment by 02JanDal** [comment] 2015-08-10 06:02
Duplicate of #1089

**Closed by 02JanDal** 2015-08-10 06:02 UTC
