### ISSUE TITLE
PermGen not supported in Java8+

### ISSUE THREAD

**Issue by isavegas** [MultiMC/MultiMC5#811] opened 2015-03-12 05:29 UTC
I am aware of the fact that Java 9 hasn't been released, but I have compiled the OpenJDK implementation of Java 9 from source, and have been made painfully aware of the fact that MultiMC has no built-in way to disable the PermGen flag, as Java 9 refuses to start when it is passed. Java 8 has no support for PermGen, either, but it simply throws a warning when you pass a PermGen value to the JVM. I was hoping that you might add a simple check against the selected executable's version to determine if MultiMC should specify a PermGen size, or a small checkbox in the Java settings tab to disable it.

**Comment by 02JanDal** [comment] 2015-03-12 06:20
Duplicate of #690, feel free to continue discussing there. In short: set the permgen to the default (64? 128? not entirely sure) and the flag won't be given to java.

**Closed by 02JanDal** 2015-03-12 06:20 UTC
