### ISSUE TITLE
Minecraft prereleases not showing up

### ISSUE THREAD

**Issue by africalinguist** [MultiMC/MultiMC5#2615] opened 2019-04-20 01:10 UTC
System Information
-----------------------------
MultiMC version: 0.6.5-develop-1223

Operating System: Ubuntu 18.04.2 LTS

Summary of the issue or suggestion:
----------------------------------------------
Minecraft prerelease 3, 4 and 5 are not showing up in the version list, despite being released by mojang and getting a blog post on minecraft.net.

What should happen:
------------------------------
These versions should show up.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Go to create a new instance.

2. check "snapshots".

3. look at the list.

Suspected cause:
---------------------------
unknown, maybe something with the metadata?

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
![multimc new instance screen](https://user-images.githubusercontent.com/26539285/56449466-96794780-6343-11e9-8685-5b357ea142e1.png)

Additional Info:
---------------------------

**Comment by tehbasshunter** [comment] 2019-04-20 01:15
There's an issue with how the snapshots are downloaded. Follow this [here](https://youtu.be/IalXe75BscE) to install PR 3 OR 4.

**Comment by Jakesta13** [comment] 2019-04-20 02:00
> There's an issue with how the snapshots are downloaded. Follow this here to install PR 3 OR 4.
I find this strange since I auto-download latest server versions from Mojang's version_manifest.json file and nothing has changed from 1.14-pre2.
Not sure if this is the same way that MultiMC does it, if not then that could be the reason.

**Comment by shedaniel** [comment] 2019-04-20 18:37
Mojang included two lwjgl versions starting from pre3 and that broke MultiMC

**Comment by peterix** [comment] 2019-04-21 00:16
Duplicate of #2608.

**Closed by peterix** 2019-04-21 00:16 UTC
