### ISSUE TITLE
1.7.10 Modpack doesnt load. "Updating assets index"

### ISSUE THREAD

**Issue by playa2k** [MultiMC/MultiMC5#1830] opened 2017-02-28 20:14 UTC
System Information
-----------------------------
MultiMC version: 0.5.0-945

Operating System: Win10, 64 Bit, JRE1.8.0_121

Summary of the issue or suggestion:
----------------------------------------------
Updating assets index drops an error. 1.7.10 Modpack. 1.10.2 works fine

What should happen:
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
-

Suspected cause:
---------------------------
Something is broken with the 1.7.10.json file, or the server isnt responding. Deleting doesnt help. Maybe a problem with s3.amazonaws.com? If so, why doesnt the launcher just launch the game with the existing file, which worked before?

Logs/Screenshots:
----------------------------
https://paste.ee/p/3Gxu1

Additional Info:
---------------------------

**Comment by peterix** [comment] 2017-02-28 20:18
Duplicate of #1828

**Closed by peterix** 2017-02-28 20:18 UTC
