### ISSUE TITLE
Make instances/profiles with common folders (how-to suggestion?)

### ISSUE THREAD

**Issue by Felina-Lain** [MultiMC/MultiMC5#2189] opened 2018-03-18 19:31 UTC
Hello,
I'm aware that this has been asked many times before, and from what I gathered the answer was always "it's very tricky to do so we probably won't"
I don't have much knowledge on the matter, but I still tried to think up of suggestions on how that might work, based on (what I hope was) logic:

Folders and sub-folders system.
Would it work having a core folder that contains saves, screenshots, resource packs, even mods.
Then MultiMC would seek out inside those folders, a subfolder associated with the profile?

Kinda like forge does, we can create a sub-folder in the mods folder with the MC version as name and forge will only load those (but better because forge doesn't do it to full extent, and it would be better if we could do it with profiles names)

Like, I create a profile named "Modpack X" so MultiMC would use everything in the core folders for it (so anything directly in the "mods" folder for exemple) and everything that would be in any sub-folder named "Modpack X"
Then I have another profile name "Modpack Z", with subfolders "Modpack Z" it won't load "Modpack X" things, because of the sub-folders?

I dunno if I make sense, I hope I do.

Else I'm wondering if it would be possible to do as Magic Launcher did. It's deprecated now but at the time, it used one unique instance of MC and would load things depending on the profile, but checking mods on and off (but I have no clue how it did that in practice)

Thanks for taking the time to read this, sorry if what I suggested is not possible and I wasted your time.

**Comment by peterix** [comment] 2018-03-18 19:36
It's not a problem with MultiMC, it's a problem with the game. It just doesn't allow this. And even if it was introduced in a new version of the game, it wouldn't work in any of the previous ones.

So you would have to use workarounds like symlinks, or copy things around behind the scenes all the time, or some sort of overlay filesystem. None of that is reliable enough, and often even available. And it has limitations.

**Comment by peterix** [comment] 2018-03-18 19:37
Duplicate of #42

**Closed by peterix** 2018-03-18 19:37 UTC
Labels: multimc: feature

**Comment by Felina-Lain** [comment] 2018-03-18 19:53
It's a problem that was introduced with recent (more o less recent) updates then I suppose? Which could be the reason why Magic Launcher became obsolete I would guess...

Well sorry for the waste of time once more, and thanks for answering anyway...

**Comment by peterix** [comment] 2018-03-18 19:56
No, whatever magic launcher did didn't apply to resources, worlds, or any other normal files in general.
All it did was put mods on the classpath, which kinda worked, except when it didn't.
