### ISSUE TITLE
It is possible to launch MC/FORGE server or BukkitGUI from MultiMC?

### ISSUE THREAD

**Issue by hitman60** [MultiMC/MultiMC5#2354] opened 2018-07-27 12:35 UTC
This is more feature request rather then issue. Since I love MultiMC, but I prefer to run my singleplayer worlds on dedicated server from different physical HDD, with different java arguments.

**Comment by S10MC2015** [comment] 2018-07-27 20:46
This would be such a good future but it will take a very long time to implement

**Comment by peterix** [comment] 2018-11-01 01:04
No, and this is a duplicate of #60.

**Closed by peterix** 2018-11-01 01:04 UTC
Labels: support: multimc
