### ISSUE TITLE
Unable to add any instances from zip files

### ISSUE THREAD

**Issue by Renegadefade** [MultiMC/MultiMC5#2284] opened 2018-05-23 15:42 UTC
System Information
-----------------------------
MultiMC version: 0.6.2-1222

Operating System: Win10

Summary of the issue or suggestion:
----------------------------------------------
I attempted to update a couple of mod packs I've been playing. Whenever trying to add an instance from a zip file I get an error "Unable to resolve mod IDs: Some mod ID resolving tasks failed"

I've downloaded a couple other packs to test and got the same result. Although, when importing through the FTB Legacy tab it adds adds an instance without any errors.

What should happen:
------------------------------
A new instance created.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Click Add Instance

2. Import from zip

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

**Comment by peterix** [comment] 2018-05-23 16:55
Duplicate of #2283

**Closed by peterix** 2018-05-23 16:55 UTC
Labels: duplicate

**Comment by darthvader45** [comment] 2019-10-20 02:04
Weird, suddenly reappears in 0.6.7-1375.  Not sure why though.

**Comment by Heufneutje** [comment] 2019-10-21 06:52
Create a new issue for it with the proper template.
