### ISSUE TITLE
Icon Size on Mac

### ISSUE THREAD

**Issue by CaptainMaximus5** [MultiMC/MultiMC5#4098] opened 2021-09-13 20:43 UTC
### Role

I think that after the Big Sur Update to Mac that all of the icons should be the same size and it is a simple fix.

### Suggestion

I want them to make the icon slightly smaller to match with all of the new big sur icons.

### Benefit

So that all of the icons will match

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by phit** [comment] 2021-09-13 20:44
Duplicate of https://github.com/MultiMC/MultiMC5/issues/3507

**Closed by phit** 2021-09-13 20:44 UTC
