### ISSUE TITLE
LWGJL list load error on launch of imported FTB Retro SSP pack

### ISSUE THREAD

**Issue by TomeWyrm** [MultiMC/MultiMC5#1670] opened 2016-09-25 03:40 UTC
---
## System Information

MultiMC version: MultiMC 5 - Version 0.4.11-751 on win32

Operating System: Windows 7 (Microsoft Windows v6.1 b7601 (Service Pack 1))

Summary of the issue or suggestion:
I'm getting an "Instance update failed because: Too soon! Let the LWJGL list load :)." message whenever I try to launch a 1.2.5 forge mod pack. Specifically: I tried to import the FTB Retro pack into MultiMC via the FTB Launcher integration. It detects fine, but when I launch, I get the above error

---
## What should happen:

Pack should launch.

---
## Steps to reproduce the issue (Add more if needed):
1. Use Legacy FTB Launcher to download "Feed The Beast Retro SSP (v3) Minecraft Version 1.2.5" pack, wait for pack to get to main menu using that launcher. Exit the pack.
2. Boot up MultiMC (or reboot), pack may not show up instantly. I ended up rebooting MultiMC once or twice then waited some time (I was watching a youtube video on my phone to pass the time) and then refreshed the instance list with F5.
3. Boot the "Feed The Beast Retro SSP" pack in MultiMC. Error will occur immediately.

---
## Suspected cause:

Apparently a LWJGL version error based on another issue in this tracker.

---
## Logs/Screenshots:

http://paste.ee/p/tbLUK

---
## Additional Info:

It's in the logs, but I'm using Java 1.8.0.101-b13 (64 bit server). I can easily provide more info if required, though there might be a delay, as I work full-time :-)

**Comment by QuImUfu** [comment] 2016-09-27 21:21
Can reproduce on my machine (also happens with a copied instance of the FTB-Instance).
Linux Lubuntu 64bit.
I think it might be a MMC bug with legacy (FTB?) instances. It is most likely caused by a change in the rss file, causing this error: 
C "Failed to load LWJGL list. XML error: error occurred while parsing element at line 2" 
logged somewhere in the mmc log file.

Sadly i can't get the modpack to work as "native" MMC Instance, too. (Crashes at some point, Forestry or EE causes the crash. O.o )

**Comment by peterix** [comment] 2016-11-27 00:46
Should be fixed as soon as the build finishes.

**Closed** 2016-11-27 01:17 UTC
Labels: bug
