### ISSUE TITLE
qt5-default not supported anymore

### ISSUE THREAD

**Issue by krakel** [MultiMC/MultiMC5#3435] opened 2020-11-12 08:14 UTC
System Information
-----------------------------
MultiMC version:
multimc_1.4-1.deb

Operating System:
Linux - Debian - Testing

Summary of the issue or suggestion:
----------------------------------------------
qt5-default was removed from the package list

multimc should use direct qt5 dependencies
from the debian package description:
"This package should not be used for building Debian packages."

**Comment by phit** [comment] 2020-11-12 08:57
Please use [the search](https://github.com/MultiMC/MultiMC5/issues?q=is%3Aissue+is%3Aopen+qt5-default) before opening a new issue, duplicate of #3413

**Closed** 2020-11-24 20:41 UTC
Labels: close:duplicate
