### ISSUE TITLE
[Enhancement] Add CLI option to launch directly into a specified instance

### ISSUE THREAD

**Issue by Gotolei** [MultiMC/MultiMC5#1132] opened 2015-07-16 09:07 UTC
./MultiMC --instance 'Infinity 181'
    ./MultiMC -I 'RR3 Mainline'
Or perhaps, to get around problems with escaping, have something under Instance Settings where the user sets a simple ID number/string.

This would allow for users to create desktop icons/launchers, skipping the main window and speeding up the startup process a bit.

**Comment by RX14** [comment] 2015-07-16 09:12
Ohh :+1:

This allows custom launchers to simply make a MultiMC profile then use MultiMC launching code. I've wanted this on the vanilla Launcher forever

**Comment by 02JanDal** [comment] 2015-07-16 09:13
Duplicate of #253.

**Closed by 02JanDal** 2015-07-16 09:13 UTC

**Comment by Gotolei** [comment] 2015-07-16 09:15
Bleh, searched for both 'packs' and 'instances' and found nothing relevant.

Guess 'profile' was the key word to use :p
