### ISSUE TITLE
Persist last-used offline mode username between sessions

### ISSUE THREAD

**Issue by business-goose** [MultiMC/MultiMC5#3651] opened 2021-03-09 17:48 UTC
System Information
-----------------------------
MultiMC version:
0.6.11-1430
Operating System:
Windows 10 x64

Summary of the issue or suggestion:
----------------------------------------------
Save the last-used offline username in a file and when a user requests to launch any instance, it will default to the cached username instead of the premium username.

**Comment by phit** [comment] 2021-03-09 21:31
Duplicate of https://github.com/MultiMC/MultiMC5/issues/3335

**Closed by phit** 2021-03-09 21:31 UTC
Labels: suggestion
