### ISSUE TITLE
Pack update option

### ISSUE THREAD

**Issue by Goten87** [MultiMC/MultiMC5#3652] opened 2021-03-11 10:42 UTC
When you download a modpack from FTB or other
when they update the pack you need to redownload it in new profile and then move stuff on your own

is there any change you peeps can make a update pack function or change version for modpacks

**Comment by phit** [comment] 2021-03-11 11:11
Duplicate of https://github.com/MultiMC/MultiMC5/issues/2640
and countless others, probably not gonna happen any time soon, please follow the issue template next time

**Closed by phit** 2021-03-11 11:11 UTC
Labels: close:duplicate
