### ISSUE TITLE
Option to download mods from CurseForge

### ISSUE THREAD

**Issue by dodik666** [MultiMC/MultiMC5#3709] opened 2021-04-03 12:00 UTC
### Role

I play modded and vanilla Minecraft

### Suggestion

Option to search and download mods from CurseForge

### Benefit

It will allow to easily download mods without need to open browser

### This suggestion is unique

I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by phit** [comment] 2021-04-03 12:09
Duplicate of https://github.com/MultiMC/MultiMC5/issues/3422
Duplicate of https://github.com/MultiMC/MultiMC5/issues/3696
and so many other

**Closed by phit** 2021-04-03 12:09 UTC
