### ISSUE TITLE
1.16.5 Forge failed on start

### ISSUE THREAD

**Issue by Ekmot276** [MultiMC/MultiMC5#3772] opened 2021-05-08 17:31 UTC
### Operating System

Windows

### Description of bug

Minecraft fails to load with forge installed using MultiMC

Error log:
https://pastebin.com/06fM4LFv

(Note: The game starts perfectly without forge installed.)

### Steps to reproduce

Create a new instance of Minecraft 1.16.5 and install Forge using "Edit Instance" > "Version" > "Install Forge"

### Suspected cause

Im not sure if this might have anything to do with my installed version of java, just in case this might help:

C:\Users\Ekmot276>java -version
java version "11.0.11" 2021-04-20 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.11+9-LTS-194)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.11+9-LTS-194, mixed mode)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by kb-1000** [comment] 2021-05-08 17:50
Can reproduce this. The reason for this is that https://maven.minecraftforge.net/org/ow2/asm/asm/6.1.1/asm-6.1.1.jar is gone.

**Comment by phit** [comment] 2021-05-10 07:25
@Ekmot276 @kb-1000 looks like this is fixed now?

**Closed** 2021-05-15 21:16 UTC
Labels: bug, external, metadata

**Comment by AverageComet250** [comment] 2021-05-16 09:14
@Ekmot276 u should still try using java 8 for forge and vanilla; fabric is the only loader to _properly_ support never versions, unless you're on snapshot 21w19a which adds java 16 support to vanilla mc
