### ISSUE TITLE
[suggestion]FTB version tracking

### ISSUE THREAD

**Issue by ppoozl** [MultiMC/MultiMC5#2337] opened 2018-07-13 15:45 UTC
Hi! Would you consider adding FTB modpack version tracking and update feature so that I can easily update my FTB modpack without deleting it and redownload it.

**Comment by Janrupf** [comment] 2018-07-13 17:38
Duplicate of #2287

**Comment by peterix** [comment] 2018-07-13 17:58
And the answer is: eventually.

**Closed** 2018-07-13 17:58 UTC
Labels: duplicate
