### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by MsDebbie616** [MultiMC/MultiMC5#1538] opened 2016-03-29 20:57 UTC
MultiMC version: 0.4.11-751

Minecraft folder is:
instances/New Series/minecraft

Java path is:
C:/ProgramData/Oracle/Java/javapath/java.exe

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx2048m, -Duser.language=en, -jar, C:/Users/debra/Videos/MultiMC/jars/NewLaunch.jar]

Minecraft process ID: 6000

Error occurred during initialization of VM
Could not reserve enough space for 2097152KB object heap
Process exited with code 1.

**Comment by NolanSyKinsley** [comment] 2016-03-29 21:03
How much memory do you have? Closing other processes may help. The error speaks for itself, not enough memory.

**Comment by MsDebbie616** [comment] 2016-03-29 23:38
How though? I guess got this new computer fml.

**Comment by peterix** [comment] 2016-03-29 23:48
http://www.computerhope.com/issues/ch000149.htm

Can you post a screenshot of that System window?

**Comment by MsDebbie616** [comment] 2016-03-30 01:04
not letting me screenshot, anyway that is the problem.Stroage :/  i guess i have to delete stuff im good now ty

**Comment by MsDebbie616** [comment] 2016-03-30 20:28
i deleted alot of things and it says the same error

**Comment by TacoGS** [comment] 2016-03-30 20:51
This means that the system is running out of RAM. the JVM (Java Virtual Machine) is not able to acquire enough memory to continue to do what is being asked of it.

2,097,152 KB = 2 GB of memory which it is not getting.

Deleting stuff from your hard drive doesn't solve this issue because memory is RAM not Hard Disk. Chances are you may have a small amount of RAM and you're trying to ask it to do too much.

If you hit the keys CTRL + SHIFT + ESC (all on the left side of the keyboard) and hit the performance tab you will see Memory with a scale that goes up and down. The higher to the top of that it gets the worse the problem as it is running out of usable memory.

If you can take a screenshot of that (remove identifiable information) we can possible help or at least advise what the problem is and solution.

Let us know.

**Comment by MsDebbie616** [comment] 2016-03-30 21:02
Actually, i had to update my java to a 64bit. It works now ty though

**Comment by TacoGS** [comment] 2016-03-30 21:02
Good to hear, You have a good day.

**Closed** 2016-03-30 21:10 UTC
