### ISSUE TITLE
Instance update failed because: Failed to download the following files:

### ISSUE THREAD

**Issue by Maescool** [MultiMC/MultiMC5#1482] opened 2016-02-16 16:45 UTC
When Creating a new instance or trying to update an instance to a new version, I'm getting this error:
````
Instance update failed because: Failed to download the following files:
http://s3.amazonaws.com/Minecraft.Download/versions//.jar

Reason:Job 'Libraries for instance 16w07b' failed to process:
http://s3.amazonaws.com/Minecraft.Download/versions//.jar
Please try again..
````
Have this issue on MultiMC 0.4.10-684 linux and 0.4.10-693 Mac
Just noticing this today..

**Comment by peterix** [comment] 2016-02-16 16:46
Duplicate of #1453

You can also refer to that for the workaround

**Closed by peterix** 2016-02-16 16:46 UTC
Labels: bug
