### ISSUE TITLE
Document: Error parsing JSON: illegal value

### ISSUE THREAD

**Issue by TwilightPSN** [MultiMC/MultiMC5#2658] opened 2019-05-19 18:03 UTC
System Information
-----------------------------
MultiMC version:
0.6.5

Operating System:
Windows 10 Pro 64-Bit

Summary of the issue or suggestion:
Unable to Download modpack due to Error Parsing JSON

Steps to reproduce the issue:
Try to download any pack update from 3.0 on from https://minecraft.curseforge.com/projects/immersive-revolution/files and it will not allow you to

[MultiMC-0.log](https://github.com/MultiMC/MultiMC5/files/3195422/MultiMC-0.log)

**Comment by flcmc** [comment] 2019-05-22 01:24
Duplicate of #2655. Should be fixed now.

**Closed** 2019-06-23 21:25 UTC
Labels: close:duplicate
