### ISSUE TITLE
List update failed: Job 'Download of meta file net.minecraft/index.json' failed to process

### ISSUE THREAD

**Issue by Knogle** [MultiMC/MultiMC5#2553] opened 2019-02-28 21:31 UTC
System Information
-----------------------------
MultiMC version: 0.6.5

Operating System: Linux (Debian)

Summary of the issue or suggestion:

Ahoy. Just performed a fresh install of Debian.
Then i installed MultiMC, openssl:amd64, openssl:i386 libssl-dev:amd64 and libssl-dev:i386.
I started MultiMC but received this message:

List update failed:
Job 'Download of meta file net.minecraft/index.json' failed to process:
https://v1.meta.multimc.org/net.minecraft/index.json

----------------------------------------------

What should happen:
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.

2.

3.

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

```
The MultiMC Log right here
    0.000 D <> Log initialized.
    0.000 D MultiMC 5, (c) 2013-2019 MultiMC Contributors
    0.000 D Version                    :  "0.6.5-develop-1216"
    0.000 D Git commit                 :  "ae956d8fd6007304cbf6174ead70e61a61d502b0"
    0.000 D Git refspec                :  "refs/heads/develop"
    0.001 D Work dir before adjustment :  "/home/chairman/Downloads/MultiMC"
    0.001 D Work dir after adjustment  :  "/home/chairman/Downloads/MultiMC"
    0.001 D Adjusted by                :  "Command line /home/chairman/Downloads/MultiMC"
    0.001 D Binary path                :  "/home/chairman/Downloads/MultiMC/bin"
    0.001 D Application root path      :  "/home/chairman/Downloads/MultiMC"
    0.001 D <> Paths set.
    0.006 D Detected default console font: "DejaVu Sans Mono" , substitutions: ""
    0.007 D <> Settings loaded.
    0.007 C Exception: "Unable to open /home/chairman/Downloads/MultiMC/translations/index_v2.json for reading: No such file or directory"
    0.007 C Translations Download Failed: index file not readable
    0.007 W QFileSystemWatcher::addPath: path is empty
    0.007 W Selected invalid language "" , defaulting to "en"
    0.007 D Your language is ""
    0.007 D <> Translations loaded.
    0.007 D <> Updater started.
    0.007 D Started watching  "/home/chairman/Downloads/MultiMC/icons"
    0.008 D <> Instance icons intialized.
    0.008 D <> Icon themes initialized.
    0.008 D ""
    0.008 D Loading theme "custom"
    0.008 D No theme json present.
    0.012 D No theme css present.
    0.015 D <> Widget themes initialized.
    0.015 D Instance path              :  "instances"
    0.015 D Loading Instances...
    0.015 D Discovering instances in "/home/chairman/Downloads/MultiMC/instances"
    0.015 D <> Instances loaded.
    0.015 D Loading accounts...
    0.015 C "Failed to read the account list file (accounts.json)."
    0.015 D <> Accounts loaded.
    0.015 D <> Cache initialized.
    0.015 D Detecting proxy settings...
    0.015 D Using no proxy is an option!
    0.015 D <> Proxy settings done.
    0.015 D Downloading Translations Index...
    0.015 D Task "NetJob(Translations Index)" starting for the first time
    0.015 D <> Icon theme set.
    0.015 D <> Application theme set.
    0.024 D Analytics info not seen by user yet (or old version).
    0.048 D Downloading  "https://files.multimc.org/translations/index_v2.json"
    0.051 W QSslSocket: cannot resolve CRYPTO_num_locks
    0.051 W QSslSocket: cannot resolve CRYPTO_set_id_callback
    0.051 W QSslSocket: cannot resolve CRYPTO_set_locking_callback
    0.051 W QSslSocket: cannot resolve ERR_free_strings
    0.051 W QSslSocket: cannot resolve sk_new_null
    0.051 W QSslSocket: cannot resolve sk_push
    0.051 W QSslSocket: cannot resolve sk_free
    0.051 W QSslSocket: cannot resolve sk_num
    0.051 W QSslSocket: cannot resolve sk_pop_free
    0.051 W QSslSocket: cannot resolve sk_value
    0.051 W QSslSocket: cannot resolve SSL_library_init
    0.051 W QSslSocket: cannot resolve SSL_load_error_strings
    0.051 W QSslSocket: cannot resolve SSLv3_client_method
    0.051 W QSslSocket: cannot resolve SSLv23_client_method
    0.051 W QSslSocket: cannot resolve SSLv3_server_method
    0.052 W QSslSocket: cannot resolve SSLv23_server_method
    0.052 W QSslSocket: cannot resolve X509_STORE_CTX_get_chain
    0.052 W QSslSocket: cannot resolve OPENSSL_add_all_algorithms_noconf
    0.052 W QSslSocket: cannot resolve OPENSSL_add_all_algorithms_conf
    0.052 W QSslSocket: cannot resolve SSLeay
    0.052 W QSslSocket: cannot resolve SSLeay_version
    0.052 W QSslSocket: cannot call unresolved function CRYPTO_num_locks
    0.052 W QSslSocket: cannot call unresolved function CRYPTO_set_id_callback
    0.052 W QSslSocket: cannot call unresolved function CRYPTO_set_locking_callback
    0.052 W QSslSocket: cannot call unresolved function SSL_library_init
    0.052 W QSslSocket: cannot call unresolved function SSLv23_client_method
    0.052 W QSslSocket: cannot call unresolved function sk_num
    0.073 W QSslSocket: cannot call unresolved function SSLv23_client_method
    0.073 W QSslSocket: cannot call unresolved function SSL_library_init
    0.089 W QSslSocket: cannot call unresolved function SSLv23_client_method
    0.090 W QSslSocket: cannot call unresolved function SSL_library_init
    0.107 W QSslSocket: cannot call unresolved function SSLv23_client_method
    0.107 W QSslSocket: cannot call unresolved function SSL_library_init
    0.108 C Failed  "https://files.multimc.org/translations/index_v2.json"  with reason  99
    0.108 D Download failed in previous step: "https://files.multimc.org/translations/index_v2.json"
    0.108 D Downloading  "https://files.multimc.org/translations/index_v2.json"
    0.124 W QSslSocket: cannot call unresolved function SSLv23_client_method
    0.124 W QSslSocket: cannot call unresolved function SSL_library_init
    0.124 C Failed  "https://files.multimc.org/translations/index_v2.json"  with reason  99
    0.124 D Download failed in previous step: "https://files.multimc.org/translations/index_v2.json"
    0.125 D Downloading  "https://files.multimc.org/translations/index_v2.json"
    0.141 W QSslSocket: cannot call unresolved function SSLv23_client_method
    0.141 W QSslSocket: cannot call unresolved function SSL_library_init
    0.141 C Failed  "https://files.multimc.org/translations/index_v2.json"  with reason  99
    0.141 D Download failed in previous step: "https://files.multimc.org/translations/index_v2.json"
    0.141 D Downloading  "https://files.multimc.org/translations/index_v2.json"
    0.157 W QSslSocket: cannot call unresolved function SSLv23_client_method
    0.157 W QSslSocket: cannot call unresolved function SSL_library_init
    0.157 C Failed  "https://files.multimc.org/translations/index_v2.json"  with reason  99
    0.158 D Download failed in previous step: "https://files.multimc.org/translations/index_v2.json"
    0.158 C Task "NetJob(Translations Index)" failed:  "Job 'Translations Index' failed to process:
https://files.multimc.org/translations/index_v2.json"
    0.158 C Translations Index Download Failed: "Job 'Translations Index' failed to process:
https://files.multimc.org/translations/index_v2.json"
    1.955 D Task "JavaListLoadTask(0x7f97a00095e0)" starting for the first time
    1.955 D Linux Java detection incomplete - defaulting to "java"
    1.956 D Probing the following Java paths: 
    1.956 D   "java"
    1.956 D   "/usr/lib/jvm/java-1.5.0-gcj-6-amd64/jre/bin/java"
    1.956 D   "/usr/lib/jvm/java-1.5.0-gcj-6-amd64/bin/java"
    1.956 D   "/usr/lib/jvm/java-11-openjdk-amd64/jre/bin/java"
    1.956 D   "/usr/lib/jvm/java-11-openjdk-amd64/bin/java"
    1.956 D   "/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java"
    1.956 D   "/usr/lib/jvm/java-8-openjdk-amd64/bin/java"
    1.956 D Task "JavaCheckerJob(0x1b80dc0)" starting for the first time
    1.956 D "Java detection"  started.
    1.956 D Env: ignoring "QT_LINUX_ACCESSIBILITY_ALWAYS_ON" "1"
    1.956 D Env: ignoring "QT_QPA_PLATFORMTHEME" "qgnomeplatform"
    1.956 D Env: ignoring "QT_ACCESSIBILITY" "1"
    1.956 D Env: ignoring "LD_LIBRARY_PATH" "/home/chairman/Downloads/MultiMC/bin:"
    1.956 D Env: ignoring "LD_PRELOAD" ""
    1.956 D Env: ignoring "QT_PLUGIN_PATH" "/home/chairman/Downloads/MultiMC/plugins"
    1.956 D Env: ignoring "QT_FONTPATH" "/home/chairman/Downloads/MultiMC/fonts"
    1.956 D Env: ignoring "QT_IM_MODULE" "compose"
    1.956 D "Running java checker: java-jar /home/chairman/Downloads/MultiMC/bin/jars/JavaCheck.jar"
    1.957 D Env: ignoring "QT_LINUX_ACCESSIBILITY_ALWAYS_ON" "1"
    1.957 D Env: ignoring "QT_QPA_PLATFORMTHEME" "qgnomeplatform"
    1.957 D Env: ignoring "QT_ACCESSIBILITY" "1"
    1.957 D Env: ignoring "LD_LIBRARY_PATH" "/home/chairman/Downloads/MultiMC/bin:"
    1.957 D Env: ignoring "LD_PRELOAD" ""
    1.957 D Env: ignoring "QT_PLUGIN_PATH" "/home/chairman/Downloads/MultiMC/plugins"
    1.957 D Env: ignoring "QT_FONTPATH" "/home/chairman/Downloads/MultiMC/fonts"
    1.958 D Env: ignoring "QT_IM_MODULE" "compose"
    1.958 D "Running java checker: /usr/lib/jvm/java-1.5.0-gcj-6-amd64/jre/bin/java-jar /home/chairman/Downloads/MultiMC/bin/jars/JavaCheck.jar"
    1.958 D Env: ignoring "QT_LINUX_ACCESSIBILITY_ALWAYS_ON" "1"
    1.958 D Env: ignoring "QT_QPA_PLATFORMTHEME" "qgnomeplatform"
    1.958 D Env: ignoring "QT_ACCESSIBILITY" "1"
    1.958 D Env: ignoring "LD_LIBRARY_PATH" "/home/chairman/Downloads/MultiMC/bin:"
    1.958 D Env: ignoring "LD_PRELOAD" ""
    1.958 D Env: ignoring "QT_PLUGIN_PATH" "/home/chairman/Downloads/MultiMC/plugins"
    1.958 D Env: ignoring "QT_FONTPATH" "/home/chairman/Downloads/MultiMC/fonts"
    1.958 D Env: ignoring "QT_IM_MODULE" "compose"
    1.958 D "Running java checker: /usr/lib/jvm/java-1.5.0-gcj-6-amd64/bin/java-jar /home/chairman/Downloads/MultiMC/bin/jars/JavaCheck.jar"
    1.960 D Env: ignoring "QT_LINUX_ACCESSIBILITY_ALWAYS_ON" "1"
    1.960 D Env: ignoring "QT_QPA_PLATFORMTHEME" "qgnomeplatform"
    1.960 D Env: ignoring "QT_ACCESSIBILITY" "1"
    1.960 D Env: ignoring "LD_LIBRARY_PATH" "/home/chairman/Downloads/MultiMC/bin:"
    1.960 D Env: ignoring "LD_PRELOAD" ""
    1.960 D Env: ignoring "QT_PLUGIN_PATH" "/home/chairman/Downloads/MultiMC/plugins"
    1.960 D Env: ignoring "QT_FONTPATH" "/home/chairman/Downloads/MultiMC/fonts"
    1.960 D Env: ignoring "QT_IM_MODULE" "compose"
    1.960 D "Running java checker: /usr/lib/jvm/java-11-openjdk-amd64/jre/bin/java-jar /home/chairman/Downloads/MultiMC/bin/jars/JavaCheck.jar"
    1.961 D Env: ignoring "QT_LINUX_ACCESSIBILITY_ALWAYS_ON" "1"
    1.961 D Env: ignoring "QT_QPA_PLATFORMTHEME" "qgnomeplatform"
    1.961 D Env: ignoring "QT_ACCESSIBILITY" "1"
    1.961 D Env: ignoring "LD_LIBRARY_PATH" "/home/chairman/Downloads/MultiMC/bin:"
    1.961 D Env: ignoring "LD_PRELOAD" ""
    1.961 D Env: ignoring "QT_PLUGIN_PATH" "/home/chairman/Downloads/MultiMC/plugins"
    1.961 D Env: ignoring "QT_FONTPATH" "/home/chairman/Downloads/MultiMC/fonts"
    1.961 D Env: ignoring "QT_IM_MODULE" "compose"
    1.961 D "Running java checker: /usr/lib/jvm/java-11-openjdk-amd64/bin/java-jar /home/chairman/Downloads/MultiMC/bin/jars/JavaCheck.jar"
    1.962 D Env: ignoring "QT_LINUX_ACCESSIBILITY_ALWAYS_ON" "1"
    1.962 D Env: ignoring "QT_QPA_PLATFORMTHEME" "qgnomeplatform"
    1.962 D Env: ignoring "QT_ACCESSIBILITY" "1"
    1.962 D Env: ignoring "LD_LIBRARY_PATH" "/home/chairman/Downloads/MultiMC/bin:"
    1.962 D Env: ignoring "LD_PRELOAD" ""
    1.962 D Env: ignoring "QT_PLUGIN_PATH" "/home/chairman/Downloads/MultiMC/plugins"
    1.962 D Env: ignoring "QT_FONTPATH" "/home/chairman/Downloads/MultiMC/fonts"
    1.962 D Env: ignoring "QT_IM_MODULE" "compose"
    1.962 D "Running java checker: /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java-jar /home/chairman/Downloads/MultiMC/bin/jars/JavaCheck.jar"
    1.963 D Env: ignoring "QT_LINUX_ACCESSIBILITY_ALWAYS_ON" "1"
    1.963 D Env: ignoring "QT_QPA_PLATFORMTHEME" "qgnomeplatform"
    1.963 D Env: ignoring "QT_ACCESSIBILITY" "1"
    1.963 D Env: ignoring "LD_LIBRARY_PATH" "/home/chairman/Downloads/MultiMC/bin:"
    1.963 D Env: ignoring "LD_PRELOAD" ""
    1.963 D Env: ignoring "QT_PLUGIN_PATH" "/home/chairman/Downloads/MultiMC/plugins"
    1.963 D Env: ignoring "QT_FONTPATH" "/home/chairman/Downloads/MultiMC/fonts"
    1.963 D Env: ignoring "QT_IM_MODULE" "compose"
    1.963 D "Running java checker: /usr/lib/jvm/java-8-openjdk-amd64/bin/java-jar /home/chairman/Downloads/MultiMC/bin/jars/JavaCheck.jar"
    1.970 D Java checker has failed to start.
    1.970 D "Java detection" progress: 1 / 7
    1.971 D Java checker has failed to start.
    1.971 D "Java detection" progress: 2 / 7
    1.971 D Java checker has failed to start.
    1.972 D "Java detection" progress: 3 / 7
    2.009 D STDOUT "os.arch=amd64
java.version=11.0.2
"
    2.009 W STDERR ""
    2.009 D Java checker finished with status  0  exit code  0
    2.010 D Java checker succeeded.
    2.010 D "Java detection" progress: 4 / 7
    2.011 D STDOUT "os.arch=amd64
java.version=1.8.0_181
"
    2.011 W STDERR ""
    2.011 D Java checker finished with status  0  exit code  0
    2.011 D Java checker succeeded.
    2.011 D "Java detection" progress: 5 / 7
    2.013 D STDOUT "os.arch=amd64
java.version=1.8.0_181
"
    2.013 W STDERR ""
    2.013 D Java checker finished with status  0  exit code  0
    2.013 D Java checker succeeded.
    2.013 D "Java detection" progress: 6 / 7
    2.019 D STDOUT "os.arch=amd64
java.version=11.0.2
"
    2.019 W STDERR ""
    2.019 D Java checker finished with status  0  exit code  0
    2.019 D Java checker succeeded.
    2.019 D "Java detection" progress: 7 / 7
    2.020 D Task "JavaCheckerJob(0x1b80dc0)" succeeded
    2.020 D Found the following valid Java installations:
    2.020 D   "11.0.2" "64" "java"
    2.020 D   "11.0.2" "64" "/usr/lib/jvm/java-11-openjdk-amd64/bin/java"
    2.020 D   "1.8.0_181" "64" "/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java"
    2.020 D   "1.8.0_181" "64" "/usr/lib/jvm/java-8-openjdk-amd64/bin/java"
    2.020 D Task "JavaListLoadTask(0x7f97a00095e0)" succeeded
    2.021 D Env: ignoring "QT_LINUX_ACCESSIBILITY_ALWAYS_ON" "1"
    2.021 D Env: ignoring "QT_QPA_PLATFORMTHEME" "qgnomeplatform"
    2.021 D Env: ignoring "QT_ACCESSIBILITY" "1"
    2.021 D Env: ignoring "LD_LIBRARY_PATH" "/home/chairman/Downloads/MultiMC/bin:"
    2.021 D Env: ignoring "LD_PRELOAD" ""
    2.022 D Env: ignoring "QT_PLUGIN_PATH" "/home/chairman/Downloads/MultiMC/plugins"
    2.022 D Env: ignoring "QT_FONTPATH" "/home/chairman/Downloads/MultiMC/fonts"
    2.022 D Env: ignoring "QT_IM_MODULE" "compose"
    2.022 D "Running java checker: /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java-Xms512m -Xmx1024m -jar /home/chairman/Downloads/MultiMC/bin/jars/JavaCheck.jar"
    2.075 D STDOUT "os.arch=amd64
java.version=1.8.0_181
"
    2.075 W STDERR ""
   
   33.052 C Task "Flame::FileResolvingTask(0x1b6abb0)" failed:  "Some mod ID resolving tasks failed."
   33.052 C Task "InstanceImportTask(0x1dabeb0)" failed:  "Unable to resolve mod IDs:
Some mod ID resolving tasks failed."
   33.065 C Task "InstanceStaging(0x7f97a000e030)" failed:  "Unable to resolve mod IDs:
Some mod ID resolving tasks failed."

```
Additional Info:
---------------------------

**Comment by brodycas3** [comment] 2019-02-28 21:35
When you upload the log can you upload it to something like paste.ee next time, Or you can upload the log file straight to GitHub.

**Comment by ThePhisics101** [comment] 2019-04-27 06:34
I'm having a similar issue on Ubuntu 19.04 (Mate 1.20.4)
Sometimes it crashes on launch:
https://hastebin.com/adujoqacez.makefile
Sometimes it doesn't, but i can't do anything that requires an internet connection (although I am connected):
https://hastebin.com/agomefuwav.makefile

**Comment by QuImUfu** [comment] 2019-04-28 08:31
Another duplicate of: https://github.com/MultiMC/MultiMC5/issues/1816

**Comment by Mattia98** [comment] 2019-05-15 09:52
I have this problem too on Ubuntu 19.04

**Closed** 2019-06-16 10:11 UTC
Labels: close:duplicate

**Comment by codydafoxie** [comment] 2024-10-26 22:00
I have this problem too on Windows XP SP3.

**Comment by BestCoder1877** [comment] 2025-03-11 14:58
I found the solution download the file manually and place it in the net.minecraft folder that is inside the meta folder

**Comment by phit** [comment] 2025-03-11 15:29
that's not a solution, 90% of the time this is caused by an outdated OS
on Windows XP: https://legacyupdate.net/
on Windows Vista/7: fully updating is enough, if your Windows Update doesn't work, fix that
