### ISSUE TITLE
minecraft 1.17 does not work

### ISSUE THREAD

**Issue by Herobrine7707** [MultiMC/MultiMC5#3935] opened 2021-07-14 10:36 UTC
### Operating System

Other

### Description of bug

MuliMC I have been using for many years and a few weeks ago I don't know exactly it came out 1.17 I wanted to test it was quite normal on charging even before it started was crashed directly and minecraft is not even started they can help me

### Steps to reproduce

1.17

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by RDKRACZ** [comment] 2021-07-14 11:06
There is no log so nobody is able to help you.

**Suspected cause**
Java 8 instead required 16.

> I have searched the issue tracker and did not find an issue describing my bug.

Are you sure?
https://github.com/MultiMC/MultiMC5/issues?q=1.17+crash
https://github.com/MultiMC/MultiMC5/issues?q=1.17+not_work

**Comment by jamierocks** [comment] 2021-07-14 11:20
Unable to reproduce, closing.

**Closed by jamierocks** 2021-07-14 11:20 UTC
Labels: bug
