### ISSUE TITLE
Update function for modpacks

### ISSUE THREAD

**Issue by DeathDragonAW** [MultiMC/MultiMC5#4065] opened 2021-09-01 15:16 UTC
### Role

Player

### Suggestion

(Auto-)Updates for modpacks from curse or FTB

### Benefit

To not mess around with the instance files by hand.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by Janrupf** [comment] 2021-09-01 17:59
> I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.


Duplicate of #2640

**Closed** 2021-09-01 18:21 UTC

**Comment by DeathDragonAW** [comment] 2021-09-01 19:20
Oh boy, didn't search that long back. Sorry!
