### ISSUE TITLE
If two packs share the same iconKey with a custom icon, the new pack's icon replaces the old one permanantly

### ISSUE THREAD

**Issue by Merith-TK** [MultiMC/MultiMC5#4058] opened 2021-08-29 23:30 UTC
### Operating System

Windows

### Description of bug

Keep an Eye on the Fallen Order icon under the "Server Packs" group

This is just with the fallen Order modpack 
![image](https://user-images.githubusercontent.com/10422110/131268590-f87a5fa4-c93b-4bf8-a5d5-7539a6fe4904.png)

it has its own icon with the icon key "icon" and the image being `icon.png`

Now this is what happens when I import a modpack that has its own icon, with the same Icon Key
![image](https://user-images.githubusercontent.com/10422110/131268626-867d2819-20c2-4ac3-a869-e69ca8b8eaa4.png)

The Fallen Order pack icon gets changed to the `modpack` icon permanantly
(after uninstalling `modpack`)
![image](https://user-images.githubusercontent.com/10422110/131268714-64b41006-94f9-4fe5-8ccf-521c68b9325d.png)

It exibits the same behavior with built in pack icons (see vanillia pack 1.16.5 in previous screenshots, its iconKey is `stone`)
![image](https://user-images.githubusercontent.com/10422110/131268736-cf924040-3aea-4529-90e8-823251cbe307.png)
![image](https://user-images.githubusercontent.com/10422110/131268818-98c53bc4-46a5-4b99-b7ef-5fad1a88a953.png)

### Steps to reproduce

Create a instance with an custom icon named "icon.png" and its iconKey being "icon"

import this zip
[modpack.zip](https://github.com/MultiMC/MultiMC5/files/7073371/modpack.zip)

wait a second for multimc to refresh with the changes,

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment] 2021-08-30 07:32
Duplicate of https://github.com/MultiMC/MultiMC5/issues/3068

**Closed by phit** 2021-08-30 07:32 UTC
Labels: bug
