### ISSUE TITLE
Direct Server Joining doesn't work

### ISSUE THREAD

**Issue by RaXorX** [MultiMC/MultiMC5#3929] opened 2021-07-11 12:43 UTC
### Operating System

Windows

### Description of bug

Setting a default server to Join on startup in the miscellanous settings or using the Join button from the server tab in edit instance mode, either of those crashes minecraft while launching the same server after the game loads work fine.

### Steps to reproduce

Assign a server as a default to join right on launch and launch the instance or add a server from the servers tab within the instance setting and click on Join for that server. Minecraft starts and crashes.

### Suspected cause

The server does has mods and the client too, the ones that are required to join the server. Once the instance launches can join the server fine but otherwise not.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment] 2021-07-11 13:22
this is broken in some Minecraft versions https://bugs.mojang.com/browse/MC-145102
what version are you trying?

**Comment by RaXorX** [comment] 2021-07-12 06:11
1.17 (server and client sided)

**Comment by jamierocks** [comment] 2021-07-13 13:50
Can you supply a game log?

![image](https://user-images.githubusercontent.com/5103549/125463639-cb49691b-e02f-4076-80a7-ccbac997bfaf.png)

**Comment by jamierocks** [comment] 2021-07-15 13:46
I've reproduced this, it appears to be a game bug.

**Comment by RaXorX** [comment] 2021-07-17 21:55
Really sorry for the late reply. Let me know if the logs are still needed although considering you got it to reproduce I am guessing not.

**Comment by jamierocks** [comment] 2021-07-17 21:59
No we're good for logs, thank you though. Unfortunately it's a game bug so there's not much that we can do about it :(

**Comment by phit** [comment] 2021-07-20 15:33
closing since this is out of our control, should be fixed in 1.17.1 though
https://bugs.mojang.com/browse/MC-228828

**Closed by phit** 2021-07-20 15:33 UTC
Labels: bug, minecraft
