### ISSUE TITLE
Failure while trying to install TerraFirmaPunk (forge download)

### ISSUE THREAD

**Issue by Nicba1010** [MultiMC/MultiMC5#2450] opened 2018-11-03 09:28 UTC
System Information
-----------------------------
MultiMC version:
0.6.2-1222
Operating System:
Windows 10 64-bit | Java 1.8.0_171 64-bit
Summary of the issue or suggestion:
----------------------------------------------
Instance update failed because: Game update failed: it was impossible to fetch the required libraries.
Reason:
Job 'Libraries for instance TerraFirmaPunk' failed to process:
http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.7.10-10.13.4.1566-1.7.10/forge-1.7.10-10.13.4.1566-1.7.10-universal.jar.

What should happen:
------------------------------
TerraFirmaPunk should install.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Try install TerraFirmaPunk

2. Try launch TerraFirmaPunk

Suspected cause:
---------------------------
Forge download fails half way! Possibly a forge download server issue. It fails in chrome too now that I look at it. Suggested fix: Increase download retries or make it configurable when dealing with such janky downloads.

Logs/Screenshots:
----------------------------
[Log](https://paste.ee/p/jmw9Q)

Additional Info:
---------------------------

**Comment by Nicba1010** [comment] 2018-11-03 19:13
@JulianWebb I'd beg to differ. Yes it is a Forge problem but it would be nice to be able to set a custom resume/retry count. Also I don't think it even tries to resume but only retry.

**Comment by JulianWebb** [comment] 2018-11-03 19:16
That would be a feature suggestion, not a bug report. This issue, right here, right now, is not solvable by MultiMC.

**Comment by peterix** [comment] 2018-11-04 12:54
Fixed on forge server side.

**Closed by peterix** 2018-11-04 12:54 UTC
