### ISSUE TITLE
Cannot add a Minecraft Account to MultiMC

### ISSUE THREAD

**Issue by radzo73** [MultiMC/MultiMC5#2307] opened 2018-06-02 22:44 UTC
System Information
-----------------------------
MultiMC version:
0.6.2

Operating System:
Mac OS X 10.7.5

Summary of the issue or suggestion:
----------------------------------------------
I cannot add an account to MultiMC All I get is
"Authentication operation failed due to a network error: Failed to set protocol version (99)"

What should happen:
------------------------------
I am able to add an account to Multi MC

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Attempt to log in with a Minecraft Account

Additional Info:
---------------------------
All servers (Auth, API, etc) are up at the time of this writing
No instances have been created/imported, either.

**Comment by Janrupf** [comment] 2018-06-03 08:49
Wew, we only had this issue on Linux AFAIK. (Or maybe on older OSX?) On Linux installing openssl1.0-dev fixed it in most cases, maybe thats possible with homebrew or something? Anyway, can you post the MultiMC log (its in the MultiMC directory) and called multimc.log or multimc.0.log?

**Comment by radzo73** [comment] 2018-06-03 14:38
where would I find said logs? They're not appearing in Console, and MultiMC doesn't have a folder in my Application Support folder.

**Comment by peterix** [comment] 2018-06-03 14:45
All of the data is inside the application. So just open it up (shift richt click lets you do that in Finder).

**Comment by peterix** [comment] 2018-06-03 14:47
What I suspect is that there's some problem with SSL (encrypted access to web servers). Current MultiMC uses the system SSL framework instead of OpenSSL, and it seems to have problems on very old versions of OS X.

**Comment by radzo73** [comment] 2018-06-03 15:52
[MultiMC-0.log](https://github.com/MultiMC/MultiMC5/files/2066100/MultiMC-0.log)
[MultiMC-1.log](https://github.com/MultiMC/MultiMC5/files/2066101/MultiMC-1.log)
[MultiMC-2.log](https://github.com/MultiMC/MultiMC5/files/2066102/MultiMC-2.log)
[MultiMC-3.log](https://github.com/MultiMC/MultiMC5/files/2066103/MultiMC-3.log)
[MultiMC-4.log](https://github.com/MultiMC/MultiMC5/files/2066104/MultiMC-4.log)
This is all I found while searching for .log files in the app

**Comment by peterix** [comment] 2018-06-03 16:45
https://code.woboq.org/qt5/qtbase/src/network/ssl/qsslsocket_mac.cpp.html#877

Looks like an upstream problem between Qt and OS X.

**Comment by radzo73** [comment] 2018-06-03 16:49
...ok, so what can I do about it to fix it?

**Comment by peterix** [comment] 2018-06-03 16:50
Update your OS.

**Comment by radzo73** [comment] 2018-06-03 16:51
I actually can't (because my computer is that old)

**Comment by peterix** [comment] 2018-06-03 17:08
Hmm... I'll have to look into that then. The problem is that I haven't been able to get hold of OSX that old, so I can't properly test it.

**Comment by radzo73** [comment] 2018-06-03 19:20
~~have my computer then~~ I can wait, take your time...

**Comment by radzo73** [comment] 2018-06-06 18:47
I ran `brew install openssl`, and it didn't work. Does it have to be openssl1.0-dev or the latest version? I don't know where to look for openssl1.0-dev if it's the version I need...

**Comment by peterix** [comment] 2018-06-06 19:48
That won't help, because multimc no longer uses it on macos

**Comment by radzo73** [comment] 2018-06-06 20:07
then what would? (if you know)

**Comment by peterix** [comment] 2018-06-06 20:26
Me building openssl, bundling it with MMC, building custom qt, and bundling that too. Ideally with a machine that has 10.7 on it for testing, otherwise it could take a while to get it right...

**Comment by radzo73** [comment] 2018-06-06 20:43
I could help with testing (if that's even possible)

**Comment by AriaanBruinsma** [comment] 2019-06-05 05:28
Seems I had a similar issue, I had to delete the Qt5Lib files from my installation. It was probably conflicting.
 
Duplicate of #1784

**Comment by phit** [comment] 2021-03-09 20:45
Duplicate of https://github.com/MultiMC/MultiMC5/issues/2085

**Closed by phit** 2021-03-09 20:45 UTC
Labels: bug, external
