### ISSUE TITLE
HiDPI Support

### ISSUE THREAD

**Issue by nikhiljha** [MultiMC/MultiMC5#1767] opened 2017-01-02 19:09 UTC
System Information
-----------------------------
MultiMC version: 0.4.11-751

Operating System: Windows 10

Summary of the issue or suggestion:
----------------------------------------------
Various parts of the MultiMC UI do not scale well when viewed on a HiDPI monitor. My 13 inch monitor at 4k looks like this:

![](http://i.imgur.com/nSZzLsE.png)

What should happen:
------------------------------
MultiMC should take into account windows scaling, [as seen here.](https://doc.qt.io/qt-5/highdpi.html)

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Open MultiMC on a HiDPI display.

Suspected cause:
---------------------------
Not taking into account windows scaling. 👍 

Additional Info:
---------------------------

[This is a nice link.](https://doc.qt.io/qt-5/highdpi.html)

**Comment by peterix** [comment] 2017-01-03 16:55
Yes, this would require upgrading Qt.

Duplicate of #647

**Closed by peterix** 2017-01-03 16:55 UTC
Labels: bug

**Comment by grennis** [comment] 2017-07-12 00:04
Just wanted to tell you that I added the command line parameter -platform windows:dpiawareness=0 and that fixed the scaling. MultiMC looks great on high DPI display.
