### ISSUE TITLE
MultiMC showing 64-bit Java versions as 32-bit

### ISSUE THREAD

**Issue by adammbaker** [MultiMC/MultiMC5#3933] opened 2021-07-14 00:27 UTC
### Operating System

macOS

### Description of bug

MultiMC is showing my confirmed 64-bit Java installations as 32-bit; won't let me launch Minecraft.

### Steps to reproduce

Install 64-bit versions of Java.
Go to settings; or, attempt to launch game.
Confirm in the Terminal.app by typing `java --version` and seeing:
`openjdk 16.0.1 2021-04-20`
`OpenJDK Runtime Environment Zulu16.30+19-CA (build 16.0.1+9)`
`OpenJDK 64-Bit Server VM Zulu16.30+19-CA (build 16.0.1+9, mixed mode)`

### Suspected cause

There might be some sort of issue with MultiMC not playing well with M1 Macs (64-bit ARM).

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Zetabite** [comment] 2021-07-14 00:28
Have you made sure that not multiple java versions are installed?

**Comment by adammbaker** [comment] 2021-07-14 00:36
Default Java installation is at `/Library/Java/JavaVirtualMachines/zulu-16.jdk/Contents/Home`.

When I go to Edit Instance -> Settings -> Test it displays:
`Java test succeeded!`
`Platform reported: aarch64`
`Java version reported: 16.0.1`
`Java vendor reported: Azul Systems, Inc.`

I do have several Java versions installed since no previous installation was seen as 32-bit. I thought maybe I installed the wrong version so I installed Java 11 then Java 16 to no avail.

**Comment by adammbaker** [comment] 2021-07-14 00:38
<img width="749" alt="Screen Shot 2021-07-13 at 18 37 28" src="https://user-images.githubusercontent.com/50785507/125542679-6893b582-d7b5-4741-bb7b-c3164e415375.png">
Here is the list of installations that are 64-bit but seen as 32-bit.

**Comment by adammbaker** [comment] 2021-07-14 00:40
Here is the Minecraft Log dump:

> MultiMC version: 0.6.12-1466
> 
> 
> Minecraft folder is:
> /Applications/MultiMC.app/Contents/MacOS/instances/Vanilla Plus/.minecraft
> 
> 
> Java path is:
> /Library/Java/JavaVirtualMachines/zulu-16.jdk/Contents/Home/bin/java
> 
> 
> Checking Java version...
> Java is version 16.0.1, using 32-bit architecture, from Azul Systems, Inc..
> 
> 
> Your Java architecture is not matching your system architecture. You might want to install a 64bit Java version.
> 
> 
> Main Class:
>   net.fabricmc.loader.launch.knot.KnotClient
> 
> Native path:
>   /Applications/MultiMC.app/Contents/MacOS/instances/Vanilla Plus/natives
> 
> Traits:
> traits XR:Initial
> traits FirstThreadOnMacOS
> 
> Libraries:
>   /Applications/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
>   /Applications/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
>   /Applications/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
>   /Applications/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
>   /Applications/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
>   /Applications/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
>   /Applications/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
>   /Applications/MultiMC.app/Contents/MacOS/libraries/com/mojang/blocklist/1.0.5/blocklist-1.0.5.jar
>   /Applications/MultiMC.app/Contents/MacOS/libraries/com/mojang/patchy/2.1.6/patchy-2.1.6.jar
>   /Applications/MultiMC.app/Contents/MacOS/libraries/com/github/oshi/oshi-core/5.7.5/oshi-core-5.7.5.jar
>   /Applications/MultiMC.app/Contents/MacOS/libraries/net/java/dev/jna/jna/5.8.0/jna-5.8.0.jar
>   /Applications/MultiMC.app/Contents/MacOS/libraries/net/java/dev/jna/jna-platform/5.8.0/jna-platform-5.8.0.jar
>   /Applications/MultiMC.app/Contents/MacOS/libraries/org/slf4j/slf4j-api/1.8.0-beta4/slf4j-api-1.8.0-beta4.jar
>   /Applications/MultiMC.app/Contents/MacOS/libraries/org/apache/logging/log4j/log4j-slf4j18-impl/2.14.1/log4j-slf4j18-impl-2.14.1.jar
>   /Applications/MultiMC.app/Contents/MacOS/libraries/com/ibm/icu/icu4j/66.1/icu4j-66.1.jar
>   /Applications/MultiMC.app/Contents/MacOS/libraries/com/mojang/javabridge/1.1.23/javabridge-1.1.23.jar
>   /Applications/MultiMC.app/Contents/MacOS/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
>   /Applications/MultiMC.app/Contents/MacOS/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
>   /Applications/MultiMC.app/Contents/MacOS/libraries/com/google/guava/guava/21.0/guava-21.0.jar
>   /Applications/MultiMC.app/Contents/MacOS/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
>   /Applications/MultiMC.app/Contents/MacOS/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
>   /Applications/MultiMC.app/Contents/MacOS/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
>   /Applications/MultiMC.app/Contents/MacOS/libraries/com/mojang/brigadier/1.0.18/brigadier-1.0.18.jar
>   /Applications/MultiMC.app/Contents/MacOS/libraries/com/mojang/datafixerupper/4.0.26/datafixerupper-4.0.26.jar
>   /Applications/MultiMC.app/Contents/MacOS/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
>   /Applications/MultiMC.app/Contents/MacOS/libraries/com/mojang/authlib/2.3.31/authlib-2.3.31.jar
>   /Applications/MultiMC.app/Contents/MacOS/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
>   /Applications/MultiMC.app/Contents/MacOS/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
>   /Applications/MultiMC.app/Contents/MacOS/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
>   /Applications/MultiMC.app/Contents/MacOS/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
>   /Applications/MultiMC.app/Contents/MacOS/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
>   /Applications/MultiMC.app/Contents/MacOS/libraries/org/apache/logging/log4j/log4j-api/2.14.1/log4j-api-2.14.1.jar
>   /Applications/MultiMC.app/Contents/MacOS/libraries/org/apache/logging/log4j/log4j-core/2.14.1/log4j-core-2.14.1.jar
>   /Applications/MultiMC.app/Contents/MacOS/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
>   /Applications/MultiMC.app/Contents/MacOS/libraries/ca/weblite/java-objc-bridge/1.0.0/java-objc-bridge-1.0.0.jar
>   /Applications/MultiMC.app/Contents/MacOS/libraries/net/fabricmc/intermediary/1.17.1/intermediary-1.17.1.jar
>   /Applications/MultiMC.app/Contents/MacOS/libraries/net/fabricmc/tiny-mappings-parser/0.2.2.14/tiny-mappings-parser-0.2.2.14.jar
>   /Applications/MultiMC.app/Contents/MacOS/libraries/net/fabricmc/sponge-mixin/0.9.4+mixin.0.8.2/sponge-mixin-0.9.4+mixin.0.8.2.jar
>   /Applications/MultiMC.app/Contents/MacOS/libraries/net/fabricmc/tiny-remapper/0.4.2/tiny-remapper-0.4.2.jar
>   /Applications/MultiMC.app/Contents/MacOS/libraries/net/fabricmc/access-widener/1.0.0/access-widener-1.0.0.jar
>   /Applications/MultiMC.app/Contents/MacOS/libraries/net/fabricmc/fabric-loader-sat4j/2.3.5.4/fabric-loader-sat4j-2.3.5.4.jar
>   /Applications/MultiMC.app/Contents/MacOS/libraries/com/google/jimfs/jimfs/1.2-fabric/jimfs-1.2-fabric.jar
>   /Applications/MultiMC.app/Contents/MacOS/libraries/org/ow2/asm/asm/9.1/asm-9.1.jar
>   /Applications/MultiMC.app/Contents/MacOS/libraries/org/ow2/asm/asm-analysis/9.1/asm-analysis-9.1.jar
>   /Applications/MultiMC.app/Contents/MacOS/libraries/org/ow2/asm/asm-commons/9.1/asm-commons-9.1.jar
>   /Applications/MultiMC.app/Contents/MacOS/libraries/org/ow2/asm/asm-tree/9.1/asm-tree-9.1.jar
>   /Applications/MultiMC.app/Contents/MacOS/libraries/org/ow2/asm/asm-util/9.1/asm-util-9.1.jar
>   /Applications/MultiMC.app/Contents/MacOS/libraries/net/fabricmc/fabric-loader/0.11.6/fabric-loader-0.11.6.jar
>   /Applications/MultiMC.app/Contents/MacOS/libraries/com/mojang/minecraft/1.17.1/minecraft-1.17.1-client.jar
> 
> Native libraries:
>   /Applications/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-macos.jar
>   /Applications/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-macos.jar
>   /Applications/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-macos.jar
>   /Applications/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-macos.jar
>   /Applications/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-macos.jar
>   /Applications/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-macos.jar
>   /Applications/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-macos.jar
>   /Applications/MultiMC.app/Contents/MacOS/libraries/ca/weblite/java-objc-bridge/1.0.0/java-objc-bridge-1.0.0-natives-osx.jar
> 
> Params:
>   --username  --version MultiMC5 --gameDir /Applications/MultiMC.app/Contents/MacOS/instances/Vanilla Plus/.minecraft --assetsDir /Applications/MultiMC.app/Contents/MacOS/assets --assetIndex 1.17 --uuid  --accessToken  --userType  --versionType release
> 
> Window size: 854 x 480
> 
> Java Arguments:
> [-Xdock:icon=icon.png, -Xdock:name="MultiMC: Vanilla Plus", -XstartOnFirstThread, -Xms512m, -Xmx2048m, -Duser.language=en]
> 
> 
> Minecraft process ID: 29802
> 
> 
> Using onesix launcher.
> 
> [18:39:16] [main/INFO]: Loading for game Minecraft 1.17.1
> [18:39:16] [main/INFO]: [FabricLoader] Loading 3 mods:
> 	- fabricloader@0.11.6
> 	- java@16
> 	- minecraft@1.17.1
> [18:39:16] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/Applications/MultiMC.app/Contents/MacOS/libraries/net/fabricmc/sponge-mixin/0.9.4+mixin.0.8.2/sponge-mixin-0.9.4+mixin.0.8.2.jar Service=Knot/Fabric Env=CLIENT
> [18:39:19] [Render thread/INFO]: [STDERR]: [LWJGL] Failed to load a library. Possible solutions:
> 	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
> 	b) Add the JAR that contains the shared library to the classpath.
> [18:39:19] [Render thread/INFO]: [STDERR]: [LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
> [18:39:19] [Render thread/INFO]: [STDERR]: [LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
> [18:39:19] [Render thread/INFO]: [STDERR]: Failed to start Minecraft:
> [18:39:19] [Render thread/INFO]: [STDERR]: java.lang.reflect.InvocationTargetException
> [18:39:19] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> [18:39:19] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
> [18:39:19] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> [18:39:19] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
> [18:39:19] [Render thread/INFO]: [STDERR]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
> [18:39:19] [Render thread/INFO]: [STDERR]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
> [18:39:19] [Render thread/INFO]: [STDERR]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
> [18:39:19] [Render thread/INFO]: [STDERR]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
> [18:39:19] [Render thread/INFO]: [STDERR]: Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
> [18:39:19] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:236)
> [18:39:19] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
> [18:39:19] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
> [18:39:19] [Render thread/INFO]: [STDERR]: 	... 8 more
> [18:39:19] [Render thread/INFO]: [STDERR]: Caused by: java.lang.reflect.InvocationTargetException
> [18:39:19] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> [18:39:19] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
> [18:39:19] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> [18:39:19] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
> [18:39:19] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
> [18:39:19] [Render thread/INFO]: [STDERR]: 	... 10 more
> [18:39:19] [Render thread/INFO]: [STDERR]: Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.mojang.blaze3d.systems.RenderSystem
> [18:39:19] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_6396.method_37123(class_6396.java:65)
> [18:39:19] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_37274(class_310.java:2417)
> [18:39:19] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_22681(class_310.java:2412)
> [18:39:19] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:187)
> [18:39:19] [Render thread/INFO]: [STDERR]: 	... 15 more
> [18:39:19] [Render thread/INFO]: [STDOUT]: Exiting with -1
> Process exited with code 255.
> Clipboard copy at: 13 Jul 2021 18:40:07 -0600
>

**Comment by Zetabite** [comment] 2021-07-14 00:54
Just to make sure, you use it through the compatibility layer, everything else doesnt work and is not supported. Not even M1 is really supported

**Comment by adammbaker** [comment] 2021-07-14 01:01
I understand that MultiMC hasn't been built for M1. I'm using it through Rosetta which converts x86 calls to arm64.

Somewhere in MultiMC it sees my Java installations as 64-bit during the test but still lists them as 32-bit.

**Comment by Zetabite** [comment] 2021-07-14 01:02
Yeah, Rosetta is the layer i meant. I have honestly no idea whats happening here.

**Comment by spannerman79** [comment] 2021-07-14 04:03
Have to wait to see/find out the statue update on https://github.com/MultiMC/MultiMC5/issues/3480#issuecomment-747926533.

**Comment by r58Playz** [comment] 2021-07-15 19:07
If you are using Minecraft without externally compiled natives([my repo for m1 minecraft](https://github.com/r58Playz/m1-multimc-hack)) then Minecraft will crash since you are using arm jvm and x86_64 natives.
MultiMC will show ARM JVMs as 32 bit. 
My setup:
<img width="1401" alt="Screen Shot 2021-07-15 at 12 06 10 PM" src="https://user-images.githubusercontent.com/45221816/125843479-ce18621d-361d-439e-a9f9-9e04f63799a0.png">
(selected one is the jvm i use)

I use my repo for the arm natives.

P.S. sorry for the self promotion

**Comment by phit** [comment] 2021-07-28 10:33
ARM is still not supported by the game or MultiMC, closing as duplicate of https://github.com/MultiMC/MultiMC5/issues/2133 and https://github.com/MultiMC/MultiMC5/issues/3480#issuecomment-747926533

**Closed by phit** 2021-07-28 10:33 UTC
Labels: bug

**Comment by jaknz** [comment] 2022-11-20 23:35
The two issues that were referenced as a reason to close this issue are not related. One has been completely deleted, and the other has been closed due to issues with the Raspberry Pi operating system. Neither of these has anything to do with running an arm64 version.

**Comment by slayernominee** [comment] 2023-05-31 08:28
i have the same issue, is there a solution?

**Comment by phit** [comment] 2023-05-31 08:40
Yes, install x64 java https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java#macos
