### ISSUE TITLE
Added my MC acc then MultiMC crashes at launch

### ISSUE THREAD

**Issue by Fiaegel** [MultiMC/MultiMC5#1724] opened 2016-11-16 11:08 UTC
System Information
-----------------------------
MultiMC version: 0.4.11-751

Operating System: Windows 7 64x

Summary of the issue or suggestion: 
----------------------------------------------
Multimc crashed after I added my mojang account. Attempting to reopen the program causes it to crash each time. Updating/reinstalling Java 32/64 did not fix the issue nor did deleting and reinstalling the program at a different location .

What should happen:
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. 

2.

3.

Suspected cause:
---------------------------
Java 

Logs/Screenshots:
----------------------------
log0 : http://pastebin.com/BEFitPZ0 
screen : http://imgur.com/a/Md1zL

Additional Info:
---------------------------

**Comment by peterix** [comment] 2018-02-14 17:21
Well, that was a long time ago. Sorry about not responding sooner. I am closing this, as the problem is likely gone due to rewrites.

**Closed by peterix** 2018-02-14 17:21 UTC
Labels: multimc: bug
