### ISSUE TITLE
Invalid credentials for a microsoft account

### ISSUE THREAD

**Issue by tomeraz** [MultiMC/MultiMC5#3810] opened 2021-05-25 05:14 UTC
### Operating System

Windows

### Description of bug

Getting "invalid credentials" for a microsoft account with correct username/password.
Any way around this?
Any progress on issue #3392 ?
Thanks!

### Steps to reproduce

Add account using valid microsoft minecraft account credentials.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by spannerman79** [comment] 2021-05-25 05:16
Duplicate of https://github.com/MultiMC/MultiMC5/issues/3392

Don't create an issue when there is already an issue created.

You know that little check box you selected being "I have searched the issue tracker"... well obvious you haven't.

**Comment by kb-1000** [comment] 2021-05-25 06:31
Duplicate of #3392

**Closed by kb-1000** 2021-05-25 06:31 UTC
Labels: bug
