### ISSUE TITLE
Idea for the version list in the instance creation window

### ISSUE THREAD

**Issue by CobaltRogue1998** [MultiMC/MultiMC5#3017] opened 2020-02-26 17:38 UTC
There should be an option in the version list for "Latest Release", "Latest Snapshot" and "Latest Experiment". If this option is used, every time you load the instance it checks for a newer version and automatically updates.

**Comment by spannerman79** [comment] 2020-02-29 08:57
And how would it actually check to see if a mod was updated?
Whos going to maintain (Ie: **pay** for it be it time/money) it if it depends on external API's?

I think you need to do a little more thinking into your idea and at least _some_ research first.

**Comment by CobaltRogue1998** [comment] 2020-02-29 09:06
I think you need to a little more reading because nothing in this post contained the word "**_Mod_**" . I'll have to explain it to you. The post is about a setting to make the instance automatically update to an newer available version of _**Vanilla Minecraft**_. For instance if it's set to use latest version and you are on 1.15.1, it will get 1.15.2 when loading the instance up.

**Comment by spannerman79** [comment] 2020-02-29 09:16
> I think you need to a little more reading because nothing in this post contained the word "**_Mod_**"

Fair enough - anything to do with auto-updating usually ends up in something breaking - especially with minecraft



> The post is about a setting to make the instance automatically update to an newer available version of _**Vanilla Minecraft**_

Ok, I can see cats and dogs living together and fluffy kitten image breaking here.

No way in **hell** would I want something like that.  

Here is just _one_ thing that you need to  do as you quote "I think you need to a little more reading"

- The change from 1.13 flattened nbt file formats - https://minecraft.gamepedia.com/Java_Edition_1.13/Flattening . If this was in place it would force update from 1.12.2 to all through the buggy snapshots etc up to 1.13.  Say goodbye to your world if you are playing modded MC even _if_ forge was a thing for 1.13.

If you wish to move to different MC versions you can do it yourself - you don't need it to "auto update" and break sh!t.

This is why it is normally accepted if you wish to "update to a newer version of MC" you do it yourself knowing **full well** that if it breaks you more or less have bought it and your mistake.

**Comment by CobaltRogue1998** [comment] 2020-02-29 09:35
Well it would not be on by default. The vanilla launcher itself does it by default. I just gave a simple idea that could be turned into something more, it could have had filters, like stay with only point releases etc. Plus since my idea was about not choosing a version number in the first place, that would mean forge, fabric and jar mods would be not selectable and disabled. This would not effect modded. This idea would be great for snapshots since most of us don't even use the vanilla launcher and they show patch notes if a new snapshot is released. Then if this option is selected, you would just get the new snapshot. I would not even expect many people to use this feature. MultiMC just does not have this feature. I don't even have to have this. If there was a popup saying there was a new update for the instance and just give patch notes id be super fine with that.

**Comment by realToadtoad** [comment] 2020-05-24 19:09
Isn't this a duplicate of #87?

**Comment by phit** [comment] 2021-03-09 21:36
Duplicate of https://github.com/MultiMC/MultiMC5/issues/87

**Closed by phit** 2021-03-09 21:36 UTC
