### ISSUE TITLE
A block crashed my world so I removed the mod and now I can’t load my world.

### ISSUE THREAD

**Issue by BlossomPeach65** [MultiMC/MultiMC5#3309] opened 2020-08-23 20:29 UTC
[Crash log](https://paste.ee/p/xoxKq) 
Please help me! I really don’t want my world to be lost forever. The mod was blockcraftery.

**Comment by Janrupf** [comment] 2020-09-09 19:25
Waila or Doubleslabs is causing the crash, or maybe a combination of both.

**Comment by QuImUfu** [comment] 2020-09-10 10:27
duplicate of #3312

**Closed** 2021-02-05 17:42 UTC
