### ISSUE TITLE
Linux binary releases contain too many libraries, causing incompatibility

### ISSUE THREAD

**Issue by DokiTeeX** [MultiMC/MultiMC5#1784] opened 2017-01-15 16:12 UTC
System Information
-----------------------------
MultiMC version: 5

Operating System: Kali Linux 2.0

Summary of the issue or suggestion: Can't log in with my MC Account, when I press "Enter" it says : Unable to init SSL Context: (99)
----------------------------------------------

What should happen: I would login
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Launch MultiMC

2. Try to set an account

3. 

Suspected cause: My OS ? A package missing ?
---------------------------

Logs/Screenshots:
----------------------------

Additional Info: I do not use Kali Linux with bad intentions.
---------------------------

**Comment by peterix** [comment] 2017-01-15 17:26
Kali linux seems to be using OpenSSL built with versioned symbols. I have no idea why they do it, but it makes the library that would otherwise be fine unusable.

You will have to build MultiMC from source:
https://github.com/MultiMC/MultiMC5/blob/develop/BUILD.md

**Comment by peterix** [comment] 2017-01-15 18:15
Alternatively, you could remove the non-MultiMC libraries from MultiMC.

![stuff to keep](https://cdn.discordapp.com/attachments/134843027553255425/270246520949833743/unknown.png "Stuff to keep")

If you keep only these in `bin` and install Qt5 from the system, it could work.

**Comment by QuImUfu** [comment] 2017-01-15 20:28
In my test with the newest Kali linux VirtualBox image from their website and with the newest version of MultiMC everything works fine.
But according to the website this image "may have pre-generated SSH host keys" whatever that means.

**Comment by QuImUfu** [comment] 2017-01-16 12:26
After updating the system i can reproduce.

**Comment by peterix** [comment] 2017-01-16 12:32
Can you make it work by removing all the bundled dependencies and using system libraries instead?

**Comment by QuImUfu** [comment] 2017-01-16 17:54
No, because the libraries are not in the kali debian repository. 
Most of them have only newer versions available.

Building from source does work, in case @DokiTeeX wants me to i can upload a working Kali Linux build.
But he has to be aware that updating to a newer version will break MMC if he uses that build.

**Comment by peterix** [comment] 2017-01-16 18:00
It should work with newer versions. I can run MultiMC this way - it is built with Qt 5.4 and my system has Qt 5.7.

**Comment by QuImUfu** [comment] 2017-01-16 18:26
Oh, found a better fix than building a custom build:
Remove the libraries with qt5 and the libstdc++.so.6 file and it works.

**Comment by AriaanBruinsma** [comment] 2019-06-05 05:28
Duplicate of #1784

**Comment by inkyfingers** [comment] 2019-06-22 23:38
I reviewed several of the above linked posts when I was asked to help with MultiMC on Debian 9.

I believe that this is a Debian openssl issue. Please see Debian release notes:

https://www.debian.org/releases/stable/amd64/release-notes/ch-information.en.html#openssl-issues

Does MultiMC use OpenSSL 1.0.2? <code>libssl1.0-dev</code> provides headers against OpenSSL 1.0.2. 

System Information
-----------------------------

MultiMC version: 0.6.5-1217

Operating System: Debian 9

Instance: fabric-1.14.2-build.7_yarn-0.4.8-build.155/fabric-1.14.2-build.7_yarn-0.4.8-build.155


Steps to reproduce the issue 
---------------------------------------

Launch MultiMC on Debian 9, the launcher window appears but was not yet fully loaded, for instance no languages, no version number showing, 4 red status buttons on bottom right of launcher screen, no active error console.

I could not log in to a profile with console error message implying no secure connection.

The terminal log had masses of "Unable to init SSL Context:" and several "Authentication operation failed due to a network error: Unable to init SSL Context:  (99)"

Then <code>apt-get install libssl1.0-dev</code> and the launcher works and minecraft starts.

I recognise that I am proposing a "fix" that has been dismissed in the past. It would be interesting to know if those who have successfully compiled MultiMC for Debian 9 have <code>libssl1.0-dev</code> on their system.

**Comment by peterix** [comment] 2019-06-22 23:52
The next stable release will not include Qt... and this problem will go away. But you will have to install Qt 5.4  or newer.

**Comment by peterix** [comment] 2019-06-22 23:53
And yes, the `-dev` package has the required `.so` file symlink.

Really, it's a bug in Qt's ssl integration, because it looks for the non-versioned `.so` file, where it should be looking for the one with the ABI version in it.

**Comment by inkyfingers** [comment] 2019-06-23 10:54
@peterix thank you for your reply and for not rebuking me for suggesting an insecure hack.

I now see why the removal of the non-MultiMC libraries and plugins from MultiMC is a proper fix.

I have done that and confirm the method worked on Debiam 9 today.

Further I see that the difference between <code>mmc-stable-lin64.tar.gz</code> and <code>mmc-develop-lin64.tar.gz</code>, today, (both available from the https://multimc.org/ page) is simply that the troublesome library files have already been stripped out.

Thank you.

**Comment by peterix** [comment] 2019-07-10 21:36
Resolving as fixed.

**Closed by peterix** 2019-07-10 21:36 UTC
Labels: multimc: bug, system: Linux
