### ISSUE TITLE
Truncation of text in configs by '#': it should be escaped when writing strings

### ISSUE THREAD

**Issue by uncleankiwi** [MultiMC/MultiMC5#1813] opened 2017-02-03 18:35 UTC
System Information
-----------------------------
MultiMC version: 0.5.0 build 929 

Operating System: Windows 7 SP 1

Summary of the issue or suggestion:
----------------------------------------------
Entering a pound (#) sign in the notes and restarting MultiMC causes the # sign and everything after it to be deleted.

Reproducible.

What should happen:
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by Querela** [comment] 2018-02-25 22:02
Hello,
I'm using MultiMC 0.6.1-1177 win32 and the truncating still happens. I'm not sure if it was fixed because this ticket seems to still be open and the issue is obviously occuring for me.

The issue happens like this:
1. write notes, can do anything with MultiMC,
2. after closing MultiMC the note is still stored in the instance.cfg file
3. reopening MultiMC doesn't change anything with the config
4. opening the note of the instance only displays the truncated note
-> note in instance.cfg still okay
5. closing the note in the gui (therefore saving it) -> will save this (truncated) displayed note to the config file

-> issue therefore seems to occur when parsing/displaying the note from the instance.cfg file to the gui
-> maybe the escaping when **saving** doesn't happen? `#` is stored as is in my file, on opening it will vanish?

my example note:
`notes=\nMODS\n====\n\n------------------------------------------------------------------------------------------\n\n#<everyting vanishes>`

**Closed** 2019-06-19 23:56 UTC
Labels: multimc: bug
