### ISSUE TITLE
Networking error: "Unable to init SSL Context"

### ISSUE THREAD

**Issue by faceless-saint** [MultiMC/MultiMC5#1992] opened 2017-09-15 14:14 UTC
System Information
-----------------------------
MultiMC version: **0.5.0-887**

Operating System: **Debian Stretch (amd64)**

Summary of the issue or suggestion:
----------------------------------------------
List of Minecraft versions will not update. The following error appears in the log:
```
W QSslSocket: cannot call unresolved function SSLv23_client_method
W QSslSocket: cannot call unresolved function SSL_library_init
C Task failed:  "Failed to load Minecraft main version listUnable to init SSL Context: "
```
Attempting to authenticate an account fails with an equivalent error.

What should happen:
------------------------------
The version list is fetched successfully, or the Mojang account is authenticated.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Install the given version of MultiMC to an up-to-date Debian Stretch install.
      * The error above is captured from an install using the "Generic (x64-bit) Linux binary"
      * The Ubuntu package was also attempted with an identical error 
2. Create a new instance.
3. The error will appear when MultiMC attempts to initialize the version list.
4. Alternatively, attempt to create a new account. The same error will appear upon initial login.

Suspected cause:
---------------------------
Undocumented missing runtime dependency, or a broken Linux build. As a troubleshooting measure I installed all Linux build dependencies, is the event that one of them was also a runtime dependency, but this did not resolve the issue.

Logs/Screenshots:
----------------------------
The full MultiMC log is as follows:
```
0.000 D MultiMC 5, (c) 2013-2017 MultiMC Contributors
    0.000 D Version                    :  "0.5.0-887"
    0.001 D Git commit                 :  "aafac3934b9887ced77c9f5b3d6be988af06dbf0"
    0.001 D Git refspec                :  "refs/heads/stable"
    0.001 D Work dir before adjustment :  "/home/ryclarke/Downloads"
    0.001 D Work dir after adjustment  :  "/usr/local/MultiMC"
    0.001 D Adjusted by                :  "Command line /usr/local/MultiMC"
    0.001 D Binary path                :  "/usr/local/MultiMC/bin"
    0.001 D Application root path      :  "/usr/local/MultiMC"
    0.011 D Detected default console font: "DejaVu Sans Mono" , substitutions: ""
    0.015 D FTB Launcher paths: "/home/ryclarke/.ftblauncher" and "/home/ryclarke/.ftblauncher"
    0.015 D Attempting to read "/home/ryclarke/.ftblauncher/ftblaunch.cfg"
    0.015 W Couldn't open "/home/ryclarke/.ftblauncher/ftblaunch.cfg" : "No such file or directory"
    0.015 W This is perfectly normal if you don't have FTB installed
    0.015 D Your language is "en"
    0.016 D Started watching  "/usr/local/MultiMC/icons"
    0.016 W ""
    0.016 D Loading theme "custom"
    0.016 D Loading builtin version list.
    0.017 W Blacklisted legacy version ignored:  "rd-160052"
    0.017 D Instance path              :  "instances"
    0.017 D Loading Instances...
    0.017 D Loading accounts...
    0.017 C "Failed to read the account list file (accounts.json)."
    0.018 D Detecting proxy settings...
    0.018 D Using no proxy is an option!
    0.018 D Downloading Translations Index...
    0.018 D "Translations Index"  started.
    0.018 D Analytics disabled by user.
    0.050 W QMetaObject::connectSlotsByName: No matching signal for on_actionDeleteGroup_triggered()
    0.052 D "Status JSON"  started.
    0.079 W QSslSocket: cannot resolve CRYPTO_num_locks
    0.079 W QSslSocket: cannot resolve CRYPTO_set_id_callback
    0.079 W QSslSocket: cannot resolve CRYPTO_set_locking_callback
    0.079 W QSslSocket: cannot resolve ERR_free_strings
    0.079 W QSslSocket: cannot resolve sk_new_null
    0.079 W QSslSocket: cannot resolve sk_push
    0.079 W QSslSocket: cannot resolve sk_free
    0.079 W QSslSocket: cannot resolve sk_num
    0.079 W QSslSocket: cannot resolve sk_pop_free
    0.079 W QSslSocket: cannot resolve sk_value
    0.080 W QSslSocket: cannot resolve SSL_library_init
    0.080 W QSslSocket: cannot resolve SSL_load_error_strings
    0.080 W QSslSocket: cannot resolve SSLv3_client_method
    0.080 W QSslSocket: cannot resolve SSLv23_client_method
    0.080 W QSslSocket: cannot resolve SSLv3_server_method
    0.080 W QSslSocket: cannot resolve SSLv23_server_method
    0.080 W QSslSocket: cannot resolve X509_STORE_CTX_get_chain
    0.080 W QSslSocket: cannot resolve OPENSSL_add_all_algorithms_noconf
    0.080 W QSslSocket: cannot resolve OPENSSL_add_all_algorithms_conf
    0.080 W QSslSocket: cannot resolve SSLeay
    0.080 W QSslSocket: cannot resolve SSLeay_version
    0.080 W QSslSocket: cannot call unresolved function CRYPTO_num_locks
    0.080 W QSslSocket: cannot call unresolved function CRYPTO_set_id_callback
    0.080 W QSslSocket: cannot call unresolved function CRYPTO_set_locking_callback
    0.080 W QSslSocket: cannot call unresolved function SSL_library_init
    0.080 W QSslSocket: cannot call unresolved function SSLv23_client_method
    0.081 W QSslSocket: cannot call unresolved function sk_num
    0.082 D Downloading LWJGL RSS...
    0.082 D "LWJGL RSS"  started.
    0.082 D Reloading news.
    0.082 D "News RSS Feed"  started.
    0.082 D Checking for updates.
    0.082 D Channel list isn't loaded yet. Loading channel list and deferring update check.
    0.082 D Loading the channel list.
    0.082 D "Update System Channel List"  started.
    0.082 D "Checking for notifications"  started.
    0.116 D Viewport size "694x563"
    0.116 D RAM size is 3952 MB
    0.116 D [Analytics] "ScreenView: Main Window"
    0.116 D "Translations Index" succeeded.
    0.116 D Task succeeded
    0.116 D Got translations index!
    0.116 D Download cache hit  "http://files.multimc.org/translations/index"
    0.117 D Downloading  "http://status.mojang.com/check"
    0.117 D Downloading  "https://sourceforge.net/projects/java-game-lib/rss"
    0.117 D Downloading  "http://multimc.org/rss.xml"
    0.117 D Downloading  "http://files.multimc.org/update/lin64/channels.json"
    0.118 D Downloading  "http://files.multimc.org/notifications.json"
    0.323 W QSslSocket: cannot call unresolved function SSLv23_client_method
    0.323 W QSslSocket: cannot call unresolved function SSL_library_init
    0.324 C Failed  "https://sourceforge.net/projects/java-game-lib/rss"  with reason  99
    0.324 D Download failed in previous step: "https://sourceforge.net/projects/java-game-lib/rss"
    0.324 D Downloading  "https://sourceforge.net/projects/java-game-lib/rss"
    0.426 W QSslSocket: cannot call unresolved function SSLv23_client_method
    0.427 W QSslSocket: cannot call unresolved function SSL_library_init
    0.427 C Task failed:  "Failed to load Minecraft main version listUnable to init SSL Context: "
    0.531 W QSslSocket: cannot call unresolved function SSLv23_client_method
    0.531 W QSslSocket: cannot call unresolved function SSL_library_init
    0.531 C Failed  "https://sourceforge.net/projects/java-game-lib/rss"  with reason  99
    0.531 D Download failed in previous step: "https://sourceforge.net/projects/java-game-lib/rss"
    0.531 D Downloading  "https://sourceforge.net/projects/java-game-lib/rss"
    0.948 D Following redirect to  "https://multimc.org/rss.xml"
    0.949 D Downloading  "https://multimc.org/rss.xml"
    0.949 D Download redirected: "https://multimc.org/rss.xml"
    0.950 D Download succeeded: "http://status.mojang.com/check"
    0.950 D "Status JSON" succeeded.
    0.951 D Task succeeded
    0.951 D Finished loading status JSON.
    0.952 D Status loading succeeded.
    1.052 W QSslSocket: cannot call unresolved function SSLv23_client_method
    1.052 W QSslSocket: cannot call unresolved function SSL_library_init
    1.052 D Download succeeded: "http://files.multimc.org/update/lin64/channels.json"
    1.052 D "Update System Channel List" succeeded.
    1.053 D Task succeeded
    1.053 D Successfully loaded UpdateChecker channel list.
    1.053 D Checking for updates.
    1.053 D m_repoUrl =  "http://files.multimc.org/update/lin64/stable/"
    1.053 D "GoUpdate Repository Index"  started.
    1.053 C Failed  "https://sourceforge.net/projects/java-game-lib/rss"  with reason  99
    1.053 D Download failed in previous step: "https://sourceforge.net/projects/java-game-lib/rss"
    1.053 D Downloading  "https://sourceforge.net/projects/java-game-lib/rss"
    1.053 D Downloading  "http://files.multimc.org/update/lin64/stable/index.json"
    1.155 W QSslSocket: cannot call unresolved function SSLv23_client_method
    1.155 W QSslSocket: cannot call unresolved function SSL_library_init
    1.259 W QSslSocket: cannot call unresolved function SSLv23_client_method
    1.259 W QSslSocket: cannot call unresolved function SSL_library_init
    1.259 W QSslSocket: cannot call unresolved function SSLv23_client_method
    1.259 W QSslSocket: cannot call unresolved function SSL_library_init
    1.260 C Failed  "https://sourceforge.net/projects/java-game-lib/rss"  with reason  99
    1.260 D Download failed in previous step: "https://sourceforge.net/projects/java-game-lib/rss"
    1.260 C "LWJGL RSS" failed.
    1.260 C Task failed:  "Job 'LWJGL RSS' failed to process:
https://sourceforge.net/projects/java-game-lib/rss"
    1.260 W "Failed to load LWJGL list. Network error: Job 'LWJGL RSS' failed to process:
https://sourceforge.net/projects/java-game-lib/rss"
    1.260 C Failed  "https://multimc.org/rss.xml"  with reason  99
    1.260 D Download failed in previous step: "https://multimc.org/rss.xml"
    1.260 D Downloading  "https://multimc.org/rss.xml"
    1.362 W QSslSocket: cannot call unresolved function SSLv23_client_method
    1.363 W QSslSocket: cannot call unresolved function SSL_library_init
    1.363 C Failed  "https://multimc.org/rss.xml"  with reason  99
    1.363 D Download failed in previous step: "https://multimc.org/rss.xml"
    1.363 D Downloading  "https://multimc.org/rss.xml"
    1.467 W QSslSocket: cannot call unresolved function SSLv23_client_method
    1.467 W QSslSocket: cannot call unresolved function SSL_library_init
    1.468 C Failed  "https://multimc.org/rss.xml"  with reason  99
    1.468 D Download failed in previous step: "https://multimc.org/rss.xml"
    1.468 D Downloading  "https://multimc.org/rss.xml"
    1.468 D Download succeeded: "http://files.multimc.org/notifications.json"
    1.472 D "Checking for notifications" succeeded.
    1.472 D Task succeeded
    1.779 W QSslSocket: cannot call unresolved function SSLv23_client_method
    1.780 W QSslSocket: cannot call unresolved function SSL_library_init
    1.781 C Failed  "https://multimc.org/rss.xml"  with reason  99
    1.782 D Download failed in previous step: "https://multimc.org/rss.xml"
    1.782 C "News RSS Feed" failed.
    1.782 C Task failed:  "Job 'News RSS Feed' failed to process:
https://multimc.org/rss.xml"
    1.782 D Failed to load news: "Failed to load news RSS feed:
Job 'News RSS Feed' failed to process:
https://multimc.org/rss.xml"
    1.784 D Download succeeded: "http://files.multimc.org/update/lin64/stable/index.json"
    1.784 D "GoUpdate Repository Index" succeeded.
    1.784 D Task succeeded
    1.784 D Finished downloading repo index. Checking for new versions.
    1.785 D Processing repository version list.
    7.500 W QSslSocket: cannot call unresolved function SSLv23_client_method
    7.501 W QSslSocket: cannot call unresolved function SSL_library_init
    7.501 C Task failed:  "Failed to load Minecraft main version listUnable to init SSL Context: "
   31.008 D "Patreon Patron List"  started.
   31.017 D Downloading  "http://files.multimc.org/patrons.txt"
   31.628 D Download succeeded: "http://files.multimc.org/patrons.txt"
   31.629 D "Patreon Patron List" succeeded.
   31.629 D Task succeeded
   53.212 D Selected index 0 channel id "stable"
   60.419 D "Status JSON"  started.
   60.420 D Downloading  "http://status.mojang.com/check"
   60.956 D Download succeeded: "http://status.mojang.com/check"
   60.956 D "Status JSON" succeeded.
   60.956 D Task succeeded
   60.957 D Finished loading status JSON.
   60.957 D Status loading succeeded.
  101.066 D Paged dialog close requested
  101.066 D Analytics disabled by user.
  101.066 D Paged dialog close approved
  101.067 D Paged dialog geometry saved
  103.570 D Opening URL "https://github.com/MultiMC/MultiMC5/issues"
  120.419 D "Status JSON"  started.
  120.420 D Downloading  "http://status.mojang.com/check"
  120.859 D Download succeeded: "http://status.mojang.com/check"
  120.860 D "Status JSON" succeeded.
  120.860 D Task succeeded
  120.860 D Finished loading status JSON.
  120.861 D Status loading succeeded.
  132.403 W QSslSocket: cannot call unresolved function SSLv23_client_method
  132.403 W QSslSocket: cannot call unresolved function SSL_library_init
  132.404 C Task failed:  "Failed to load Minecraft main version listUnable to init SSL Context: "
```

**Comment by QuImUfu** [comment] 2017-09-17 20:53
Seems to be another duplicate of #1784 
Worked around by removing/moving every library (.so) in the bin subfolder except the ones starting with libMultiMC_ and libxcb-sync.
This forces MMC to use your system libraries which are working properly with new versions of OpenSSL.

**Comment by peterix** [comment] 2017-09-17 20:57
Also remove the plugins folder if you are removing the libraries.

**Comment by janagyjr** [comment] 2019-01-06 23:46
confirm this issue still exists with the 1.2-1.deb installer on Debian 9 amd64, cannot confirm the workaround is working.

**Comment by QuImUfu** [comment] 2019-01-07 20:00
```
sudo apt-file find libQt5Xml
```
or https://packages.debian.org/  
will help you find the dependencies you are missing. Install them.
as said:  
This forces MMC to use your system libraries.  
If these libraries are not installed it will (of curse) not run.

**Comment by janagyjr** [comment] 2019-01-07 20:08
```sudo apt search libQt5Xml```

ftfy, and thank you.

**Comment by mozai** [comment] 2019-04-20 00:09
Ubuntu 19.04
Running ./bin/MultiMC gets me `This application failed to start because it could not find or load the Qt platform plugin "xcb".`  Running ./MultiMC launches the window but stderr has the 

```
    0.450 W QSslSocket: cannot call unresolved function CRYPTO_num_locks
    0.450 W QSslSocket: cannot call unresolved function CRYPTO_set_id_callback
    0.450 W QSslSocket: cannot call unresolved function CRYPTO_set_locking_callback
    0.450 W QSslSocket: cannot call unresolved function SSL_library_init
    0.450 W QSslSocket: cannot call unresolved function SSLv23_client_method
    0.452 W QSslSocket: cannot call unresolved function sk_num
```

libssl1.0-dev is fully deprecated, no longer available.  I already have libQt5Xml 5.12.2 installed.
I moved all the ./bin/libQt5*.so.5 files and ./bin/libxcb-*.so.? files somewhere else, launched ./MultiMC , and it was able to access the internet again; only warning was: `QMetaObject::connectSlotsByName: No matching signal for on_actionInstanceSettings_triggered()`

**Comment by mozai** [comment] 2019-06-02 02:11
Upgraded MultiMC today, had to find this issue again to remember how to re-remove the deprecated library files.

**Comment by mozai** [comment] 2019-06-11 13:00
Latest upgrade 0.6.5-develop-1229 did not reproduce the error, I did not need to re-remove the deprecated library files.

**Comment by phit** [comment] 2019-06-11 13:14
they were removed in https://github.com/MultiMC/MultiMC5/commit/86850ef5d0195fb022cda7481b43496da722911c

**Comment by peterix** [comment] 2019-06-11 13:15
Yeah, I just need to update the `.deb` file and make a stable release where the requirement for installing Qt is described in the changelog.

**Comment by fluffynuts** [comment] 2019-07-01 16:11
I just installed from the .deb and hit this -- at least I could fix from the information here. Please update the public-facing deb to avoid sadness in others )':

**Comment by peterix** [comment] 2019-07-10 21:34
Resolving as fixed, will be in stable release later today.

**Closed by peterix** 2019-07-10 21:34 UTC
Labels: multimc: bug, system: Linux
