### ISSUE TITLE
Forge not installing on 1.9.4

### ISSUE THREAD

**Issue by BaccarWozat** [MultiMC/MultiMC5#1574] opened 2016-05-18 23:25 UTC
System Information
-----------------------------
MultiMC version: 0.4.11-751 on win32

Operating System: Windows 7 64-bit

Summary of the issue or suggestion:
----------------------------------------------
Forge recently released for 1.9.4. Versions 12.16.1.1908 and 1909 are available, but neither one installs in my 1.9.4 instance. The "Installing Forge" popup appears for about 1/10 of a second, then Forge doesn't appear under LWJGL in the list. When Play is clicked on, it just runs vanilla 1.9.4 with no Forge.

What should happen:
------------------------------
Forge should be installed and should run under 1.9.4.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Start an instance with 1.9.4.

2. Edit Instance -> Install Forge -> Forge 12.16.1.1909 -> OK

3. Close window and click Play.

Suspected cause:
---------------------------
Maybe the changes to Mojang's 1.9 file download locations has introduced a new bug wherein Forge files don't load?

Logs/Screenshots:
----------------------------
![1 9 4](https://cloud.githubusercontent.com/assets/8357501/15378048/bdaa52b6-1d25-11e6-94de-b8d72e01eeea.jpg)

**Comment by QuImUfu** [comment] 2016-05-19 00:22
I think this error is caused by forge for 1.9.4 not being downloadable, not even on their own website, so MultiMC can't download it and fails silently.
[MMC.log] (https://paste.ee/p/ZKgER)

**Comment by QuImUfu** [comment] 2016-05-19 07:57
This is now fixed on forges side.
Works in MMC.

**Closed** 2016-05-19 08:44 UTC
Labels: external
