### ISSUE TITLE
microsoft account

### ISSUE THREAD

**Issue by Emayeah** [MultiMC/MultiMC5#3802] opened 2021-05-21 08:28 UTC
### Role

i play old versions

### Suggestion

add microsoft registration

### Benefit

because i do not have a mojang account

### This suggestion is unique

- [x] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by Janrupf** [comment] 2021-05-21 08:30
See #3392, indirect duplicate

**Comment by kb-1000** [comment] 2021-05-21 08:37
Duplicate of #3392

**Closed by kb-1000** 2021-05-21 08:37 UTC
