### ISSUE TITLE
Tried to add instance from already downloaded zip, Multimc tried to 'download' it, hung near completion, couldn't abort at any point

### ISSUE THREAD

**Issue by Githerax** [MultiMC/MultiMC5#3032] opened 2020-03-14 14:53 UTC
System Information
-----------------------------
MultiMC version: 0.6.8-1419

Operating System: Win 10 Home

Summary of the issue or suggestion:
----------------------------------------------
Tried to add instance by importing from zip:
1.  It started a 'downloading' progress bar
 a.  The bar could not be aborted or closed at any point
2.  It hung near the end of "downloading" an already-downloaded zip

What should happen:
------------------------------
Importing from a zip should unzip and install

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. download a single-player modpack zip from Curse

2. attempt to add instance from zip

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------
There is no log file because the program doesn't understand it failed

Additional Info:
---------------------------

**Comment by wlhlm** [comment] 2020-03-14 18:42
Duplicate of #1949.

**Comment by Forkk** [comment] 2021-03-07 18:50
Duplicate of #1949

**Closed by Forkk** 2021-03-07 18:50 UTC
