### ISSUE TITLE
Option to hide Instance Icon in corner

### ISSUE THREAD

**Issue by HeroCC** [MultiMC/MultiMC5#733] opened 2015-01-17 20:38 UTC
Hello!
I use Ubuntu, and because our buttons are in the Top Left, the instance hides the 'X' button. Can you make a feature that disables this per-instance? 
Thanks!

**Comment by 02JanDal** [comment] 2015-01-17 20:39
Duplicate of #403

**Closed by 02JanDal** 2015-01-17 20:39 UTC
