### ISSUE TITLE
Unicode characters from Minecraft log turn into ? in MultiMC's log

### ISSUE THREAD

**Issue by TheBlueKingLP** [MultiMC/MultiMC5#1805] opened 2017-01-28 18:22 UTC
at the console,all unicode and chinese turned to a question mark(?),how to fix it?

**Comment by peterix** [comment] 2017-01-28 19:35
What console?

**Comment by peterix** [comment] 2017-01-28 19:39
![image](https://cloud.githubusercontent.com/assets/203326/22399285/d0733164-e599-11e6-9687-94567059f06a.png)

**Comment by QuImUfu** [comment] 2017-01-28 21:50
Can reproduce the problem on Windows 7 but it does work fine on Lubuntu.
Seems to be a Windows specific issue.

**Comment by brodycas3** [comment] 2017-01-28 22:03
Can confirm for win 10

**Comment by peterix** [comment] 2017-01-29 02:40
Well, any sort of process output on Windows will be limited to the system ANSI codepage. Which sucks. And not much can be done about it.

**Comment by phit** [comment] 2021-03-09 21:57
Closing in favor of the newer https://github.com/MultiMC/MultiMC5/issues/2513

**Closed by phit** 2021-03-09 21:57 UTC
Labels: bug
