### ISSUE TITLE
[Suggestion] Add a warning when using large icons ( Crash when trying to Edit Instance with specific large Icon set for modpack)

### ISSUE THREAD

**Issue by BlazingPL** [MultiMC/MultiMC5#3223] opened 2020-06-29 16:57 UTC
System Information
-----------------------------
MultiMC version: 0.6.11-custom (AUR multimc5)

Operating System: Arch linux (linux-ck 5.6.15-1)

Summary of the issue or suggestion: 
----------------------------------------------
I use icons from curseforge modpack icon. When using icon for https://www.curseforge.com/minecraft/modpacks/ragnamod-v for this modpack in MultiMC and click Edit Instance, it crashes instantly. This does not happen with other modpacks/icons.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Download and install from zip https://www.curseforge.com/minecraft/modpacks/ragnamod-v/files/2878138

2. Download Icon from the same page ( right click icon in upper-right corner , Save image as...) and apply it 

3. Click Edit Instance - MultiMC instantly crashes

Suspected Cause:
----------------------
Large png file (8MB) .

Logs/Screenshots:
---------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
[MultiMC-0.log](https://github.com/MultiMC/MultiMC5/files/4846908/MultiMC-0.log)
[MultiMC-1.log](https://github.com/MultiMC/MultiMC5/files/4846909/MultiMC-1.log)
[MultiMC-2.log](https://github.com/MultiMC/MultiMC5/files/4846910/MultiMC-2.log)
[MultiMC-3.log](https://github.com/MultiMC/MultiMC5/files/4846911/MultiMC-3.log)
[MultiMC-4.log](https://github.com/MultiMC/MultiMC5/files/4846912/MultiMC-4.log)

Icon:
![rag](https://user-images.githubusercontent.com/25771200/86033892-fa17fe00-ba39-11ea-8818-babde7af8ef4.png)

**Comment by Zetabite** [comment] 2020-06-29 17:01
Thats intended, as some components cant work properly with large scale icons. Icons shouldnt be that large anyways, as you can barely see the details. I recommend scaling it down 128 and lower.

**Comment by BlazingPL** [comment] 2020-06-29 17:03
Right, so I suggest to make a warning or reject the icon instead of random crash as you browse the options.

**Comment by QuImUfu** [comment] 2020-06-30 02:58
Seems to be a duplicate of  #2811

**Comment by Forkk** [comment] 2021-03-07 15:32
Duplicate of #2811

**Closed by Forkk** 2021-03-07 15:32 UTC
