### ISSUE TITLE
Simultaneous instances and account+instance integration

### ISSUE THREAD

**Issue by mr2013** [MultiMC/MultiMC5#1185] opened 2015-08-14 17:40 UTC
There appears to not actually be a way to run multiple instances of MC at the same time through this launcher, nor tie an account to an instance. A possible use case is that a modded client connects and crafts while the other connects with a different account to the same server, with a time lapse recording setup. Could I possibly put in a request for these features?

Apologies if this is a duplicate request, no relevant results came up searching for concurrent, simultaneous, or account.

**Comment by 02JanDal** [comment] 2015-08-14 17:45
Default account per instance: #209 (TL;DR: will not be added)
Running multiple instances simultaneously: #338 (TL;DR: will be added at some point)

Duplicate of those issues, closing. (don't feel bad for not finding them, it helps to know what you're searching for)

**Closed by 02JanDal** 2015-08-14 17:45 UTC

**Comment by mr2013** [comment] 2015-08-14 18:02
Awesome, and thank you for your assistance and great software
