### ISSUE TITLE
Console window can't fit the screen and can't be resied to smaller.

### ISSUE THREAD

**Issue by Rencer** [MultiMC/MultiMC5#2330] opened 2018-07-03 12:16 UTC
System Information
-----------------------------
MultiMC version: 0.6.2-custom (Build from AUR)

Operating System: 64 bit Manjaro Linux 17.1.11

Summary of the issue:
---------------------------------
The laptop that I using now, has the maximum resolution of 1366*768.
When I tried to change the configurations of an instance the consol window that opens up, vertically is too large.
The button that change between fullscreen and windowed, when I clicked on it, nothing happens. Than I tried to change the window size manually and it turned out, it is possible to cahnge only horizontally, but not vertically. The consol window can't fit the screen so all the buttons at the bottom are out of the screen.
The settings window of MultiMC itself is not affected by this "bug". It can be resized in any direction, and the fullscreen/windowed button works too.

**Comment by MineBartekSA** [comment] 2018-07-26 12:53
Same issue with my Elementary OS 0.4.1 Loki on the same resolution.

**Comment by peterix** [comment] 2018-11-01 01:47
Duplicate of #358

**Closed by peterix** 2018-11-01 01:47 UTC
