### ISSUE TITLE
Cannot run MultiMC application

### ISSUE THREAD

**Issue by usamahhoosen** [MultiMC/MultiMC5#2005] opened 2017-09-27 16:45 UTC
System Information
-----------------------------
MultiMC version:

Operating System: Windows 10

Summary of the issue or suggestion:
----------------------------------------------
After extracting the MultiMC zip to my desktop and opening it. I tried to run the multimc.exe application and got the following error in a dialog box.

"MultiMC couldn't create a log file - the MultiMC data folder is not writable.

Make sure you have write permissions to the MultiMC data folder.

MultiMC cannot continue until you fix this problem."

What should happen:
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Extract zip file to desktop

2. Open the folder

3. Try to run multimc.exe

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by peterix** [comment] 2017-09-27 17:55
Duplicate of #2004

**Closed by peterix** 2017-09-27 17:55 UTC
Labels: gubbins
