### ISSUE TITLE
macOS Dark Mode Support

### ISSUE THREAD

**Issue by SpacePuppeh** [MultiMC/MultiMC5#3040] opened 2020-03-19 05:25 UTC
System Information
-----------------------------
MultiMC version:
0.6.8-1359
Operating System:
macOS Catalina
Summary of the issue or suggestion:
----------------------------------------------
I am requesting dark mode to be supported on macOS. Currently, it does not auto-change the theme depending upon the system theme. Also, the title bar *even in dark mode* remains in light mode, causing unsightly contrast to the theme.

What should happen:
------------------------------
The theme should change to dark mode, including the title bar, when the system changes its theme settings.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.

2.

3.

Suspected cause:
---------------------------
Lack of support.

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------
Please add this :)

**Comment by Chew** [comment] 2020-03-26 21:38
Duplicate of #2442

**Closed** 2020-08-10 19:40 UTC
