### ISSUE TITLE
Feature Request: Installing Mods from curseforge using api

### ISSUE THREAD

**Issue by mantikafasi** [MultiMC/MultiMC5#3779] opened 2021-05-10 20:17 UTC
Installing mods and dependencies from curseforge website is too much time consuming and boring especially if you're making a modpack so Can you guys add a feature to download mods from launcher

**Comment by jotoho** [comment] 2021-05-10 21:27
Duplicate of #3761 (and probably a lot of others.)

The issue template is there for a reason. Please use it next time and do a brief scan if your suggestion or bugreport already exists in the issue tracker before you create a new one.

**Closed** 2021-05-10 21:38 UTC
