### ISSUE TITLE
Ability to specify an account for an instance

### ISSUE THREAD

**Issue by xenoflot** [MultiMC/MultiMC5#3411] opened 2020-11-01 23:43 UTC
Hi, this is a feature request, not a bug report.

I have 3 MC accounts and they're all registered with the launcher. I have three identical instances and at the moment I'm using the account selector to switch between them when I fire up each instance. It would be nice if I could specify an account in the instance options, thus streamlining the process of getting started for the day.

Thanks!

**Comment by peterix** [comment] 2020-11-01 23:48
If you are doing that all the time, maybe just select no default account at all. It will ask you when you start an instance.

**Comment by KonoTyran** [comment] 2020-11-02 01:57
I would love to see this. as I'm in the same boat being able to specify in the instance settings a "default" account to use would be awesome.

**Comment by xenoflot** [comment] 2020-11-02 07:35
Absolutely a trivial issue but still a nice to have if/when you're bored :) Thanks for the suggestion, I've deselected the default.

**Comment by NanoTrasen-Inc** [comment] 2020-11-14 02:12
Came looking to see if this was possible. I second this.

**Comment by NanoTrasen-Inc** [comment] 2020-11-14 02:14
Appears to be related (or duplicate of) #3116

**Comment by jamesonknutson** [comment] 2020-12-28 20:47
My apologies if this is considered faux pas.

I would very much like it if this feature was implemented into the launcher.

I am setting a bounty of $100.00 USD via PayPal or BTC for any developer who successfully implements this feature and has it pushed live to an official release. I will submit payment once the feature is live in a release that I can use.

If you implement this feature and would like to collect this bounty, please reach out to me via your choice of:

Telegram: @Blitzkrieg
Email: james@coincartel.io

**Comment by xenoflot** [comment] 2020-12-28 23:26
Very generous, James! 

Not sure if pings work in github but worth bringing this offer to the attention of @peterix

**Comment by jamesonknutson** [comment] 2021-03-05 23:08
@peterix I hate to double tag, but in the event that you haven't seen this yet, this is just a gentle notification that I am offering a cash bounty for the feature requested here to be added. Please don't take this the wrong way, this is by no means a demand or a proposition, just want to try and make sure that a feature I really want added has the potential to be added :)

**Comment by HeySteets** [comment] 2021-04-07 02:16
Hello!

I just spoke with @jamesonknutson over Discord -- they're developing a hacky workaround in Node, but it's by no means a full integration with MultiMC. I don't know a lick of C++, but I'd really like to see this feature implemented. 
I'll offer another $25 on top of the bounty they offered earlier, plus another donation to the maintainers directly. If anybody decides to take us up on this offer, I'd be more than happy to work with whoever develops this feature should they need a QA tester or rubber duck.

Thank you!

**Comment by peterix** [comment] 2021-04-07 09:09
OK. That is enough.

Money will never be a factor in MultiMC development. I will not accept something just because you are trying to give me money.

This is now closed and rejected.

**Closed by peterix** 2021-04-07 09:09 UTC
Labels: suggestion
