### ISSUE TITLE
Beta 1.8/1.8.1 Resources (Sounds) don't fully download

### ISSUE THREAD

**Issue by warestarstuff** [MultiMC/MultiMC5#2151] opened 2018-02-17 08:38 UTC
System Information
-----------------------------
MultiMC version: 0.61-1177

Operating System: Windows 10 (32bit)

Summary of the issue or suggestion:
----------------------------------------------
When downloading beta 1.8.1, only the resources "newsound" folder gets downloaded in the instance's folder.

What should happen:
------------------------------
All required resources (sounds) for the version should be in "resources/", such as the sound when the menu clicks and many others.

Steps to reproduce the issue
-------------------------------------------------------------
1. Download Beta 1.8.1 OR Beta 1.8 in MultiMC

2. Look at the instance's resources folder, optionally simply play the game and see whats missing.

Suspected cause:
---------------------------
N/A

Logs/Screenshots:
----------------------------
https://i.imgur.com/fQM6X2z.png

Additional Info:
---------------------------
Beta 1.8 has the same ordeal, but even LESS sounds get downloaded!

**Comment by peterix** [comment] 2018-02-18 20:13
That is between the game and the Mojang servers... If the files are no longer there, these old versions will be without sound.

**Comment by pyrestriker** [comment] 2018-03-08 23:20
The sounds do exist, just in a different location now. Using the regular client, b1.8.1 downloads with sounds intact. 
What gets me is that both .JAR files are the same size, so I'm not sure what the problem is. But, there is a regular error that keeps occurring when running in MultiMC (This is while the client is running!)

https://paste.ee/p/edJeY

Basically, it can't find the files at the location specified.

**Comment by QuImUfu** [comment] 2018-03-09 10:00
can kinda confirm, although i get no sound on both of them, with the vanilla launcher i get no errors.
The vanilla java launcher behaves exactly like MultiMC.(same error messages, no sound)
The new native launcher displays no error messages, that maybe means that sound should be working.

**Comment by peterix** [comment] 2018-04-08 14:08
Duplicate of  #2209 -- I am going to use that one for gathering all the duplicates.

**Closed by peterix** 2018-04-08 14:08 UTC
Labels: duplicate, game: runtime
