### ISSUE TITLE
Custom Sorting mode

### ISSUE THREAD

**Issue by BenignPigeon** [MultiMC/MultiMC5#4140] opened 2021-10-02 17:57 UTC
### Role

I play vanilla and modded minecraft 

### Suggestion

i would like for there to be a feature that lets you drag each instance in a custom order that you can choose

### Benefit

it is faster to find the instance that you want to play, because it is in an order that makes sense to you

### This suggestion is unique

- [x] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

There are currently 2 sorting modes: By last launched, and by name. My proposed addition would enable you to drag the instances into an order that would be custom and best suited to you.

How it would look:

![image](https://user-images.githubusercontent.com/85837722/135727162-3782c8f7-d557-4283-a72f-5c623fb5284a.png)

**Comment by phit** [comment] 2021-10-02 17:58
Duplicate of https://github.com/MultiMC/MultiMC5/issues/3979 #2153 #2198

**Closed by phit** 2021-10-02 17:58 UTC
