### ISSUE TITLE
instance metadata wiped out after multimc crash because I ran out of filespace

### ISSUE THREAD

**Issue by bogger33** [MultiMC/MultiMC5#3054] opened 2020-03-26 18:50 UTC
System Information
-----------------------------
MultiMC version: 0.6.9-develop-1336 on lin64

Operating System: debian testing KDE

Summary of the issue or suggestion:
----------------------------------------------

my multimc crashed (almost definitely because I ran out of filespace), and it seems to have wiped out the metadata for my vanilla minecraft instance. No big deal, it looks like the saves and everything important is still there, but it's now called "Unnamed Instance" and it's telling me that I need to upgrade the instance because of the OneSix instance format.

i checked and both my instance.cfg and mmc-pack.json are now 0 bytes, so I guess it was trying to write to them or something? I don't think I actually had minecraft running when this happened, though. 

What should happen:
------------------------------

I mean ideally it wouldn't corrupt the instance metadata, I dunno how preventable this is

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. run out of disk space

2. have multimc running

3. hopefully it will happen to you, i guess?

Suspected cause:
---------------------------
running out of file space

**Comment by Zetabite** [comment] 2020-03-26 18:52
Best you can do is backup the data, and redo the instance and than copying over the necessary files

**Comment by bogger33** [comment] 2020-03-26 18:52
yeah I'll just make a new instance and copy my save there, it's definitely not the end of the world

**Comment by Janrupf** [comment] 2020-04-06 21:12
Interesting bug report. There are possibly ways to fix this, but it really is hard to handle such situation as the OS will just throw errors at you where you would never have expected errors.

**Comment by bogger33** [comment] 2020-04-18 23:02
I think what you'd have to do is write a copy of the file when saving it, delete the original only of the write succeeds, and then rename.

**Comment by phit** [comment] 2021-03-09 21:09
Duplicate of https://github.com/MultiMC/MultiMC5/issues/2788

**Closed by phit** 2021-03-09 21:09 UTC
