### ISSUE TITLE
Microsofts Account

### ISSUE THREAD

**Issue by athamour1** [MultiMC/MultiMC5#3994] opened 2021-08-08 18:57 UTC
### Role

Modded minecraft player

### Suggestion

It need support for microsoft aacounts

### Benefit

New accounts in minecraft are only microsoft you cant anymore buy minecraft with Mojang account

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

I know that isn't a unique request, but I think that's new, or I don't have seen anything for creatting a new mojang account. And for moded Minecraft players MultiMC is a great tool.

**Comment by Janrupf** [comment] 2021-08-08 19:00
Duplicate of https://github.com/MultiMC/MultiMC5/issues/3392.

Why even create another issue for it?

**Closed** 2021-08-08 20:09 UTC
