### ISSUE TITLE
Copy settings/resource packs options

### ISSUE THREAD

**Issue by technic-void** [MultiMC/MultiMC5#4052] opened 2021-08-28 17:06 UTC
### Role

I create new instances and have to install resource packs and configure settings each time

### Suggestion

I want MultiMC to have a default options.txt and resource pack folder, which are put into new instances automatically

### Benefit

It is a convenience feature that saves a lot of time and effort.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

For the resource packs, simply overwriting the empty folder or adding all the resource packs into the folder will do. For the options.txt file, it would be helpful to have a "master file" with all the options ever accessed, and when a new instance is created, go through the options.txt of that instance and replace lines with the ones from the master file. that way, custom key binds for large Modpacks could be included without causing errors with instances that do not have those options.

For implementation, read a line form the instance, split it at the ":" and look for the same text in the master file and then replace the line with the new line. Thanks, if you do implement this.

**Comment by technic-void** [comment] 2021-08-28 17:09
Example:
key_key.waila.config:key.keyboard.keypad.0 (in instance)

split it to key_key.waila.config and search for corresponding line

key_key.waila.config:key.keyboard.keypad.h (in master file)

replace line with key_key.waila.config:key.keyboard.keypad.h

**Comment by peterix** [comment] 2021-08-28 17:55
Too janky, too squishy and too easy for it to create problems for the next 10 years.

**Comment by phit** [comment] 2021-08-30 08:41
Duplicate of https://github.com/MultiMC/MultiMC5/issues/3795 and https://github.com/MultiMC/MultiMC5/issues/3861

**Closed by phit** 2021-08-30 08:41 UTC
