### ISSUE TITLE
It would be good if you could allow us to change where the screenshots get uploaded. for example, I have an imgur account, but it uploads it to a generic account and not to my imgur account

### ISSUE THREAD

**Issue by SpyCraft3r** [MultiMC/MultiMC5#1866] opened 2017-04-26 04:44 UTC
System Information
-----------------------------
MultiMC version:

Operating System:

Summary of the issue or suggestion:
----------------------------------------------

What should happen:
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.

2.

3.

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by Heufneutje** [comment] 2017-04-26 07:15
Duplicate of #1089

**Comment by SpyCraft3r** [comment] 2017-04-27 01:18
Ok that was almost 2 years ago. So I wont hold my breath for it

⁣Sent from BlueMail ​

**Comment by peterix** [comment] 2017-04-27 07:22
That's what happens when there's one guy working on something like this 'on the weekends, maybe'.

Btw: https://workflowy.com/s/2EyDMcp7CU#/5178d6d87739

**Comment by SpyCraft3r** [comment] 2017-04-27 07:23
PFFT

**Comment by peterix** [comment] 2017-04-27 07:29
/shrug

This is the bigger problem: #1864

**Closed** 2017-04-27 07:29 UTC

**Comment by SpyCraft3r** [comment] 2017-04-27 07:31
Don’t like the truth, then don’t be a lazy fuck

**Comment by peterix** [comment] 2017-04-27 08:48
I do accept pull requests, if the code is decent.
