### ISSUE TITLE
Twitch URL VANISH - MultiMc 5 V0.6.8-1333

### ISSUE THREAD

**Issue by H2NsO** [MultiMC/MultiMC5#3014] opened 2020-02-25 10:44 UTC
Twitch URL has vanish
![Twitch URL VANISH](https://user-images.githubusercontent.com/61457259/75240161-cf801500-57bb-11ea-9435-95ac3a9aa69c.png)

**Comment by cfanoulis** [comment] 2020-02-25 12:44
intended https://github.com/MultiMC/MultiMC5/commit/af5120c828831dfe41482ebaff79608ba8531ede

**Comment by GeorgeWilson96** [comment] 2020-04-05 08:47
If this is as intended shouldn't this be marked as closed ?

**Comment by Zetabite** [comment] 2020-04-05 11:48
Either the issue creator or a project member can close it

**Closed** 2020-08-10 19:36 UTC
