### ISSUE TITLE
Segfault on closing instance editor

### ISSUE THREAD

**Issue by saphire-lattice** [MultiMC/MultiMC5#2176] opened 2018-03-08 09:05 UTC
System Information
-----------------------------
MultiMC version: `0.6.1-1092`, `git`

Operating System: `Linux, Archlinux, fully updated`

Summary of the issue:
----------------------------------------------
 When using native OS QT libraries (not built in with the release binary of MultiMC), when the instance editor is closed, the whole application crashes with SIGSEGV.

What should happen:
------------------------------
The window should close and MultiMC should continue running.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Remove bundled QT libraries OR build MultiMC by yourself.

2. Launch it. No matter if it's a new and clear or old and used instance.

3. Try to edit any instance, new or old, then close the window.

4. Observe the crash.

Suspected cause:
---------------------------
Change in how the new version of Qt libraries clean up windows. Possibly a stray delete in some code that duplicates or stops the clean up from working correctly?
Alternatively it's a bug in Qt itself.

Logs/Screenshots:
----------------------------
[Valgrind log](https://gist.github.com/dangranos/7ee39c4d16c066207e3cb02835ba7947)

**Comment by jambonmcyeah** [comment] 2018-03-10 14:59
I have the same issue

**Comment by peterix** [comment] 2018-05-22 12:01
This is actually a Qt bug:
https://bugreports.qt.io/browse/QTBUG-68393

I managed to reproduce it here:
https://github.com/peterix/demo_heap_corruption

**Comment by peterix** [comment] 2018-05-22 12:04
The workaround seems to be to tweak the UI files until it stops appearing in valgrind.

But that's not great and introduces visual and layout changes.

**Comment by peterix** [comment] 2018-10-31 22:48
This is fixed upstream and will be in Qt 5.12. Closing here, because MultiMC still works with the bundled Qt.

**Closed by peterix** 2018-10-31 22:48 UTC
Labels: external, multimc: bug, multimc: linux
