### ISSUE TITLE
Can't download on Linux Ubuntu

### ISSUE THREAD

**Issue by RedFox86** [MultiMC/MultiMC5#3678] opened 2021-03-23 21:18 UTC
### Operating System

Linux

### Description of bug

QT5 doesn't exist anymore

### Steps to reproduce

Try and download it and it will give an error message.

### Suspected cause

QT5 is gone.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment] 2021-03-23 21:19
Duplicate of https://github.com/MultiMC/MultiMC5/issues/3413

**Comment by phit** [comment] 2021-03-23 21:20
please see that issue for how to fix this on your end in the meantime

**Closed by phit** 2021-03-23 21:19 UTC
Labels: bug
