### ISSUE TITLE
[Suggestion] Option for instance to always use latest version

### ISSUE THREAD

**Issue by darkenedAspie** [MultiMC/MultiMC5#2024] opened 2017-10-19 23:05 UTC
System Information
-----------------------------
MultiMC version: 0.5.0-887

Operating System: Ubuntu 17.04 (64-bit)

Summary of the issue or suggestion:
----------------------------------------------
Option to keep Minecraft version of a given instance up-to-date.

What should happen:
------------------------------
There would ideally be an 'always use latest version' option in the Minecraft versions dialogue, similar to the standard java edition launcher. I have an instance that I use for snapshot testing, but I have to manually change the version every time a new version of Minecraft is released. It's a pain, and I have difficulty keeping track of when new releases occur. Having auto-updating as an option, but not necessarily the default, would prove invaluable for situations such as this.

**Comment by peterix** [comment] 2020-01-09 11:32
Duplicate of #87

**Closed** 2020-01-09 11:31 UTC
Labels: feature
