### ISSUE TITLE
Couldn't Extract Native Jar

### ISSUE THREAD

**Issue by 3jlowes** [MultiMC/MultiMC5#2248] opened 2018-04-17 17:02 UTC
System Information
-----------------------------
MultiMC version: 0.6.2-1222

Operating System: Windows 10

Summary of the issue or suggestion:
----------------------------------------------
Pack does not launch when clicking launch.

What should happen:
------------------------------
Pack should launch

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
Not really sure if it is reporduceable, probably something I am doing wrong. MultiMC is in its own folder, and is not being synced with onedrive (thats what I have read to fix something like this)
Suspected cause:
---------------------------
Not sure.

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
https://gist.github.com/3jlowes/54561c4dc581958516dc8344fa9df7d9

Additional Info:
---------------------------

**Comment by peterix** [comment] 2018-04-17 17:04
Is there a stray, broken java process running in the background?

**Comment by phoenixmcallister** [comment] 2018-04-26 09:06
i have the same issue with solus linux
`Couldn't extract native jar '/opt/multimc/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-linux.jar' to destination '/opt/multimc/instances/SevTech+Ages-3.0.6/natives'
Couldn't extract native jar '/opt/multimc/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-linux.jar' to destination '/opt/multimc/instances/SevTech+Ages-3.0.6/natives'
Couldn't extract native jar '/opt/multimc/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3-natives-linux.jar' to destination '/opt/multimc/instances/SevTech+Ages-3.0.6/natives'`

**Comment by phoenixmcallister** [comment] 2018-04-26 09:12
wait i got it working, edit the instance goto version and click download all in the bottom right

**Comment by peterix** [comment] 2018-04-26 11:10
@phoenixmcallister hmm... that's not likely to be the same issue... similar with different cause.

You probably launched offline, which -- aside from not refreshing the auth token and not using your account -- avoids downloading any extra files.

**Comment by peterix** [comment] 2018-08-29 20:35
Assuming this got fixed, closing.

**Closed by peterix** 2018-08-29 20:35 UTC
Labels: support

**Comment by pressRtowin** [comment] 2019-05-04 18:49
I'm having the same issue. Never had it before. started out of the blue. Not always the same jar either, but always the issue of not being able to extract it.

**Comment by beckyh2112** [comment] 2019-05-25 19:32
One of my 1.12.2 worlds started throwing this error. It previously had completely frozen up while I was running and brought my computer virtually to a halt. I managed to kill it with ctrl-alt-delete, but after that, I started getting this error when I tried to load that world.

**Comment by Anora** [comment] 2019-11-20 01:37
I'm getting this and using download all did not fix it

**Comment by Heufneutje** [comment] 2019-11-20 07:39
Create a new issue. Don't post on something that's been closed for over a year.

**Comment by weinus404** [comment] 2021-01-21 01:14
For anyone having this problem, click your glitch instance, then click 'Copy Instance' on the bottom right.
and the new one will work fine.
delete older one.

**Comment by dudaskank** [comment] 2021-12-10 19:45
Got the same problem some days ago, my son force the close while loading of a instance with a heavy modpack and tried to rerun the instance. Somehow, some native jars are yet opened in java.exe. I couldn't delete the folder, but could rename it, so renamed to _native. Probably a system restart could do the same.

**Comment by akainocode** [comment] 2022-05-21 17:19
Hi, I just encountered this issue - the reason you aren't able to delete the folder is because there's a running instance of java. Kill the instance that was created on the launch attempt and then emptying the native folder resolves the issue.

**Comment by ubermidget2** [comment] 2022-12-04 09:05
Happened to me as well, as others have said there was a rouge java process (That didn't show on Task Manager?)

In case anyone needs it, this does the trick in an Admin Command Prompt:
```
taskkill /f /IM javaw.exe
```

**Comment by Plel-Coder** [comment] 2023-01-29 16:19
Happened to me, in my case i didnt have enough space to extract native jar

**Comment by Heufneutje** [comment] 2023-12-02 08:11
1. Please don't necropost old issues.
2. That's not even MultiMC.

**Comment by LilWolfet** [comment] 2024-02-05 06:10
> 1. Please don't necropost old issues.
> 
>     2. That's not even MultiMC.

1. This is clearly MultiMC as the solution that worked for me is to Duplicate an MultiMC instance and delete the old one, for no apparent reason other than emptying a random folder.

2. Be quiet and go harass other users, in my use case scenario this solution worked, however it's clearly still an issue 7 years later. It either needs to be patched or there needs to be a fail-safe/workaround to automatically do this, worked on or looked at. And the only way for that to happen is if an old post like this garners attention.

**Comment by Heufneutje** [comment] 2024-02-05 19:12
> > 1. Please don't necropost old issues.
> >    
> >    2. That's not even MultiMC.
> 
>     1. This is clearly MultiMC as the solution that worked for me is to Duplicate an MultiMC instance and delete the old one, for no apparent reason other than emptying a random folder.
> 
>     2. Be quiet and go harass other users, in my use case scenario this solution worked, however it's clearly still an issue 7 years later. It either needs to be patched or there needs to be a fail-safe/workaround to automatically do this, worked on or looked at. And the only way for that to happen is if an old post like this garners attention.
> 
>     3. Seek mental help if you think otherwise.

Before you start typing rude replies to me like this, note the deleted comment. I was actually responding to someone posting a log from a piracy launcher. So as said, not MultiMC. 

If you think this is an issue that needs to be fixed, then please create a new issue with reproducible steps so it can be looked into.

**Comment by TacoGS** [comment] 2024-02-05 19:15
Be respectful or messages will be removed.

**Comment by LilWolfet** [comment] 2024-03-15 22:36
Go to hell.

**Comment by Bluscream** [comment] 2024-03-16 14:04
Everyone loves censorship until they're being censored themselves

**Comment by Janrupf** [comment] 2024-03-16 20:15
I'm not sure why this is gaining traction again, but there is a solution here:

> Happened to me as well, as others have said there was a rouge java process (That didn't show on Task Manager?)
> 
> In case anyone needs it, this does the trick in an Admin Command Prompt:
> 
> ```
> taskkill /f /IM javaw.exe
> ```

The issue is caused by stray running java processes.
