### ISSUE TITLE
Classload order appears to be different than the original launcher

### ISSUE THREAD

**Issue by me4502** [MultiMC/MultiMC5#1752] opened 2016-12-14 04:27 UTC
System Information
-----------------------------
MultiMC version: 0.4.11-751

Operating System: Windows 10

Summary of the issue or suggestion:
----------------------------------------------
When running mods that use ASM to modify parts of Forge, the classes are incorrectly loaded after they should be. This causes mods, such as Sponge, to completely fail. https://kobra.io/#/e/-KYvX3DPnRVf-Nm1o8ot

What should happen:
------------------------------
The specific class that's causing an issue, LoadController, should not have loaded before the tweakers and coremods are applied.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Install Forge

2. Install SpongeForge

3. Launch the game

Suspected cause:
---------------------------
I suspect that the wrong things are being called to launch the game when running with forge. LaunchWrapper should take care of all of this generally.

Logs/Screenshots:
----------------------------
http://pastebin.com/dGMJ8eN4
https://kobra.io/#/e/-KYvX3DPnRVf-Nm1o8ot

Additional Info:
---------------------------

**Comment by peterix** [comment] 2016-12-14 07:50
Neither of those logs are usable. Please use the Upload button.

Also, please provide something to compare with - with the expected order of libraries clearly visible.

**Comment by peterix** [comment] 2016-12-14 07:52
If this is not happening on the level of libraries. it's purely a mod problem.

**Comment by me4502** [comment] 2016-12-14 08:13
The multimc log was made with the upload button on pastebin. These aren't my logs, I'm forwarding the issue from someone else.

I'll ask around as for what the expected library load order is, however I can tell you that the class `net.minecraftforge.fml.common.LoadController` is loading too early.

**Comment by peterix** [comment] 2016-12-14 08:48
What I suspect is happening is related to #1508 

I can't do anything with crash logs. There is nothing in them that would help me actually understand the issue. Maybe they are enough for debugging vanilla minecraft bugs, but that's not what I'm doing here.

So, provide the actual log and don't dig in the 'other logs', they don't contain enough information about the instance.

**Comment by peterix** [comment] 2016-12-14 08:57
![image](https://cloud.githubusercontent.com/assets/203326/21175649/af431ace-c1e3-11e6-80df-7074163e60c7.png)

**Comment by me4502** [comment] 2016-12-14 09:08
Thanks, I'll pass that on to them.

**Comment by Heufneutje** [comment] 2016-12-14 12:34
The problem was that they probably started a new MultiMC session after the crash, so the MultiMC-0.log file did not contain the crash anymore.

**Comment by peterix** [comment] 2016-12-14 12:41
MultiMC-[0-5].log is the **MultiMC** log. If your game is crashing, the most you will probably see there will be that some background launch task ended with an error. It is only useful for diagnosing errors in MultiMC - like download (network, SSL, task scheduling) issues.

Sometimes it is good for figuring out what MultiMC was doing before **it** crashed.

**Comment by me4502** [comment] 2016-12-15 03:29
Okay, I've got the link from the upload button.

http://paste.ee/p/SSm6I

**Comment by peterix** [comment] 2016-12-15 08:27
Right. I cannot reproduce this on the develop version, but I also don't have (and can't locate) that `Murder-1.0-SNAPSHOT(1)` mod.

Can I get a copy of that?

Local load order:
```
Libraries:
  /home/peterix/minecraft/mmc5/libraries/com/mojang/netty/1.6/netty-1.6.jar
  /home/peterix/minecraft/mmc5/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  /home/peterix/minecraft/mmc5/libraries/net/java/dev/jna/jna/3.4.0/jna-3.4.0.jar
  /home/peterix/minecraft/mmc5/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  /home/peterix/minecraft/mmc5/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  /home/peterix/minecraft/mmc5/libraries/net/sf/jopt-simple/jopt-simple/4.6/jopt-simple-4.6.jar
  /home/peterix/minecraft/mmc5/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  /home/peterix/minecraft/mmc5/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  /home/peterix/minecraft/mmc5/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  /home/peterix/minecraft/mmc5/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  /home/peterix/minecraft/mmc5/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  /home/peterix/minecraft/mmc5/libraries/io/netty/netty-all/4.0.23.Final/netty-all-4.0.23.Final.jar
  /home/peterix/minecraft/mmc5/libraries/com/google/guava/guava/17.0/guava-17.0.jar
  /home/peterix/minecraft/mmc5/libraries/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar
  /home/peterix/minecraft/mmc5/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar
  /home/peterix/minecraft/mmc5/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar
  /home/peterix/minecraft/mmc5/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
  /home/peterix/minecraft/mmc5/libraries/com/mojang/authlib/1.5.24/authlib-1.5.24.jar
  /home/peterix/minecraft/mmc5/libraries/com/mojang/realms/1.10.4/realms-1.10.4.jar
  /home/peterix/minecraft/mmc5/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  /home/peterix/minecraft/mmc5/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  /home/peterix/minecraft/mmc5/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  /home/peterix/minecraft/mmc5/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  /home/peterix/minecraft/mmc5/libraries/it/unimi/dsi/fastutil/7.0.12_mojang/fastutil-7.0.12_mojang.jar
  /home/peterix/minecraft/mmc5/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9/log4j-api-2.0-beta9.jar
  /home/peterix/minecraft/mmc5/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9/log4j-core-2.0-beta9.jar
  /home/peterix/minecraft/mmc5/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  /home/peterix/minecraft/mmc5/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  /home/peterix/minecraft/mmc5/libraries/org/lwjgl/lwjgl/lwjgl/2.9.1/lwjgl-2.9.1.jar
  /home/peterix/minecraft/mmc5/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.1/lwjgl_util-2.9.1.jar
  /home/peterix/minecraft/mmc5/libraries/net/minecraftforge/forge/1.11-13.19.0.2168/forge-1.11-13.19.0.2168-universal.jar
  /home/peterix/minecraft/mmc5/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  /home/peterix/minecraft/mmc5/libraries/org/ow2/asm/asm-all/5.0.3/asm-all-5.0.3.jar
  /home/peterix/minecraft/mmc5/libraries/jline/jline/2.13/jline-2.13.jar
  /home/peterix/minecraft/mmc5/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  /home/peterix/minecraft/mmc5/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  /home/peterix/minecraft/mmc5/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  /home/peterix/minecraft/mmc5/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  /home/peterix/minecraft/mmc5/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar
  /home/peterix/minecraft/mmc5/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar
  /home/peterix/minecraft/mmc5/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  /home/peterix/minecraft/mmc5/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  /home/peterix/minecraft/mmc5/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  /home/peterix/minecraft/mmc5/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  /home/peterix/minecraft/mmc5/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  /home/peterix/minecraft/mmc5/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  /home/peterix/minecraft/mmc5/libraries/java3d/vecmath/1.5.2/vecmath-1.5.2.jar
  /home/peterix/minecraft/mmc5/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  /home/peterix/minecraft/mmc5/versions/1.11/1.11.jar
  /home/peterix/minecraft/mmc5/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-linux.jar
  /home/peterix/minecraft/mmc5/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.1/lwjgl-platform-2.9.1-natives-linux.jar
```

**Comment by me4502** [comment] 2016-12-15 08:33
Does the develop version contain any differences that could impact this than the stable release?

I don't have authority to hand over the Murder mod, however I can definitely state that it doesn't impact classload order in any way.

**Comment by peterix** [comment] 2016-12-15 08:45
Clearly, there are differences - the classpath is different.

**Comment by me4502** [comment] 2016-12-15 08:52
Thanks, I've sent through a link for them to test.

**Comment by me4502** [comment] 2016-12-15 23:43
Okay, so the dev versions fix the problem. Do you have any idea on when they'll be promoted to stable?

**Comment by peterix** [comment] 2016-12-16 14:13
Soon(TM)

I'd like to release it over the holidays.

**Comment by peterix** [comment] 2016-12-18 23:31
Anyway... fixed in develop :)

**Closed by peterix** 2016-12-18 23:31 UTC

**Comment by me4502** [comment] 2017-01-13 00:31
Any news on that stable version?

**Comment by peterix** [comment] 2017-01-13 01:02
Yep. Everything is pretty much ready. I just need to write a post on the website and actually push the updates out.

So, you can expect it this weekend.
