### ISSUE TITLE
Allow selecting beta versions of twitch modpacks

### ISSUE THREAD

**Issue by SoniEx2** [MultiMC/MultiMC5#3094] opened 2020-04-14 18:06 UTC
System Information
-----------------------------
MultiMC version: same as in #3093 

Operating System:

Summary of the issue or suggestion:
----------------------------------------------
kinda wish there was a way to select beta versions of twitch modpacks. or really any version besides the latest release.

What should happen:
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.

2.

3.

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by Scotsguy** [comment] 2021-03-08 14:14
Duplicate of #3611

**Closed by Scotsguy** 2021-03-08 14:14 UTC
