### ISSUE TITLE
Microsoft Account Support

### ISSUE THREAD

**Issue by lazytspo** [MultiMC/MultiMC5#3909] opened 2021-06-28 05:22 UTC
### Role

I want to support it

### Suggestion

I need the support of Microsoft Accounts at MultiMC

### Benefit

Because Accounts from Microsoft are at the login section at minecraft.net, accordiance to Mojang, they are no longer getting people to register new Mojang Accounts anymore.

### This suggestion is unique

- [ ] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by ImperatorStorm** [comment] 2021-06-28 06:53
duplicate of #3392

**Closed** 2021-06-28 07:19 UTC
