### ISSUE TITLE
Error loading MutliMC 5 on Linux openSUSE 12.2

### ISSUE THREAD

**Issue by Cryotechnic** [MultiMC/MultiMC5#687] opened 2014-12-21 21:53 UTC
I tried to execute MultiMC 5 on my PC (Linux openSUSE 12.2 32bit) and this is what I get:
[|] Valid metadata not found at specified URL(s)
Error: MultiMC is missing the following libraries that it needs to work correctly:
	libpng12.so.0, libpng12.so.0, libpng12.so.0, libpng12.so.0, libpng12.so.0, libpng12.so.0, libpng12.so.0, libpng12.so.0, libpng12.so.0, libpng12.so.0, libpng12.so.0, 
Please install them from your distribution's package manager.

Hint: sudo zypper install Warning: Disabling Loading Warning: Warning: Reading S --+------------+---------+--------------+------+------------------ | Warning: Disabling Loading Warning: Warning: Reading S --+------------+---------+--------------+------+------------------ | Warning: Disabling Loading Warning: Warning: Reading S --+------------+---------+--------------+------+------------------ | Warning: Disabling Loading Warning: Warning: Reading S --+------------+---------+--------------+------+------------------ | Warning: Disabling Loading Warning: Warning: Reading S --+------------+---------+--------------+------+------------------ | Warning: Disabling Loading Warning: Warning: Reading S --+------------+---------+--------------+------+------------------ | Warning: Disabling Loading Warning: Warning: Reading S --+------------+---------+--------------+------+------------------ | Warning: Disabling Loading Warning: Warning: Reading S --+------------+---------+--------------+------+------------------ | Warning: Disabling Loading Warning: Warning: Reading S --+------------+---------+--------------+------+------------------ | Warning: Disabling Loading Warning: Warning: Reading S --+------------+---------+--------------+------+------------------ | Warning: Disabling Loading Warning: Warning: Reading S --+------------+---------+--------------+------+------------------ | 
{username}{computername}:~/Downloads/MultiMC>

**Comment by JasonB42** [comment] 2015-01-16 23:24
Running fine on Ubuntu 14.04. In my experience, "Could not connect to display" messages are usually caused by security or configuration problems. Security, if your current user does not have permissions to your running XServer (sometimes after you use 'su' to switch users). Sometimes messed up environment variables cause this too. Can you run other graphical programs from this same command line?

**Comment by Gskartwii** [comment] 2015-02-16 14:40
I'm on Arch Linux and I tried installing libpng12 from pacman and source, but the problem stays.

**Comment by HugoPoi** [comment] 2015-06-10 21:14
@Gskartwii On Archlinux use the AUR packet (simply install with yaourt)

**Comment by Kilobyte22** [comment] 2015-06-10 21:19
The AUR package is not self updating. I don't recommend it. You should however install libpng12 from AUR (pacapt -S libpng12)

**Comment by peterix** [comment] 2015-08-16 01:08
Won't fix. Update your OS.

**Closed by peterix** 2015-08-16 01:08 UTC
Labels: bug
