### ISSUE TITLE
Asset Problem

### ISSUE THREAD

**Issue by SPACEFACE2394** [MultiMC/MultiMC5#1829] opened 2017-02-28 20:14 UTC
https://paste.ee/p/4m5AP
MultiMC version: 0.5.0-945

Minecraft folder is:
instances/AvP/minecraft

Java path is:
C:/Program Files/Java/jre1.8.0_111/bin/javaw.exe

Java is version 1.8.0_111, using 64-bit architecture.

Instance update failed because: Failed to download the assets index:
Job 'Asset index for AvP' failed to process:
https://s3.amazonaws.com/Minecraft.Download/indexes/1.7.10.json.

Clipboard copy at: 28 Feb 2017 13:14:09 -0700

**Comment by peterix** [comment] 2017-02-28 20:18
Duplicate of #1828

**Closed by peterix** 2017-02-28 20:18 UTC
