### ISSUE TITLE
White screen

### ISSUE THREAD

**Issue by euerick** [MultiMC/MultiMC5#3048] opened 2020-03-25 18:11 UTC
System Information
-----------------------------
MultiMC version: 0.6.8-1419 on win32

Operating System: Windows 10

Summary of the issue or suggestion: I added the ModPack from MC Eternal and when I click to launch, it just stay a white screen launcher
----------------------------------------------

What should happen: Open normally the launcher
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.

2.

3.

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
[New Paste 1.txt](https://github.com/MultiMC/MultiMC5/files/4382675/New.Paste.1.txt)

Additional Info: If I open the normal launcher, everything is fine. Only on MultiMC that goes to white screen
---------------------------

**Comment by Scotsguy** [comment] 2021-03-07 17:41
Doesn't look to be caused by MultiMC, closing.

**Closed by Scotsguy** 2021-03-07 17:41 UTC
