### ISSUE TITLE
Java version changes when installing JDK

### ISSUE THREAD

**Issue by xander1111** [MultiMC/MultiMC5#3349] opened 2020-09-19 19:26 UTC
System Information
-----------------------------
MultiMC version: 0.6.11-1403

Operating System: Windows 10 64-bit

Summary of the issue or suggestion: MultiMC switches Java version when a new version of JDK is installed
----------------------------------------------

What should happen: Java version doesn't change
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Install a new Java JDK

2. Check MultiMC Java version

Suspected cause: MultiMC had the Java path set to `javaw` which got changed to point to the new install of Java
---------------------------

Logs/Screenshots:
----------------------------

Additional Info:
---------------------------

**Comment by phit** [comment] 2020-09-19 19:50
Why is this an issue? What are you expecting to happen, if you point MMC to `javaw` and its changed, MultiMC keeps using what you told it to use.

**Comment by Scotsguy** [comment] 2021-03-07 21:07
Looks like it's working as intended, closing.

**Closed by Scotsguy** 2021-03-07 21:07 UTC
