### ISSUE TITLE
Console icon Linux

### ISSUE THREAD

**Issue by Darkefyre13** [MultiMC/MultiMC5#803] opened 2015-03-03 21:46 UTC
When i have an instance running the console icon covers up where the exit button is located on my "task bar" running ver 0.4.5 on lin64
![screenshot from 2015-03-04 10 44 37](https://cloud.githubusercontent.com/assets/8508813/6473076/b119e9ec-c25b-11e4-9a61-3cd4a93f5447.png)

**Comment by neclimdul** [comment] 2015-03-03 21:56
Based on the screenshot this looks like a Unity specific bug. I don't see this in KDE.

**Comment by peterix** [comment] 2015-03-11 22:27
Yep. Weird linux things.

This happens when people decide to stop supporting standards and reinvent the wheel instead.

Fixes will have to wait for the next UI redesign of the console window.

**Comment by peterix** [comment] 2015-03-11 22:31
And, duplicate of #403

**Closed by peterix** 2015-03-11 22:31 UTC
