### ISSUE TITLE
Sound not working

### ISSUE THREAD

**Issue by linnnylinnylinux** [MultiMC/MultiMC5#2212] opened 2018-03-31 05:53 UTC
SO in no matter what verion or with mods or not the sound wont play! idk why pls halp!

**Comment by Dushess** [comment] 2018-03-31 08:10
Old instances? Like 1.8.3b?

**Comment by Janrupf** [comment] 2018-03-31 11:00
Duplicate of #2209 and MANY other issues... Mojang removed these files so we are searching for a way to get them

**Comment by linnnylinnylinux** [comment] 2018-04-04 21:25
ok

**Comment by Timolino456** [comment] 2018-04-06 15:35
I have this problem too. It's with all new instances with old alpha or beta versions (I haven't tried it with any release version yet..)

**Comment by peterix** [comment] 2018-04-06 16:02
Duplicate of https://github.com/MultiMC/MultiMC5/issues/2209

**Closed by peterix** 2018-04-06 16:02 UTC
Labels: duplicate
