### ISSUE TITLE
Select all mods

### ISSUE THREAD

**Issue by ThePixelNerd** [MultiMC/MultiMC5#1117] opened 2015-07-07 21:17 UTC
There needs to be a checkbox in the loader mods screen at the top to select/deselect all mods at once. Right now I have about 60 mods and to turn them all on/off is a huge pain. ;)

**Comment by peterix** [comment] 2015-08-15 17:33
+1

**Comment by peterix** [comment] 2015-08-18 12:31
http://blog.qt.io/blog/2012/09/28/qt-support-weekly-27-widgets-on-a-header/

**Comment by peterix** [comment] 2015-08-18 12:32
Because this works by renaming files, the effect is that we suddenly have a lot of files to rename.

One more thing that would benefit from background processing and IO/FS tasks.

**Comment by peterix** [comment] 2015-08-21 21:44
I don't think I can do this in what I would consider acceptable quality without changing the UI to a fully custom one.

**Comment by peterix** [comment] 2016-01-24 11:19
Duplicate of #901 

I am not going to do it by modifying the view header. It is too dodgy.
It will either be buttons or context menus. Or both.

Also, moved to workflowy: https://workflowy.com/s/2EyDMcp7CU (Ideas -> mod list improvements)

**Comment by peterix** [comment] 2016-08-04 21:18
Done.

**Closed by peterix** 2016-08-04 21:18 UTC
Labels: feature
