### ISSUE TITLE
0.4.11-751 - logging is broken for instances using Forge

### ISSUE THREAD

**Issue by srs-bsns** [MultiMC/MultiMC5#1508] opened 2016-03-03 01:23 UTC
**MultiMC version:** 0.4.11-751
**Operating System:** Win 7

**Summary of the issue or suggestion:** Any instance started using Minecraft Forge will log all data to ``latest.log`` instead of separate log files: ``latest.log``, ``fml-client-latest.log``, ``fml-junk-earlystartup.log``.

**What should happen:** Obvious.

**Steps to reproduce the issue (Add more if needed):**  Start any instance using Minecraft Forge in MMC v0.4.11-751

**Suspected cause:** Hrm.. negligence? :)

**Logs/Screenshots:** [MultiMC-0.log](https://gist.github.com/srs-bsns/485c5f95a1726c122672)

**Additional Info:** N/A

**Comment by peterix** [comment] 2016-03-03 01:24
I don't see how that could possibly be a problem with MultiMC.

**Comment by peterix** [comment] 2016-03-03 01:35
Also, cannot reproduce the issue. All those files have mostly nonsensical contents in my instances, none are empty.

**Comment by srs-bsns** [comment] 2016-03-03 01:41
It's has to be a problem with MultiMC because it only started after updating to the latest stable. Reverting back to the previous stable version (v0.4.10.733) goes back to the proper mechanics of logging to separate files.

**Comment by peterix** [comment] 2016-03-03 02:04
I do not see this as an issue and would rather see those files gone, TBH.

That aside...

It's a classpath ordering issue... because log4j is completely insane and grabs the first file from the first jar it finds and runs with it. So it grabs the one from launchwrapper, at random.

If this ever worked, it was by chance.

**Comment by peterix** [comment] 2016-03-03 02:05
I can apply some different random order and it will behave differently :)

**Comment by peterix** [comment] 2016-03-28 19:47
Should be fixed in develop, for new instances.

If it bothers you in existing instances, reinstall forge.

**Closed by peterix** 2016-03-28 19:47 UTC
Labels: bug, in progress

**Comment by srs-bsns** [comment] 2016-03-29 00:29
I just tested 0.4.12-develop-763. Confirmed fixed. Thanks.

**Comment by mezz** [comment] 2016-08-02 19:27
Just want to note that this seems to still be broken in the Stable build of MultiMC. I had to update to dev and reinstall forge to fix it. 
`fml-client-latest.log` contains some information that is critical for debugging some rare but difficult mod issues, without it I can't help players solve their issue very well.
