### ISSUE TITLE
Suggestion : Ability create links between instances

### ISSUE THREAD

**Issue by unixfox** [MultiMC/MultiMC5#1168] opened 2015-08-04 19:44 UTC
Each instance is completely isolated from others. The ability to create links between instances, for example by sharing the same backup folder or the same server list.

**Comment by peterix** [comment] 2015-08-04 19:46
This would likely only work on linux and osx.

**Comment by 02JanDal** [comment] 2015-08-04 19:47
Duplicate of #42

**Closed by 02JanDal** 2015-08-04 19:47 UTC
Labels: enhancement
