### ISSUE TITLE
Can't Create Any Instances.

### ISSUE THREAD

**Issue by Campnut01** [MultiMC/MultiMC5#2943] opened 2019-12-20 20:16 UTC
System Information:
iMac OS X Version 10.9.5
Processor: 3.06 GHz Intel Core 2 Duo
Memory: 4 GB 1067 MHz DDR3
-----------------------------
MultiMC version: Version 0.6.7-1316

Operating System: OS X Version 10.9.5

Summary of the issue or suggestion: Whenever I try to create an instance no matter what I do I get this message when it is looking for versions of Minecraft.

List update failed:
Job 'Download of meta file net.minecraft/index.json' failed to process:
https://meta.multimc.org/v1/net.minecraft/index.json
----------------------------------------------

What should happen:
I would guess that the program would download a version of Minecraft and add it in.
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. I'm not sure that this can be recreated. I believe I might be a special case.

Suspected cause:
My computer might not be able to run the program anymore.
---------------------------

Logs:
----------------------------
paste.ee key:  uWnglW7uFfqKuAq1ECjODONbTKbTTZW4Vso569UBL

**Comment by Zetabite** [comment] 2019-12-20 21:43
can you pls link the correct paste.ee link, this one does not exist/link to the correct log.

**Comment by peterix** [comment] 2020-01-08 05:02
macOS 10.9 has broken SSL libraries that don't work with Qt well

**Comment by phit** [comment] 2021-03-09 22:21
Duplicate of https://github.com/MultiMC/MultiMC5/issues/2443

**Closed by phit** 2021-03-09 22:21 UTC
Labels: bug, system: macOS
