### ISSUE TITLE
Cant download critical mc files from multimc

### ISSUE THREAD

**Issue by notahumanthatisimportant** [MultiMC/MultiMC5#3915] opened 2021-06-30 21:08 UTC
### Description of bug

I launched an instance of multimc and it gave me this error message "Instance update failed because: Failed to download the assets index:
Job 'Asset index for Impact 4.9 for 1.16.5' failed to process:
https://launchermeta.mojang.com/v1/packages/ad75fb46ff5c89aa5f9c90e12481e963854f9a6e/1.16.json"

### Steps to reproduce

create a new instance of multimc and start it

### Suspected cause

I have no clue

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by jamierocks** [comment] 2021-06-30 21:42
I'm unable to reproduce with the given reproduction steps.

**Comment by jamierocks** [comment] 2021-07-13 16:24
I'm going to close this issue as unable to reproduce and no further comments have been made.

**Closed by jamierocks** 2021-07-13 16:24 UTC
Labels: maybe-bug
