### ISSUE TITLE
Client Compiles fine but install throws Error 1

### ISSUE THREAD

**Issue by Saegusae** [MultiMC/MultiMC5#1761] opened 2016-12-28 15:23 UTC
System Information
-----------------------------
MultiMC version: git-develop

Operating System: Ubuntu GNOME 16.10

Summary of the issue or suggestion:
----------------------------------------------
The client cloned from the latest develop branch compiles fine but the install always throws an error ID 1 with the description "fixup_bundle: not a valid bundle"

What should happen:
------------------------------
The client should install fine

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Do the steps as stated in BUILD.md

2. Try to install the compiled code

3. ???

4. Profit.

Suspected cause:
---------------------------
Something wrong with my system setup, still worth mentioning tho.

Logs/Screenshots:
----------------------------

```
[100%] Built target MultiMC
Install the project...
-- Install configuration: ""
-- Installing: /home/saegusa/MultiMC/install/bin/MultiMC
-- Removed runtime path from "/home/saegusa/MultiMC/install/bin/MultiMC"
-- Up-to-date: /home/saegusa/MultiMC/install/./MultiMC
-- Installing: /home/saegusa/MultiMC/install/bin/jars/JavaCheck.jar
-- Installing: /home/saegusa/MultiMC/install/bin/jars/NewLaunch.jar
-- Up-to-date: /home/saegusa/MultiMC/install/plugins/imageformats
-- Up-to-date: /home/saegusa/MultiMC/install/plugins/imageformats/libqjpeg.so
-- Up-to-date: /home/saegusa/MultiMC/install/plugins/imageformats/libqico.so
-- Up-to-date: /home/saegusa/MultiMC/install/plugins/imageformats/libqsvg.so
-- Up-to-date: /home/saegusa/MultiMC/install/plugins/imageformats/libqgif.so
-- Up-to-date: /home/saegusa/MultiMC/install/plugins/iconengines
-- Up-to-date: /home/saegusa/MultiMC/install/plugins/iconengines/libqsvgicon.so
-- Up-to-date: /home/saegusa/MultiMC/install/plugins/platforms
-- Up-to-date: /home/saegusa/MultiMC/install/plugins/platforms/libqxcb.so
-- Up-to-date: /home/saegusa/MultiMC/install/plugins/platforms/libqeglfs.so
-- fixup_bundle
--   app='/home/saegusa/MultiMC/install/bin/MultiMC'
--   libs='/home/saegusa/MultiMC/install/plugins/platforms/libqxcb.so;/home/saegusa/MultiMC/install/plugins/platforms/libqeglfs.so;/home/saegusa/MultiMC/install/plugins/iconengines/libqsvgicon.so;/home/saegusa/MultiMC/install/plugins/imageformats/libqjpeg.so;/home/saegusa/MultiMC/install/plugins/imageformats/libqico.so;/home/saegusa/MultiMC/install/plugins/imageformats/libqsvg.so;/home/saegusa/MultiMC/install/plugins/imageformats/libqgif.so'
--   dirs='/usr/lib/x86_64-linux-gnu;/usr/lib/x86_64-linux-gnu/qt5/libexec;/home/saegusa/MultiMC/build;/home/saegusa/MultiMC/build'
-- warning: *NOT* handled - not .app dir, not executable file...
CMake Error at /home/saegusa/MultiMC/src/cmake/BundleUtilities.cmake:668 (message):
  error: fixup_bundle: not a valid bundle
Call Stack (most recent call first):
  application/install_prereqs.cmake:24 (fixup_bundle)
  application/cmake_install.cmake:84 (include)
  cmake_install.cmake:49 (include)


Makefile:85: recipe for target 'install' failed
make: *** [install] Error 1

```

**Comment by nikhiljha** [comment] 2016-12-30 17:16
What version of cmake do you have? Try updating it and try to build again with latest source.

**Comment by Saegusae** [comment] 2016-12-31 16:23
I tried with both cmake 3.2.2 and cmake 3.7,1 though

**Comment by TheDoctorsLife** [comment] 2017-01-03 17:57
Maybe this has some hold as to whats going on? 
``warning: *NOT* handled - not .app dir, not executable file...`` 
Maybe it wants to be on windows/OSX and doesn't like linux. (if this is the case, why? It should install just fine on linux.) Will try to investigate once I get home.

**Comment by bearbin** [comment] 2017-08-09 13:26
#1780 duplicates this issue. Perhaps this issue should be closed, as the other one has a fix.

**Comment by SirDoctors** [comment] 2017-08-26 18:04
Yep, that issue appears to be a dupe of this one, however seeing how that issue seems to figured out the cause I'll close this in favor of #1780 

TD;LR Go to #1780 if your still experiencing this issue.

**Closed by SirDoctors** 2017-08-26 18:04 UTC
