### ISSUE TITLE
I cant add account

### ISSUE THREAD

**Issue by AstralMonkeyG** [MultiMC/MultiMC5#3561] opened 2021-01-28 20:19 UTC
I cant put my new account in multi mc, it says Invalid credentials. Invalid username or password, same as its all correct
note: ik ik i accidentally deleted everything before reading so i will make a new post

**Comment by AstralMonkeyG** [comment] 2021-01-28 21:35
start of this year, ik microsoft account yes

**Comment by Zetabite** [comment] 2021-01-28 21:50
then thats why. MS accounts arent supported yet.

**Comment by AstralMonkeyG** [comment] 2021-01-28 21:53
when will they be

**Comment by phit** [comment] 2021-01-28 21:56
when mojang signs off on any way for third party launcher to use them, this is out of multimc's control

**Comment by AstralMonkeyG** [comment] 2021-01-28 22:29
not mojang, but microsoft, and dont think they will do it so soon

**Comment by Zetabite** [comment] 2021-01-28 22:32
mojang/microsoft, in its base the same the same. it will be soon, but we dont know how soon. but we have peterix, so we know once its decided

**Comment by HellKing666** [comment] 2021-01-29 04:12
i ran into the same problem, I thought it was on my end since I changed my password recently. So I can't use any minecraft mod launchers that ask for account details, because they aren't supported yet?
i've been bouncing between modpack launchers and none of them work, i'm at the end of my rope right now.

**Comment by AverageComet250** [comment] 2021-01-29 15:19
The only way to use a modpack is to copy the mods folder into the official `.minecraft` folder after installing forge in the vanilla launcher @HellKing666

**Comment by bubbelbadHD** [comment] 2021-02-09 13:44
I have mojang account but it still doesnt login

**Comment by AverageComet250** [comment] 2021-02-09 13:48
Do you use username or email? @bubbelbadHD

**Comment by Zetabite** [comment] 2021-02-09 14:07
> I have mojang account but it still doesnt login

are you sure?

**Comment by bubbelbadHD** [comment] 2021-02-12 13:15
Yep

**Comment by capesean** [comment] 2021-03-02 12:56
@peterix any update on this? I just bought Minecraft on the weekend so my daughter can play with her friends, who use MMC, but now it seems she's unable to join them. I'm requesting a refund from Mojang as I can't get it to work with the Microsoft account.

**Comment by jotoho** [comment] 2021-03-02 13:00
@capesean This launcher is not an official mojang product. Use the vanilla launcher for now if you want to use the new account so badly.

**Comment by capesean** [comment] 2021-03-02 13:37
> @capesean This launcher is not an official mojang product. Use the official vanilla launcher for now if you want to use the new account so badly.

Yes, I'm aware of that. Given the popularity of MultiMC though, I'd think they (Mojang/Microsoft) would be quite motivated to fix the login issue. And from what I can tell, there's not a lot of communication on if/when this might happen, which would help me to decide whether to invest the time in finding another launcher, or learning how to do the same in vanilla launcher (for my kids - I don't play it), or just waiting a few weeks(?) until it's resolved. I'm just asking for some communication, really.

**Comment by wb1016** [comment] 2021-03-03 05:07
duplicate of #3392 
should be closed

**Comment by AverageComet250** [comment] 2021-03-03 10:36
@capesean WHY exactly do you want use multimc instead of the official launcher?

If it's for modpack support, then just copy the mods folder inside the modpack zip into your .minecraft and install forge from their web page.

**Comment by capesean** [comment] 2021-03-03 12:02
It's for my kids (youngest is 6); they are familiar with how to use MultiMC, but not with the official launcher. I guess I'll have to learn and then teach/show them if MultiMC can't be used any longer.

**Comment by AverageComet250** [comment] 2021-03-03 14:16
The official launcher isn't too hard to use. It's actually pretty basic compared to multimc. I think that learning how to use it and teaching your kids isn't necessary; They should easily be able to learn it themselves.

**Closed** 2021-03-03 16:48 UTC
Labels: other

**Comment by bubbelbadHD** [comment] 2021-03-05 12:55
you can download official minecraft launcher free from minecraft.net/en-us/download or minecraft.net/en-us/download
