### ISSUE TITLE
Error: Could not find or load main class org.multimc.EntryPoint (1.12.2)

### ISSUE THREAD

**Issue by jake21212** [MultiMC/MultiMC5#2835] opened 2019-09-03 05:26 UTC
System Information
-----------------------------
MultiMC version:

Operating System:

Summary of the issue or suggestion:
----------------------------------------------

What should happen:
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.

2.

3.

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by Janrupf** [comment] 2019-09-26 19:00
Empty and duplicate of #2836

**Closed** 2020-01-08 12:43 UTC
