### ISSUE TITLE
Only one copy of any given instance can launch at a time

### ISSUE THREAD

**Issue by CommunistWitchDoctor** [MultiMC/MultiMC5#526] opened 2014-10-03 08:39 UTC
As stated in title, attempting to launch a second copy of a given instance only results in a crash

**Comment by peterix** [comment] 2016-02-03 01:32
I will consider this in the upcoming launching rewrite. But right now, this is ``works as intended''. It protects users from disaster.

I am reclassifying this as an idea and moving it to workflowy (Next -> Separate out launcher part): https://workflowy.com/s/2EyDMcp7CU

**Comment by peterix** [comment] 2018-02-14 20:25
Really, works as intended.

**Closed by peterix** 2018-02-14 20:25 UTC
Labels: multimc: feature
