### ISSUE TITLE
MultiMC 5.04: Console window freezes randomly

### ISSUE THREAD

**Issue by Win7yes** [MultiMC/MultiMC5#375] opened 2014-07-16 01:04 UTC
I started up my modded 1.6.4 Instance and while Minecraft was loading, the console was totally right and no problems at all. But when I got on a world, it started freezing up. I think it is happening when I press ESC and go to the Game Menu. Right now, I already closed the instance, and the console is still frozen, resulting in not being able to get back to the main MultiMC window.

Steps to reproduce (Maybe):
1-Open a Minecraft Instance, Maybe a modded one will only do the thing (lol the Thing)
2-Get in a world and check the console window after playing a bit
3-It might be frozen (Not Responding) or not. I don't know
4-???
Little Details:
OS: Windows 8 x64, Java Version: Unknown, Minecraft Version: 1.6.4
Issue ends here (lol)

**Comment by peterix** [comment] 2015-08-15 20:40
/me slowly backs away and starts running...

Now, seriously. I'm sorry I haven't responded to this in such a long time.

However, I also cannot reproduce the issue, nor has anyone else reported it. On top of that, the console and launch process in general has been changed multiple times since you reported this.

Therefore, closing.

**Closed** 2015-08-15 20:40 UTC
Labels: bug
