### ISSUE TITLE
Ubuntu 14.04 LTS Instances Icon Overlapping and always there when MC is opened

### ISSUE THREAD

**Issue by lanman14444** [MultiMC/MultiMC5#401] opened 2014-07-27 19:39 UTC
MultiMC version: .5-dev303 on lin64
Distro: Ubuntu
Desktop Enviroment: Ubuntu (default)
Java version: 1.7.0
Issue: When you have a Instance open the Icon you set is always in the top left hand corner. Also, it overlaps The exit button even if it isn't the MInecraft one.
![ss-15-00-19](https://cloud.githubusercontent.com/assets/1356140/3714929/ac5eebde-15c5-11e4-81d0-1b64fdbc0a83.png)
![ss-15-00-33](https://cloud.githubusercontent.com/assets/1356140/3714931/ac5fd59e-15c5-11e4-9156-d507ff7fca5b.png)
![ss-15-00-55](https://cloud.githubusercontent.com/assets/1356140/3714930/ac5fd5da-15c5-11e4-8727-e1a880d5ed65.png)

**Comment by peterix** [comment] 2015-08-15 18:00
Duplicate of #403 ... and the other way around. But this has less comments.

**Closed** 2015-08-15 18:00 UTC
Labels: bug
