### ISSUE TITLE
full screen when setting is not set on

### ISSUE THREAD

**Issue by andsim** [MultiMC/MultiMC5#2129] opened 2018-02-01 01:15 UTC
System Information
-----------------------------
MultiMC version: 0.6.1-1177

Operating System: Windows 10 pro

Summary of the issue or suggestion:
----------------------------------------------
Almost always goes to full screen
when i check for windows setting to be sure it not full screen enable

What should happen:
------------------------------
never go into full screen

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. update to latest java

2. run some instances non-mod

3.

Suspected cause:
---------------------------
java? causing this not sure

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by Dog3403** [comment] 2018-02-01 16:07
Could you please shut down this thread I figured it out awhile ago. Thank you for you help.



Sent via the Samsung Galaxy S7 active, an AT&T 4G LTE smartphone
-------- Original message --------From: andsim <notifications@github.com> Date: 1/31/18  5:15 PM  (GMT-08:00) To: MultiMC/MultiMC5 <MultiMC5@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [MultiMC/MultiMC5] full screen when setting is not set on (#2129) 
System Information
MultiMC version: 0.6.1-1177
Operating System: Windows 10 pro
Summary of the issue or suggestion:
Almost always goes to full screen

when i check for windows setting to be sure it not full screen enable
What should happen:
never go into full screen
Steps to reproduce the issue (Add more if needed):


update to latest java


run some instances non-mod



Suspected cause:
java? causing this not sure
Logs/Screenshots:
Additional Info:

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/MultiMC/MultiMC5","title":"MultiMC/MultiMC5","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/MultiMC/MultiMC5"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"full screen when setting is not set on (#2129)"}],"action":{"name":"View Issue","url":"https://github.com/MultiMC/MultiMC5/issues/2129"}}}

**Comment by peterix** [comment] 2018-02-01 17:23
@Dog3403 I think you meant #2083, and I closed it.

**Comment by peterix** [comment] 2018-02-01 17:24
@andsim did you change the fullscreen setting in game? I think it might be remembering that.

**Comment by andsim** [comment] 2018-02-02 05:41
i have touch any setting until i update java and MultiMC

**Comment by andsim** [comment] 2018-02-02 05:52
wow it was in game setting that i haven't touch they added recently

**Closed** 2018-02-02 11:00 UTC
Labels: game problem

**Comment by Dog3403** [comment] 2019-01-11 23:56
Hey, can you sign this petition? http://chng.it/fbzY85rnfL

Thanks! - James
