### ISSUE TITLE
game will run sometimes 

### ISSUE THREAD

**Issue by dablade11577** [MultiMC/MultiMC5#3511] opened 2021-01-03 20:23 UTC
If you believe your issue to be a bug, please make sure you check the wiki page: https://github.com/MultiMC/MultiMC5/wiki/Report-a-Bug
-->

System Information
-----------------------------
MultiMC version:
0.6.11-11430

Operating System: 
windows 10

Summary of the issue or suggestion:
----------------------------------------------

This happens sometimes, the game will start and run just fine, other times it just wont start and will always get a crash report and will take up to an hour before it starts to start again and run normally with no crashes
What should happen:
------------------------------
start every time

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. launch game

2.

3.

Suspected cause:
---------------------------
mods or bug

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

https://paste.ee/p/dlvTG

[New Paste 1.txt](https://github.com/MultiMC/MultiMC5/files/5762223/New.Paste.1.txt)

Additional Info:
---------------------------
crash report: 
[crash-2021-01-03_13.14.32-client.txt](https://github.com/MultiMC/MultiMC5/files/5762216/crash-2021-01-03_13.14.32-client.txt)

**Comment by jotoho** [comment] 2021-01-03 20:52
The crash is caused by the OpenBlocks mod. You should try asking their developers about it or report 
the issue to them IF it hasn't already been.

(Though there's a good chance that they've stopped supporting the 1.12.2 version, in which case you 
are out of luck if you can't find anything useful on the internet and may have to uninstall that 
mod)

**Comment by dablade11577** [comment] 2021-01-03 21:44
@jotoho alrigh thx ill see what i can do

**Comment by dablade11577** [comment] 2021-01-05 02:05
@jotoho turns out it was the forge version so i installed the previous version and the problem stopped

**Comment by jotoho** [comment] 2021-01-05 02:09
> @jotoho turns out it was the forge version so i installed the previous version and the problem stopped

If your problem is solved then please don't forget to close this issue.

**Closed** 2021-01-06 02:37 UTC
