### ISSUE TITLE
[Suggestion] A way to change instance folder to a custom dir

### ISSUE THREAD

**Issue by MicherGit** [MultiMC/MultiMC5#3766] opened 2021-05-06 22:31 UTC
### Role

I have a polluted instance folder and I want groups to properly separate folders

### Suggestion

Maybe make it so instance groups group them into separate folders too?

### Benefit

Will help keep MultiMC/instances more organized

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by spannerman79** [comment] 2021-05-07 07:33
While this idea is good on paper it isn't much so in practise.

MultiMC is a _portable_ application.  So pushing a change that will create potential **massive** I/O read/writes instead of just appending/changing a single `instgroups.json` file.

Good on paper, bad in practise.

**Comment by Xetaxheb** [comment] 2021-06-10 03:26
Duplicate of https://github.com/MultiMC/MultiMC5/issues/3387

**Closed** 2021-06-10 07:11 UTC
Labels: suggestion
