### ISSUE TITLE
[Feature Request] Modpack updater

### ISSUE THREAD

**Issue by Kitsune-Ultima** [MultiMC/MultiMC5#3685] opened 2021-03-24 18:18 UTC
> Add a note to the instance config to tell which service to pull updates from
> Add a button to update the modpack if a update is available from the above service
> Add a button to manually update the modpack from a zip file
> Detect mods in the update that need updating in the instance and only download the ones in need of updating (removing older versions)

This would make it easier to update packs not only from Twitch, FTB, ATLauncher, or Technic, but also allow private packs (Those received from other people) to be updated without the hassle of creating a new instance, moving files and configs over to the new instance, and deleting the old instance.

**Comment by Forkk** [comment] 2021-03-24 18:28
Duplicate of #2640
and so many others...

**Closed by Forkk** 2021-03-24 18:28 UTC
