### ISSUE TITLE
Skins not working

### ISSUE THREAD

**Issue by Timolino456** [MultiMC/MultiMC5#2226] opened 2018-04-06 15:39 UTC
When I play Minecraft with MultiMC, skins don't load on any game version.
The launcher tells me the skin servers aren't working (see screenshot), but they are according to the page the launcher leads you to when clicking on the icon.

![skins](https://user-images.githubusercontent.com/38137599/38430404-7557b55c-39c1-11e8-9ff7-d322ce45ccc4.PNG)

**Comment by peterix** [comment] 2018-04-06 15:57
Duplicate of https://github.com/MultiMC/MultiMC5/issues/2143
This is already fixed, and it has no effect on the game regardless.

**Closed by peterix** 2018-04-06 15:57 UTC
Labels: duplicate
