### ISSUE TITLE
MultiMC crashes when disk space runs out while downloading Minecraft or modpacks

### ISSUE THREAD

**Issue by Tomodachi94** [MultiMC/MultiMC5#3615] opened 2021-02-19 17:36 UTC
System Information
-----------------------------
MultiMC version: Irrelevant, as this is a suggestion

Operating System: Irrelevant, as this is a suggestion

Summary of the issue or suggestion: Add a handler for when you run out of space when downloading Minecraft versions and modpacks.
----------------------------------------------

**Comment by Zetabite** [comment] 2021-02-19 17:38
There is already a warning in the logs when there is not enough space left.

**Comment by Tomodachi94** [comment] 2021-02-19 17:59
It abruptly crashed was my point @Zetabite.

**Comment by Zetabite** [comment] 2021-02-19 19:15
Not much it can do

**Comment by Tomodachi94** [comment] 2021-02-19 23:09
I'm no expert, but I'm pretty sure you can compare the available disk space to the downloaded file size... (@Zetabite)

**Comment by Forkk** [comment] 2021-03-06 20:45
In the future please fill out the issue form correctly.

**Comment by Tomodachi94** [comment] 2021-03-07 04:54
All other information was irrelevant @Forkk... Why should I give you ketchup when you like mustard? (metaphor)

**Comment by spannerman79** [comment] 2021-03-07 07:18
Curse modpacks do not include that sort of info into their pack jsons (manifest.json).

Until Curse gives a way to provide that in a _sane_ way this would be near impossible to impliment.

As a test to see, the most recently updated/created modpack on Curse is https://www.curseforge.com/minecraft/modpacks/nexus-war/files/3226115

In that `manifest.json` is the following;

```json
{
  "minecraft": {
    "version": "1.7.10",
    "modLoaders": [
      {
        "id": "forge-10.13.4.1558",
        "primary": true
      }
    ]
  },
  "manifestType": "minecraftModpack",
  "manifestVersion": 1,
  "name": "Nexus War",
  "version": "1.1",
  "author": "",
  "files": [
    {
      "projectID": 235577,
      "fileID": 2267308,
      "required": true
    },
    {
      "projectID": 228815,
      "fileID": 2765573,
      "required": true
    },
    {
      "projectID": 73510,
      "fileID": 2302354,
      "required": true
    },
    {
      "projectID": 229084,
      "fileID": 2480016,
      "required": true
    },
    {
      "projectID": 228816,
      "fileID": 2386733,
      "required": true
    },
    {
      "projectID": 223794,
      "fileID": 2245762,
      "required": true
    },
    {
      "projectID": 74924,
      "fileID": 2264244,
      "required": true
    },
    {
      "projectID": 69162,
      "fileID": 2388750,
      "required": true
    },
    {
      "projectID": 228756,
      "fileID": 2230908,
      "required": true
    },
    {
      "projectID": 69163,
      "fileID": 2388758,
      "required": true
    },
    {
      "projectID": 227083,
      "fileID": 2224857,
      "required": true
    },
    {
      "projectID": 74072,
      "fileID": 2264246,
      "required": true
    },
    {
      "projectID": 222880,
      "fileID": 2388752,
      "required": true
    },
    {
      "projectID": 222211,
      "fileID": 2302312,
      "required": true
    },
    {
      "projectID": 225561,
      "fileID": 2264383,
      "required": true
    },
    {
      "projectID": 222213,
      "fileID": 2262089,
      "required": true
    },
    {
      "projectID": 243788,
      "fileID": 2819851,
      "required": true
    },
    {
      "projectID": 227443,
      "fileID": 2388756,
      "required": true
    },
    {
      "projectID": 32274,
      "fileID": 2367915,
      "required": true
    },
    {
      "projectID": 42794,
      "fileID": 2754894,
      "required": true
    },
    {
      "projectID": 223094,
      "fileID": 2210792,
      "required": true
    },
    {
      "projectID": 229060,
      "fileID": 2338148,
      "required": true
    },
    {
      "projectID": 334787,
      "fileID": 2758834,
      "required": true
    },
    {
      "projectID": 221826,
      "fileID": 2495406,
      "required": true
    },
    {
      "projectID": 73488,
      "fileID": 2230518,
      "required": true
    }
  ],
  "overrides": "overrides"
}
```

Do you see any sort of file size info being stored?  I don't.

So until Curseforge/etc enforce that info it would be near impossible to impliment to be able to pull that info quickly before the start of downloads of mods.

**Comment by peterix** [comment] 2021-03-07 12:21
To be honest, MultiMC never checks disk space.

**Comment by phit** [comment] 2021-03-09 21:09
Duplicate of https://github.com/MultiMC/MultiMC5/issues/2788

**Closed by phit** 2021-03-09 21:09 UTC
Labels: bug
