### ISSUE TITLE
The MultiMC Debian/Ubuntu package will break with upcoming distro versions (qt5-default removal, Java 8 deprecation)

### ISSUE THREAD

**Issue by chloecormier** [MultiMC/MultiMC5#3413] opened 2020-11-02 11:20 UTC
System Information
-----------------------------
MultiMC version: N/A (The relevant version of the Debian package is 1.4-1)

Operating System: Debian Sid/Unstable

Summary of the issue or suggestion:
----------------------------------------------
The `qt5-default` package that MultiMC depends on is being removed after a long time of packages in the Debian/Ubuntu archive already not being allowed to depend on it. The MultiMC package will soon be uninstallable with Debian 11 and Ubuntu 21.04, and it already is uninstallable with Debian Sid/Unstable.

MultiMC also recommends the `openjdk-8-jre` package which is bad practice, and won't work at all in Debian which has deprecated it outside of unstable. Similarly, Ubuntu is only carrying it in the `universe` repo (as a consequence of inheriting its packages from Debian Unstable) so it lacks Canonical support.

What should happen:
------------------------------
The MultiMC package should depend on the specific Qt libraries it requires, instead of `qt5-default`. As far as I can tell, this should just be `libqt5widgets5 libqt5gui5 libqt5network5 libqt5core5a libqt5xml5 libqt5concurrent5`

It should also recommend the `default-jre` package instead of `openjdk-8-jre`. This points to the Java runtime recommended for the user's distro version and CPU architecture, which will usually be Java 11 on Debian 10+ or Ubuntu 18.04+ (which should still be compatible with any recent Minecraft/Forge/Fabric version), or Java 8 on Debian <9 or Ubuntu <16.04.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Install an instance of Debian Unstable [(instructions)](https://wiki.debian.org/DebianUnstable).

2. Download the 1.4-1 version of the MultiMC .deb package.

3. Attempt to install.

**Comment by shinji257** [comment] 2020-11-03 14:26
openjdk-8-jre is recommended due to Forge and other mods requiring Java 8.  In addition Minecraft still comes packaged with that version by default so while vanilla does work with Minecraft there is always the possibility of unexpected behavior.

**Comment by QuImUfu** [comment] 2020-11-03 18:49
Dropping java 8 support basically equals dropping modded minecraft support (especially backward compatibility). (Most modpacks are made for minecraft 1.12.*) Debian/Ubuntu might wanna overthink that, given Minecaft is one of the biggest games in existence and openjdk java 8 is AFAIK still maintained.  
Otherwise users of those distros will need to download and install java from adoptopenjdk or similar.

**Comment by chloecormier** [comment] 2020-11-06 01:51
Java 11 works fine for Forge 1.15+ so incompatibility will be less and less of a problem with time presumably. My understanding is that vanilla Minecraft also does officially support all newer Java versions, even though it comes bundled with Java 8 ([judging by this Dinnerbone comment](https://www.reddit.com/r/Minecraft/comments/88xrn8/minecraft_still_uses_java_8_meanwhile_im_sitting/dwnzedv/)).

Still, if it's too early to recommend Java 11 now, that's totally cool and it might be fine in a year or so. Keeping the Java 8 dependency will be fine as long as the package is only targeting Ubuntu since it'll stick around in Ubuntu as long as Debian Unstable carries it, and Debian Unstable will carry it as long as it's necessary to bootstrap Kotlin.

**Comment by shinji257** [comment] 2020-11-06 02:32
I guess at the end of the day as long as we are supporting current Forge by default it should be ok and people could download Java 8 via another distribution.  Either getting the archive from Oracle directly or using AdoptOpenJDK instead.

Also it might be possible that issues with older Forge is due to the LaunchWrapper being used.  Apparently the default one typically included didn't support past Java 8 but there is another one that does that the Optifine dev started including back in 2018.
https://github.com/sp614x/optifine/issues/1376#issuecomment-417884401

**Comment by kb-1000** [comment] 2020-11-06 10:02
You're essentially stating that old minecraft versions are not a thing anymore.
This is obviously wrong, lots of people still play the old versions.
Forking launchwrapper sounds illegal, that thing is all rights reserved, also, I heard of the fork breaking compatibility of optifine with multimc without using a modloader like forge or fabric.

**Comment by peterix** [comment] 2020-11-06 10:51
Debian should consider not breaking compatibility.

**Comment by peterix** [comment] 2020-11-06 10:52
OpenJDK 11 is a poorly packaged, poorly built, mess. It's affected by compiler bugs and I cannot recommend its use on any distribution in its current form.

**Comment by chloecormier** [comment] 2020-11-06 13:37
It's absolutely fine to keep the Java 8 dependency for now if devs think that would be best. I think the Qt issue is lot more imperative anyhow.

**Comment by phoe** [comment] 2020-11-09 08:58
This is an issue with debian sid; qt5-default installed from buster conflicts with the QT5 GLES-enabled libraries that are now in live sid repositories. I need to use the generic installation for the time being instead of using the deb package.

**Comment by chloecormier** [comment] 2020-11-09 16:30
The GLES-enabled Qt5 libraries are optional variants, the regular packages are still there and work as before. `qt5-default` has been removed from the Debian archive entirely in any branch newer than Buster and it's normal for it to be removed on upgrade. The current .deb package does work fine if it's manually repacked with a change to depend on the specific Qt5 libraries instead of `qt5-default`, so it's not an issue with Debian Sid.

**Comment by andrewathalye** [comment] 2021-01-17 19:17
As an update, this change has now been moved into Debian Testing as of a few weeks ago, so anyone trying to install there would have to use the tgz.

**Comment by Zipdox** [comment] 2021-01-24 00:46
Should've used GTK...

**Comment by chloecormier** [comment] 2021-01-24 07:44
Not sure what the connection between this and the GTK/Qt war is. It's strictly a packaging issue. It's good practice in any case to only depend on the specific components of a toolkit that you use rather than the entire toolkit, GTK would be no exception.

**Comment by Zipdox** [comment] 2021-01-26 12:15
> Not sure what the connection between this and the GTK/Qt war is. It's strictly a packaging issue. It's good practice in any case to only depend on the specific components of a toolkit that you use rather than the entire toolkit, GTK would be no exception.

How difficult would this be to fix? Is it gonna take a lot of effort?

**Comment by jamierocks** [comment] 2021-01-26 15:22
> > Not sure what the connection between this and the GTK/Qt war is. It's strictly a packaging issue. It's good practice in any case to only depend on the specific components of a toolkit that you use rather than the entire toolkit, GTK would be no exception.
> 
> How difficult would this be to fix? Is it gonna take a lot of effort?

I'm sorry, what are you asking here?

**Comment by Zipdox** [comment] 2021-01-26 20:24
> I'm sorry, what are you asking here?

How difficult would it be to fix the packaging issue? It it a case of "nobody has gotten to it" or will it require a massive overhaul?

**Comment by Janrupf** [comment] 2021-01-26 20:49
Well, the problem is that in fact you should not depend on Java 9 or higher or even suggest it. The Qt situation is not a problem as you said yourself, it can quickly be fixed. Java 8 being dropped is more a problem

**Comment by Zipdox** [comment] 2021-01-26 20:49
Ok I fixed it: https://github.com/MultiMC/MultiMC5/pull/3556
I tested it and it worked fine.

**Comment by Zetabite** [comment] 2021-01-26 20:54
Have you tested modded on forge?

**Comment by Janrupf** [comment] 2021-01-26 20:55
The Java recommended version has not changed with the PR, so no breakage expected there

**Comment by chloecormier** [comment] 2021-01-27 01:44
Yeah, it might be worth splitting the Java problem into a separate GH issue, and closing this one once that pull gets merged. The Java issue requires a decision between distro compatibility and compatibility with older Forge versions, and it'll probably need a different timeframe for discussing it and figuring out a fix.

That said, I'm also interested now in what @peterix specifically meant when talking about poor packaging and compiler bugs in the OpenJDK 11 Debian package. Have those issues been forwarded upstream to where the Debian maintainers are aware of them? That sounds like a prerequisite to even talk about fixing the Java issue.

**Comment by Zipdox** [comment] 2021-01-27 15:38
> Have you tested modded on forge?

Yes but with openjdk-8-jre. I don't think installing that is too hard to pull off. You can just download the openjdk-8-jre and openjdk-8-jre-headless deb packages manually and install them. Alternatively a PPA can be used as stated in https://stackoverflow.com/questions/57031649/how-to-install-openjdk-8-jdk-on-debian-10-buster

**Comment by Zetabite** [comment] 2021-01-27 15:39
Yeah no worries, just making sure that everything is going nicely :D

**Comment by andrewathalye** [comment] 2021-01-27 16:39
Maybe one potential solution (I know this would be additional work, so sorry) for Linux users would be to depend on default-jre and only the required qt packages (which also existed in previous Debian / Ubuntu versions so this should not cause compat issues) and then display a message when the user tries to start a <1.9 version letting them know that Java 8 is required and linking to java.com or AdoptOpenJDK. It is actually rather difficult to find an up-to-date build of OpenJDK 8 for Debian >=10 since it is no longer included by default in the repositories, so Oracle JDK might actually be preferred in terms of ease of installation for most users, although the licensing is obviously not ideal here.

**Comment by andrewathalye** [comment] 2021-01-27 16:42
I have personally not experienced any issues with openjdk-11-jdk on Debian Bullseye, both for development and running Minecraft, however that is not to discount any packaging or compiler issues, just that they are likely not too severe so as to impede safe packaging.

**Comment by kb-1000** [comment] 2021-01-27 17:13
Java 11 is not suitable for any version older than 1.13 at all, and will randomly crash with a ConcurrentModificationException for at least some newer versions. Thus: no.

**Comment by andrewathalye** [comment] 2021-01-27 17:43
Sorry, I've updated my comment to reflect that. It is however perfectly fine for >=1.13 with the Fabric mod Voyager installed, which fixes the CME. Java 8 is still supported for now so it would be ideal to find a way to include that, but seeing as Debian appear to have made their decision about Java 8 efforts should probably be focused on finding the best compromise to support Java 11 or not including Java at all. I guess a PPA could also be automatically added which includes a version of Java 8 like the official Minecraft launcher does, but that might cause package conflicts.

**Comment by chloecormier** [comment] 2021-01-28 06:11
> It is however perfectly fine for >=1.13 with the Fabric mod Voyager installed, which fixes the CME.

Worth mentioning that this fix has been included by default in Fabric Loader for a while as well, so all Fabric 1.16 instances work fine with recent Java versions without needing to install anything extra: https://github.com/FabricMC/fabric/pull/1176

Ultimately, it's an issue of retaining compatibility for older versions of the game, which will definitely be a major concern as long as 1.12 is "the version for modding." Maybe it'll be easier to bring in a newer Java version once the most popular version of the game for modding is >=1.16.

Right now, the Ubuntu package (with the Qt fix, at least) works fine on Debian since openjdk-8-jre is only a recommendation and not a dependency. It just means that no Java version will be brought in at all. Since Ubuntu is still carrying openjdk-8-jre, perhaps it would be good to split the Debian and Ubuntu packages? The Ubuntu package could continue depending on Java 8 for maximum compatibility, and the Debian package could depend on default-jre, just so it brings in _something_ at least.

**Comment by Zipdox** [comment] 2021-01-28 08:49
> Ultimately, it's an issue of retaining compatibility for older versions of the game, which will definitely be a major concern as long as 1.12 is "the version for modding." Maybe it'll be easier to bring in a newer Java version once the most popular version of the game for modding is >=1.16.

There will always be a community of 1.12.2 and 1.8.9 players because of detrimental game changes in recent versions. 1.8.9 obviously for PvP servers. 1.12.2 is the only option for some very large survival servers since 1.13 has a massive performance impact. It's the only option for servers that aren't willing to introduce game breaking optimizations.

> Right now, the Ubuntu package (with the Qt fix, at least) works fine on Debian since openjdk-8-jre is only a recommendation and not a dependency. It just means that no Java version will be brought in at all. Since Ubuntu is still carrying openjdk-8-jre, perhaps it would be good to split the Debian and Ubuntu packages? The Ubuntu package could continue depending on Java 8 for maximum compatibility, and the Debian package could depend on default-jre, just so it brings in _something_ at least.

Maybe, but I think a better solution is to warn the user in MultiMC itself if java 8 isn't installed. Then just link to a wiki page in this repo with installation instructions or something. It could be left in the recommends so that it is installed if available.

**Comment by Zipdox** [comment] 2021-01-31 17:23
@chloecormier Any idea as to when the PR will be merged?

**Comment by chloecormier** [comment] 2021-02-01 19:54
@Zipdox I'm not involved with the MultiMC project and can't merge it myself, I apologize.

To respond to your previous comment though, I do like the idea of warning users who lack Java 8 a lot and I think that'd be the best compromise. It means you could bring in default-jre, which is probably suitable for a majority of players, while still warning them about what won't work and how they can fix it in case they want to play on an older game version. 

That said, I don't think both should be in the recommends, the Java runtime is large and overall it becomes a _huge_ download if you're effectively bringing in both Java 8 and Java 11 during the MultiMC installation on Ubuntu systems. 

As far as how users should go about manually installing Java 8 on Debian Stable, it sounds like the best way to do that is to add the AdoptOpenJDK Apt repository, so maybe the warning could link to instructions based on that: https://stackoverflow.com/questions/57031649/how-to-install-openjdk-8-jdk-on-debian-10-buster

**Comment by kb-1000** [comment] 2021-02-01 20:00
> It means you could bring in default-jre, which is probably suitable for a majority of players, while still warning them about what won't work and how they can fix it in case they want to play on an older game version.

I disagree. That makes it too hard to just _play_, and people are having issues with the Java 11 build from Ubuntu in combination with Minecraft (ABI incompatibility in relation to LWJGL where none needs to be, it works just fine with other builds).
Either way, to my knowledge the dependency will be completely dropped somewhen in the future, replacing it with Mojang's Java runtime (used by Mojang launcher)

**Comment by chloecormier** [comment] 2021-02-01 20:03
> and people are having issues with the Java 11 build from Ubuntu in combination with Minecraft (ABI incompatibility in relation to LWJGL where none needs to be, it works just fine with other builds).

Is that an Ubuntu-specific issue? I've never had any problems with the Java 11 build from Debian anyhow, but those two builds should be extremely similar.

Regardless, if the dependency is replaced with the Mojang Java runtime then that'd be a great way to deal with this without having to compromise.

**Comment by kb-1000** [comment] 2021-02-01 20:05
> Is that an Ubuntu-specific issue?

That's very well possible.
https://bugs.launchpad.net/ubuntu/+source/gcc-7/+bug/1764701
https://bugs.launchpad.net/ubuntu/+source/openjdk-lts/+bug/1838740

**Comment by jamierocks** [comment] 2021-02-01 20:08
I think its worth noting that an effective fix for the Java issues will come when MultiMC uses the appropriate Mojang JRE (see the todo channel on the Discord).
![](https://i.jamierocks.uk/mmxxi/rXq8ljAjJC.png)

**Comment by peterix** [comment] 2021-02-01 21:38
Indeed. That is the intention here.

MultiMC will have to depend on the dependencies of a 'generic JRE', not a specific JRE. What is shipped with the OS will be of much lesser importance.

The Qt issue is a real one.

**Comment by Zipdox** [comment] 2021-02-02 12:09
> Indeed. That is the intention here.
> 
> MultiMC will have to depend on the dependencies of a 'generic JRE', not a specific JRE. What is shipped with the OS will be of much lesser importance.
> 
> The Qt issue is a real one.

Indeed. Can anyone higher up merge the PR? It's really annoying to have to send people the deb I built myself.

**Comment by peterix** [comment] 2021-03-23 21:59
Does this work for you?
https://files.multimc.org/downloads/multimc_1.5-1.deb

**Comment by peterix** [comment] 2021-03-23 22:19
Anyway, tested on 20.10 and this seems fine now.

**Closed by peterix** 2021-03-23 22:19 UTC
Labels: bug, packaging, system: Linux

**Comment by davralin** [comment] 2021-06-30 07:04
> Does this work for you?
> https://files.multimc.org/downloads/multimc_1.5-1.deb

I might be blind here @peterix - but has this file been released somewhere besides this post?

I can't seem to find any deb-packages since release 0.6.8, which had multimc_1.4-1.deb - and that doesn't work.

I can confirm that apt seems happy with the 1.5-1.deb-file on debian bullseye too, 1.4-1.deb didn't.

**Comment by coldReactive** [comment] 2021-08-28 01:36
> Does this work for you?
> https://files.multimc.org/downloads/multimc_1.5-1.deb

You should alter the download/install page on the multimc website to say qt-default is no longer needed if this does indeed work. Since The reason for qt5-default's removal is clear, and it will never be coming back: https://askubuntu.com/questions/1335184/qt5-default-not-in-ubuntu-21-04/1337334#1337334

**Comment by davralin** [comment] 2021-08-28 13:26
In case someone weren't aware - Debian Bullseye has also been released, so for all intents and purposes, this change is now live.

**Comment by kolegge3** [comment] 2022-06-14 13:46
@chloecormier why are u in minecraft u should be in dead craft cause u will die soon xD
![ezgif-4-53ffca5be9](https://user-images.githubusercontent.com/107486247/173592748-7b30590e-be26-4d61-9265-c9ef4a5eab58.gif)
![re](https://user-images.githubusercontent.com/107486247/173592758-6fa2ed36-2e9d-4894-aec3-6924b2942c49.png)
