### ISSUE TITLE
NEI and CodeChickemCore are not recognized

### ISSUE THREAD

**Issue by skullzbeast** [MultiMC/MultiMC5#1028] opened 2015-05-30 18:59 UTC
When using MultiMC 0.4.6, and Minecraft 1.3.2, NEI and CodeChickenCore go into the coremods folder. When the game loads, the mods button on the menu shows that the mods are there, bet when one opens a world, NEI does not show up when the inventory is opened, even after pressing 'o'. I have tried this with several forge versions. This also effects all versions up until 1.5.

**Comment by peterix** [comment] 2015-05-30 22:11
Known issue, already fixed in develop.

If you set the update channel to develop and update, the issue should be gone. Note that this is pretty much a pre-release version, so I'd advise switching back to stable when 0.4.7 is released (should be soon).

**Comment by peterix** [comment] 2015-05-30 22:12
BTW: the cause of that is that these old versions of CCC and NEI don't recognize the main minecraft jar, unless it's named exactly 'minecraft.jar'. MultiMC stable uses 'temp.jar'.

**Closed** 2015-05-31 18:07 UTC
Labels: bug
