### ISSUE TITLE
SSL Handshake failed when logging in with MC - macOS 10.15.1

### ISSUE THREAD

**Issue by inndoez-lol** [MultiMC/MultiMC5#3354] opened 2020-09-24 17:35 UTC
When I log into MultiMC with an account, it says "SSL Handshake failed".

My OS is: macOS Catalina 10.15.1.

Here's the log file for the last run where it errored.

https://pastebin.com/raw/h51AE742

**Comment by inndoez-lol** [comment] 2020-09-30 21:59
Can someone please help

**Comment by andrewathalye** [comment] 2020-11-10 18:41
Did you run MultiMC on a network that could be filtering SSL traffic? Sometimes school networks and similar organisations attempt to block traffic from specific SSL sites or redirect it, which usually leads to this sort of error. You may also need to install updated root certificates, but I'm not familiar with the process for that on macOS unfortunately.

**Comment by Scotsguy** [comment] 2021-03-07 17:52
Duplicate of #2085

**Closed by Scotsguy** 2021-03-07 17:52 UTC
