### ISSUE TITLE
No java versions found 

### ISSUE THREAD

**Issue by alexjustdiedrip** [MultiMC/MultiMC5#2953] opened 2020-01-01 18:12 UTC
Whenever I go onto multimc a screen comes up telling me to select a version of java, but there are none there. I have java downloaded and when I click the auto detect button it just keeps saying 
Error: unable to access jarfile

**Comment by jredfox** [comment] 2020-01-04 06:46
dupe of #2949

**Comment by peterix** [comment] 2020-01-08 03:02
It would be ebtter if you provided some information. This is meaningless.

If you are still interested in an answer, open a new issue and provide:
* What OS are you using
* How did you install MultiMC and where are its files
* Screenshot of the `jars` folder - it's in the MultiMC folder. Like this one:
  ![image](https://user-images.githubusercontent.com/203326/71946990-a5eb3a00-31cb-11ea-9782-ed106c5ebc08.png)
  On linux, it may be `bin/jars/` instead.

**Closed by peterix** 2020-01-08 03:02 UTC
