### ISSUE TITLE
MultiMc not staring my profile, it fails after a few moments.

### ISSUE THREAD

**Issue by Wraithcraft** [MultiMC/MultiMC5#1674] opened 2016-09-28 00:28 UTC
I came back to MultiMC to test an idea for a modpack, and when I dragged all the mods into the folder, and installed forge, I was met with an error. I don't know how to fix this, please help!

Logs:
MultiMC version: 0.4.11-751

Minecraft folder is:
instances/HQM Pack /minecraft

Java path is:
C:/Program Files/Java/jre1.8.0_101/bin/javaw.exe

Checking Java version...
Java version is 1.8.0_101!
Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms2048m, -Xmx4092m, -Duser.language=en, -jar, C:/Users/Ethan/Downloads/Keep/MultiMC/jars/NewLaunch.jar]

Minecraft process ID: 3536

Using onesix launcher.

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  C:/Users/Ethan/Downloads/Keep/MultiMC/instances/HQM Pack /natives

Traits:
  []

Libraries:
  C:/Users/Ethan/Downloads/Keep/MultiMC/libraries/com/mojang/netty/1.6/netty-1.6.jar
  C:/Users/Ethan/Downloads/Keep/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/Users/Ethan/Downloads/Keep/MultiMC/libraries/net/java/dev/jna/jna/3.4.0/jna-3.4.0.jar
  C:/Users/Ethan/Downloads/Keep/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/Users/Ethan/Downloads/Keep/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Users/Ethan/Downloads/Keep/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/4.6/jopt-simple-4.6.jar
  C:/Users/Ethan/Downloads/Keep/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  C:/Users/Ethan/Downloads/Keep/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  C:/Users/Ethan/Downloads/Keep/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  C:/Users/Ethan/Downloads/Keep/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  C:/Users/Ethan/Downloads/Keep/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  C:/Users/Ethan/Downloads/Keep/MultiMC/libraries/io/netty/netty-all/4.0.23.Final/netty-all-4.0.23.Final.jar
  C:/Users/Ethan/Downloads/Keep/MultiMC/libraries/com/google/guava/guava/17.0/guava-17.0.jar
  C:/Users/Ethan/Downloads/Keep/MultiMC/libraries/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar
  C:/Users/Ethan/Downloads/Keep/MultiMC/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar
  C:/Users/Ethan/Downloads/Keep/MultiMC/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar
  C:/Users/Ethan/Downloads/Keep/MultiMC/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
  C:/Users/Ethan/Downloads/Keep/MultiMC/libraries/com/mojang/authlib/1.5.21/authlib-1.5.21.jar
  C:/Users/Ethan/Downloads/Keep/MultiMC/libraries/com/mojang/realms/1.7.59/realms-1.7.59.jar
  C:/Users/Ethan/Downloads/Keep/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/Ethan/Downloads/Keep/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/Ethan/Downloads/Keep/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/Ethan/Downloads/Keep/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/Ethan/Downloads/Keep/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9/log4j-api-2.0-beta9.jar
  C:/Users/Ethan/Downloads/Keep/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9/log4j-core-2.0-beta9.jar
  C:/Users/Ethan/Downloads/Keep/MultiMC/libraries/tv/twitch/twitch/6.5/twitch-6.5.jar
  C:/Users/Ethan/Downloads/Keep/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/Users/Ethan/Downloads/Keep/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/Users/Ethan/Downloads/Keep/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.1/lwjgl-2.9.1.jar
  C:/Users/Ethan/Downloads/Keep/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.1/lwjgl_util-2.9.1.jar
  C:/Users/Ethan/Downloads/Keep/MultiMC/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  C:/Users/Ethan/Downloads/Keep/MultiMC/libraries/java3d/vecmath/1.5.2/vecmath-1.5.2.jar
  C:/Users/Ethan/Downloads/Keep/MultiMC/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  C:/Users/Ethan/Downloads/Keep/MultiMC/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  C:/Users/Ethan/Downloads/Keep/MultiMC/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  C:/Users/Ethan/Downloads/Keep/MultiMC/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  C:/Users/Ethan/Downloads/Keep/MultiMC/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  C:/Users/Ethan/Downloads/Keep/MultiMC/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  C:/Users/Ethan/Downloads/Keep/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar
  C:/Users/Ethan/Downloads/Keep/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar
  C:/Users/Ethan/Downloads/Keep/MultiMC/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  C:/Users/Ethan/Downloads/Keep/MultiMC/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  C:/Users/Ethan/Downloads/Keep/MultiMC/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  C:/Users/Ethan/Downloads/Keep/MultiMC/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  C:/Users/Ethan/Downloads/Keep/MultiMC/libraries/jline/jline/2.13/jline-2.13.jar
  C:/Users/Ethan/Downloads/Keep/MultiMC/libraries/org/ow2/asm/asm-all/5.0.3/asm-all-5.0.3.jar
  C:/Users/Ethan/Downloads/Keep/MultiMC/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  C:/Users/Ethan/Downloads/Keep/MultiMC/libraries/net/minecraftforge/forge/1.8.9-11.15.1.1722/forge-1.8.9-11.15.1.1722-universal.jar
  C:/Users/Ethan/Downloads/Keep/MultiMC/versions/1.8.9/1.8.9.jar

Params:
  [--username, <PROFILE NAME>, --version, MultiMC5, --gameDir, C:/Users/Ethan/Downloads/Keep/MultiMC/instances/HQM Pack /minecraft, --assetsDir, C:/Users/Ethan/Downloads/Keep/MultiMC/assets, --assetIndex, 1.8, --uuid, <PROFILE ID>, --accessToken, <ACCESS TOKEN>, --userProperties, {}, --userType, mojang, --tweakClass, net.minecraftforge.fml.common.launcher.FMLTweaker]

Window size: 854 x 480

Preparing native libraries...
Extracting twitch-platform-6.5-natives-windows-64.jar
Extracting twitch-external-platform-4.5-natives-windows-64.jar
Extracting jinput-platform-2.0.5-natives-windows.jar
Extracting lwjgl-platform-2.9.1-natives-windows.jar

Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395)
	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)
Caused by: java.lang.UnsatisfiedLinkError: Could not load library. Reasons: [no jansi in java.library.path, null]
	at org.fusesource.hawtjni.runtime.Library.doLoad(Library.java:182)
	at org.fusesource.hawtjni.runtime.Library.load(Library.java:140)
	at org.fusesource.jansi.internal.Kernel32.<clinit>(Kernel32.java:37)
	at org.fusesource.jansi.WindowsAnsiOutputStream.<clinit>(WindowsAnsiOutputStream.java:52)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.apache.logging.log4j.core.appender.ConsoleAppender.getOutputStream(ConsoleAppender.java:128)
	at org.apache.logging.log4j.core.appender.ConsoleAppender.getManager(ConsoleAppender.java:104)
	at org.apache.logging.log4j.core.appender.ConsoleAppender.createAppender(ConsoleAppender.java:99)
	at org.apache.logging.log4j.core.config.DefaultConfiguration.<init>(DefaultConfiguration.java:53)
	at org.apache.logging.log4j.core.LoggerContext.<init>(LoggerContext.java:63)
	at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.locateContext(ClassLoaderContextSelector.java:217)
	at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:114)
	at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:81)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:83)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:34)
	at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:387)
	at net.minecraft.launchwrapper.LogWrapper.configureLogging(LogWrapper.java:14)
	at net.minecraft.launchwrapper.LogWrapper.log(LogWrapper.java:28)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:94)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	... 8 more
Exiting with -1
Process exited with code -1.

**Comment by QuImUfu** [comment] 2016-09-28 04:39
seems to be sort of an log4j windows specific [problem] (https://issues.apache.org/jira/browse/LOG4J2-1461).
You could try the workaround mentioned in the bug report and add "-Dlog4j.skipJansi=true" to you java arguments.
I think this should prevent this error, but it is only a workaround, i don't know what the actual problem is.

**Comment by Wraithcraft** [comment] 2016-09-28 06:13
I tried that, relaunched, it crashed again with a slightly longer error message.
[](http://hastebin.com/bapacuciju.md)

**Comment by QuImUfu** [comment] 2016-09-28 12:34
O.o 
You instance-folder name seems to end with an space. Java seems to be bothered by this on windows. Try renaming the instance folder to something without a space at the end.

**Comment by QuImUfu** [comment] 2016-09-28 19:33
Has this fixed you problem? If yes please close the issue.

**Comment by jikuja** [comment] 2016-09-28 19:37
If this is reproduciable peterix should be pinged and check added for instance name checking code.

**Comment by Wraithcraft** [comment] 2016-09-28 21:39
I have fixed the issue, I just copied everything over to a new instance, windows gave me an error when I tried to edit the file name.

**Closed** 2016-09-28 21:40 UTC

**Comment by QuImUfu** [comment] 2016-09-28 22:55
@jikuja already on [workflowy](https://workflowy.com/s/2EyDMcp7CU#/eb92606276eb).
